### ISSUE TITLE
Size quotas appear to be broken

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#1003]
I made a new non-admin user on data.kitware.com, where the default quota is 2GB. When I view my quota as that user, however, I see:

![screen shot 2015-09-30 at 3 24 47 pm](https://cloud.githubusercontent.com/assets/555959/10204019/68d30606-6787-11e5-9c2a-e4a626d8a52d.png)

But as an admin, I am told that the default 2GB limit applies:

![screen shot 2015-09-30 at 3 21 07 pm](https://cloud.githubusercontent.com/assets/555959/10204027/723d886a-6787-11e5-9ba5-13c6a293113a.png)

It also doesn't seem to be enforced; @danlamanna was able to upload well past the default quota.

ping @manthey any idea why this happens?

**Comment by manthey** [comment]
Fixed in PR #1004.
