### ISSUE TITLE
Add an option to not automatically create "Private" folders

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#1007]

**Comment by zachmullen** [comment]
(when creating a collection)

Also public folder if the collection is public. Probably just a single flag that says "createFolders=True" on createCollection.

**Comment by zachmullen** [comment]
Does anybody care if we create these default folders at all? We could honestly just remove this behavior altogether and I doubt anyone would miss it. ping @girder/developers for comments.

**Comment by jcfr** [comment]
:+1: for removing it. It is easy enough to create folders.

**Comment by jeffbaumes** [comment]
+1
