### ISSUE TITLE
Item with Job

### ISSUE THREAD

**Issue by motticus** [girder/girder#1015]
This may already be implemented but I am not sure.  

How do I allow for a 1 to 1 correspondence between an item (item id) and a job that is executed based on a romanesco task (job id)? 

thanks

**Comment by jeffbaumes** [comment]
The `item/:id/romanesco` endpoint allows you to create romanesco jobs based on the romanesco task defined in the item's metadata. This task can be run multiple times, however, so it is not strictly 1-to-1. Can you give a bit more detail for what you are attempting to accomplish here?

**Comment by motticus** [comment]
I have a dynamic process which allows a user to execute analysis tools externally (something related to a queue).  The process finds a listing of items under item/ and then executes them via item/:id/romanesco.   To verify status i need item/:itemid/romanesco/:jobid/status.  To verify results i use item/:itemid/romanesco/:jobid/result.  No issue.  

The problem I have is tying jobid back to itemid.  The dynamic process allows to view results later but the results (job) must be tied back to an item.  How can that be done?  If i pull a listing of jobs it doesnt have the item id within.

**Comment by jeffbaumes** [comment]
Got it - I think I understand now. @zachmullen is it possible to include this back-link to an item in the job metadata? Could it automatically be added when running the `item/:id/romanesco` endpoint?

**Comment by zachmullen** [comment]
That's definitely possible, but would require a change in romanesco. We could just add something [here](https://github.com/Kitware/romanesco/blob/master/server/__init__.py#L146) as a special field on the job that the plugin could expose.

**Comment by zachmullen** [comment]
@motticus I marked this as fixed, but feel free to reopen if this doesn't fully address what you wanted. The latest master of romanesco will now put a `romanescoItemId` field in the job document.

**Comment by motticus** [comment]
The romanescoitemid does not show up when i execute a job.  The field is not there: 

    job['romanescoItemId'] = item['_id']

However, If i make the change into the kwargs and add the field, it does show up: 

    kwargs['jobInfo'] = {
        'url': '{}/job/{}'.format(apiUrl, job['_id']),
        'method': 'PUT',
        'headers': {'Girder-Token': jobToken['_id']},
        'logPrint': True,
        'romanescoitemid': item['_id']
    }

**Comment by zachmullen** [comment]
@motticus, sorry, there was a second commit, we moved it to `job['meta']['romanescoItemId']`.
