### ISSUE TITLE
referencing closed issue #1015

### ISSUE THREAD

**Issue by motticus** [girder/girder#1016]
This is a request to add the item id to the job so the requestor can be referenced.  

The romanescoitemid does not show up when i execute a job. The field is not there:

job['romanescoItemId'] = item['_id']
However, If i make the change into the kwargs and add the field, it does show up:

kwargs['jobInfo'] = {
    'url': '{}/job/{}'.format(apiUrl, job['_id']),
    'method': 'PUT',
    'headers': {'Girder-Token': jobToken['_id']},
    'logPrint': True,
    'romanescoitemid': item['_id']
}

**Comment by zachmullen** [comment]
Hi @motticus,

The field is now under `job['meta']['romanescoItemId']` as of https://github.com/Kitware/romanesco/pull/173. Can you verify for me whether you are able to access i there?

**Comment by motticus** [comment]
Works like a champ.  Thanks for your help getting this into the codebase quickly.   +1:

**Comment by zachmullen** [comment]
No problem, let us know if you need any further changes :smile:
