### ISSUE TITLE
girder-install web fails

### ISSUE THREAD

**Issue by dzenanz** [girder/girder#1020]
I followed the [docs](https://girder.readthedocs.org/en/latest/installation.html), and when I got to step `girder-install web`, it failed. `sudo girder-install web` fails in the same way. Here is the output:
```
[dzenan@localhost ~]$ girder-install web
Could not import girder.  Please ensure that your PYTHONPATH is correct.
[dzenan@localhost ~]$ python
Python 2.7.8 (default, Jul  5 2015, 14:16:16) 
[GCC 4.9.2 20150212 (Red Hat 4.9.2-6)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import girder
>>> 
[dzenan@localhost ~]$ echo $PYTHONPATH

[dzenan@localhost ~]$
```
I am using Fedora 21. `uname -a` gives `Linux localhost.localdomain 3.18.9-200.fc21.x86_64 #1 SMP Mon Mar 9 15:10:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by jbeezley** [comment]
Are you able to run the girder server (`python -m girder`)?

**Comment by dzenanz** [comment]
```
[dzenan@localhost ~]$ python -m girder
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/site-packages/girder/__main__.py", line 57, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/girder/__main__.py", line 50, in main
    server.setup(args.testing)
  File "/usr/lib/python2.7/site-packages/girder/utility/server.py", line 132, in setup
    root, appconf = configureServer(test, plugins, curConfig)
  File "/usr/lib/python2.7/site-packages/girder/utility/server.py", line 91, in configureServer
    from girder.api import api_main
  File "/usr/lib/python2.7/site-packages/girder/api/api_main.py", line 22, in <module>
    from . import describe
  File "/usr/lib/python2.7/site-packages/girder/api/describe.py", line 26, in <module>
    from . import docs, access
  File "/usr/lib/python2.7/site-packages/girder/api/access.py", line 23, in <module>
    from girder.api import rest
  File "/usr/lib/python2.7/site-packages/girder/api/rest.py", line 38, in <module>
    from six.moves import range
ImportError: cannot import name range
[dzenan@localhost ~]$ 
```

**Comment by jbeezley** [comment]
That's odd.  What happens if you do: `pip install -U girder`

**Comment by dzenanz** [comment]
[dzenan@localhost ~]$ pip install -U girder
Requirement already up-to-date: girder in /usr/lib/python2.7/site-packages
Requirement already up-to-date: cffi==0.8.6 in /usr/lib64/python2.7/site-packages (from girder)
Requirement already up-to-date: CherryPy==3.7.0 in /usr/lib/python2.7/site-packages (from girder)
Requirement already up-to-date: pymongo==2.8 in /usr/lib64/python2.7/site-packages (from girder)
Requirement already up-to-date: bcrypt==1.1.1 in /usr/lib64/python2.7/site-packages (from girder)
Requirement already up-to-date: boto==2.38.0 in /usr/lib/python2.7/site-packages (from girder)
Requirement already up-to-date: Mako==1.0.0 in /usr/lib/python2.7/site-packages (from girder)
Requirement already up-to-date: PyYaml==3.11 in /usr/lib64/python2.7/site-packages (from girder)
Requirement already up-to-date: requests==2.3.0 in /usr/lib/python2.7/site-packages (from girder)
Requirement already up-to-date: psutil==2.1.3 in /usr/lib64/python2.7/site-packages (from girder)
Requirement already up-to-date: six==1.9.0 in /usr/lib/python2.7/site-packages (from girder)
Requirement already up-to-date: pycparser in /usr/lib/python2.7/site-packages (from cffi==0.8.6->girder)
Requirement already up-to-date: MarkupSafe>=0.9.2 in /usr/lib64/python2.7/site-packages (from Mako==1.0.0->girder)
Cleaning up...
[dzenan@localhost ~]$

**Comment by jbeezley** [comment]
I'm thinking there might be an old `six` install somewhere.  What about
```
python -c 'import sys; print "\n".join(sys.path)'
```
and
```
python -c 'import six; print six.__file__'
```

You would probably have better luck installing into a virtualenv rather than the system site-packages.

**Comment by dzenanz** [comment]
[dzenan@localhost ~]$ python -c 'import sys; print "\n".join(sys.path)'

/usr/lib64/python27.zip
/usr/lib64/python2.7
/usr/lib64/python2.7/plat-linux2
/usr/lib64/python2.7/lib-tk
/usr/lib64/python2.7/lib-old
/usr/lib64/python2.7/lib-dynload
/usr/lib64/python2.7/site-packages
/usr/lib64/python2.7/site-packages/gtk-2.0
/usr/lib/python2.7/site-packages
[dzenan@localhost ~]$ python -c 'import six; print six.__file__'
/usr/lib/python2.7/site-packages/six.pyc
[dzenan@localhost ~]$

**Comment by jbeezley** [comment]
I guess I would try to reinstall the dependencies.
```
pip install -I -U --force-reinstall girder
```
If that doesn't work, I'm all out of ideas.

**Comment by dzenanz** [comment]
That did it. After that command, `sudo girder-install web` succeeded. Thank you!
