### ISSUE TITLE
pymongo.MongoReplicaSetClient is deprecated

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#1022]
We can now just use `MongoClient` unconditionally with the `replicaSet` kwarg, so we should remove [this code](https://github.com/girder/girder/blob/6fe7e9538227939ce62f70e8bd83f08fb7d1af0e/girder/models/__init__.py#L83-L86).

**Comment by zachmullen** [comment]
More info: http://api.mongodb.org/python/current/api/pymongo/mongo_replica_set_client.html

**Comment by manthey** [comment]
pymongo's interface has deprecated quite a bit, including renaming parameters for some functions.  For instance, `insert` and `remove` are deprecated (see https://api.mongodb.org/python/current/changelog.html).  We certainly use both in the gridfs assetstore code, and use remove in lots of code.  If we want to be purely pymongo 3 compliant, this is a bigger task than just changing to `MongoClient`.

**Comment by zachmullen** [comment]
I'd be fine with doing such an overhaul -- I think the only pymongo details that we leak at the moment are `pymongo.ASC/DESC`, which hopefully haven't changed in 3.0.

**Comment by zachmullen** [comment]
(and for those constants, we should squash them out and replace with our own `girder.constants.ASC/DESC`)

**Comment by cpatrick** [comment]
:+1: to squashing that leakage.
