### ISSUE TITLE
Consider replacing underscore.js with lodash.js

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#1038]
https://stackoverflow.com/questions/13789618/differences-between-lodash-and-underscore
http://benmccormick.org/2014/11/12/underscore-vs-lodash/
https://github.com/lodash/lodash/wiki/Migrating

**Comment by danlamanna** [comment]
+1 - I think the only major concern here is lodash being roughly twice the size of underscore.

I think most of us have been [spoiled by lodash by now](https://github.com/Kitware/minerva/blob/6e2b86637e3c419c1f49e3776406b779d740a8de/web_external/js/models/DatasetModel.js#L293-L294).

**Comment by zachmullen** [comment]
I followed the drama of this fork a while ago and it left a bad taste in my mouth; I've never seen such a fuss about such a tiny issue. Both parties came out looking pretty bad IMO.

Anyway, that's neither here nor there &mdash; my vote would be that we maintain the status quo until we find a compelling reason to switch, especially if what @danlamanna says is true about the larger footprint. If it's a question of performance, some benchmarking would be helpful if we think our underscore methods are slowing us down. For stuff like the recursive `has`, it would be really easy for us to implement that ourselves.

**Comment by jbeezley** [comment]
It looks to be about 3x difference for the latest version actually (this is the "modern" build of lodash even):
```
-rw-r-----@ 1 jbeezley  staff  52646 Oct 26 09:09 lodash.min.js
-rw-r-----@ 1 jbeezley  staff  16449 Oct 26 09:08 underscore-min.js
```

Personally, I would probably use lodash for a new project, but I tend to agree with @zachmullen on wanting a real compelling reason to make the switch.

**Comment by brianhelba** [comment]
What first brought me to lodash is that they do proper semantic versioning with comprehensively release notes and migration guides. Underscore doesn't produce any release notes, which wouldn't be such a problem except that they also refuse to use semantic versioning.

On the feature side of things, I also much prefer their chaining syntax and convenience. Their extra functions are nice, but I've personally not needed them much yet.

I agree that the build size is an issue, but according to [this article](http://benmccormick.org/2014/11/12/underscore-vs-lodash/) from a year ago: 
> If you want to drop the Lo-Dash extra functionality entirely, and only use it for performance and usability reasons, you can build an underscore compatible version and use only 20kb. You can also go even further, and for instance use only the functionality required by Backbone. That will get you down to 13kb, smaller than the original Underscore library.

To get the smaller size, you need to do a modular build, but lodash includes a [Grunt module](https://www.npmjs.com/package/grunt-lodash), to let you create one as part of your normal Grunt workflow.

If size is really the only thing holding us back, I'd suggest that we explore the modular builds in more detail (once someone has the time to actually do so).

**Comment by ronichoudhury** [comment]
On Sat, Oct 24, 2015 at 10:50 PM Dan LaManna <notifications@github.com>
wrote:

> I think most of us have been spoiled by lodash by now
> <https://github.com/Kitware/minerva/blob/6e2b86637e3c419c1f49e3776406b779d740a8de/web_external/js/models/DatasetModel.js#L293-L294>
> .
>
We just need monads in JavaScript and then everything will be great! :-P

**Comment by danlamanna** [comment]
If there's any specific functionality we want, I just stumbled upon [underscore-contrib](http://documentcloud.github.io/underscore-contrib/) which would let us plug in any of the sub-libraries documented.

**Comment by ronichoudhury** [comment]
Monadic lists! :-P http://documentcloud.github.io/underscore-contrib/#mapcat

Lots of other cool stuff in here too. Thanks for the tip Dan.

**Comment by sebastienbarre** [comment]
In the webpack branch, you wouldn't ever include the whole `lodash`, but only pieces of it.
e.g. 
```
var _assign   = require('lodash/object/assign');
```
or
```
import padStart from 'lodash/padStart';
```
See [Using Lodash as a Collection of Micro-Libraries](http://knpw.rs/blog/using-lodash)

**Comment by brianhelba** [comment]
[babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash) will allow us to naively import the whole `lodash` in code, but have the build system grab only the modules that we need.

**Comment by danlamanna** [comment]
Is this still relevant?

**Comment by zachmullen** [comment]
No, insofar as the backbone client is no longer getting new features.
