### ISSUE TITLE
Add a packaging test for email templates

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#1042]
Email templates must be explicitly copied to a new installation package in ``setup.py``'s ``package_data`` argument. The packaging tests should be updated to also test that email and webroot templates are found and rendered.

**Comment by zachmullen** [comment]
Our tests now verify the existence of the email templates in both the [sdist package](https://github.com/girder/girder/blob/master/tests/packaging/test_package_contents.py#L17-L20) and the [pip install directory](https://github.com/girder/girder/blob/master/tests/packaging/pip_install_girder.sh#L28-L32). The webroot templates are rendered [here](https://github.com/girder/girder/blob/master/tests/packaging/pip_install_girder.sh#L120-L132).

If you think we need more testing beyond this, please reopen.
