### ISSUE TITLE
Swagger path is wrong on proxies

### ISSUE THREAD

**Issue by manthey** [girder/girder#1054]
PR #954 was a change to eliminate an extra `./` in the path of the swagger api calls.  Unfortunately, this was done by using the absolute path, which breaks easy use of the api when Girder is hosted through a proxy.

I'm not sure how to fix both problems with the current version of Swagger without monkey-patching.  Alternatively, we can use the current code when _not_ using a proxy and the old form of using an api base path of `.` when using a proxy.

**Comment by manthey** [comment]
@zachmullen Since you made PR #954, I was wondering if you had a suggestion for this.

**Comment by zachmullen** [comment]
Sorry, not sure how to get this working in all cases.

**Comment by manthey** [comment]
I see four possible ways to address this:

* Revert to using `.` as the basePath.  This results in the problem original reported in #948, though this is essentially a cosmetic issue.

* Detect if we are in a proxy via tools.proxy.on, and, if so, use `.` and if not use `getApiUrl()`.  This means we'll still have the ugly extra `./` when behind a proxy, and if the user setting up girder fails to add the proxy setting, we'll still have the current issue.

* Have a config setting that can override this value.  Recommend setting it to `.` if you are in a proxy and need to access the swagger interface both inside and outside of the proxy, or to `(proxy url)/api/v1` if you only need to access it from outside of the proxy.

* Monkey patch swagger to strip out the offending `./`.  We would have to make sure this doesn't break any time we changed swagger-ui versions.

I think the third method is probably the best choice of these.

**Comment by manthey** [comment]
Resolved in PR #1793.
