### ISSUE TITLE
Try porting to boto3

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#1059]
We currently have no less than three hacks in our s3 assetstore adapter to workaround limitations or outright bugs in boto.

Boto has transitioned to a completely new repo and package (boto3), and has all but stopped maintenance on the old package. Hopefully in moving to the new package we will be able to get rid of some or all of our workarounds.

**Comment by zachmullen** [comment]
Refs #1058

**Comment by manthey** [comment]
We moved to boto3 in PR #2132.
