### ISSUE TITLE
Grunt is not finding plugins from plugin_directory

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#1068]
Girder [server supports plugins](https://github.com/girder/girder/blob/d42b3817b16f69a3992c05c750c840956d3df31f/girder/utility/plugin_utilities.py#L195) from the location specified by the configuration option ``plugins.plugin_directory``.

However, Grunt only [looks for and builds plugins](https://github.com/girder/girder/blob/d42b3817b16f69a3992c05c750c840956d3df31f/Gruntfile.js#L451) in the ``plugins/*`` directory, and does not also search this configured path. The result is that while ``plugin_directory`` is quite useful for server-side plugins, is useless for client-side plugins.

The Gruntfile should be updated to remedy this.

**Comment by brianhelba** [comment]
@danlamanna Ping.

**Comment by brianhelba** [comment]
@girder/developers Do the recent changes by @jbeezley do anything to help address this bug? Assuming that it's still an issue, does anyone have time to fix this? I have funding available (contact me via email), if it will take any significant time.

**Comment by danlamanna** [comment]
It shouldn't take much time at all, I'm just waiting for the changes to our build process to settle down before addressing it.

**Comment by jbeezley** [comment]
Yeah, we should definitely wait until #1084 lands.

**Comment by brianhelba** [comment]
Great, thanks. Fixing this issue will be quite helpful to some of my Girder deployments.

**Comment by brianhelba** [comment]
I could possibly be convinced, but I don't understand ``girder-install plugin`` well enough at the moment. Let's have a quick Hangout to review it when you have time, @zachmullen .

**Comment by brianhelba** [comment]
@zachmullen explained ``girder-install plugin`` to me, and I'm satisfied that once https://github.com/girder/girder/pull/1088 goes in, it will satisfy all the requirements of this issue.
