### ISSUE TITLE
Create utility for gating multiple async events

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#1072]
It's a fairly common pattern to want to wait for several asynchronous events at the same time, and only proceed with a callback once all of them have finished. It's trivial in the case of a single asynchronous event, but when there is more than one, you either have to chain them consecutively, or maintain your own data structure and logic for testing whether they're all finished or not, which is cumbersome. It would be nice to add a utility to Girder core with the following semantics:

```
var gate = new girder.AsyncGate(function () {
    // behavior to be executed when all registered events have finished
    this.render();
}, this)
    .waitFor(someModel, 'g:fetched')
    .waitFor(someCollection, 'g:fetched');
```

Then it's easy enough to add things like timeout, error handlers, etc. onto this prototype.

**Comment by zachmullen** [comment]
Sorry, not sure why "gate" was in my head, what I was thinking of was "fence". If anyone can come up with better nomenclature I'm all ears.

**Comment by manthey** [comment]
jquery uses `deferred`, `when`, and `promise`.

**Comment by mgrauer** [comment]
Yes, this would definitely be useful, and I hope would have a slimming effect.

```
  session.set({
        _id: id
  }).once('m:fetched', function () {
        var datasetsCollection = new minerva.collections.DatasetCollection();
        datasetsCollection.once('g:changed', function () {
            var analysisCollection = new minerva.collections.AnalysisCollection();
            analysisCollection.once('g:changed', function () {
                var sourceCollection = new minerva.collections.SourceCollection();
                sourceCollection.once('g:changed', function () {
                    girder.events.trigger('g:navigateTo', minerva.views.SessionView, {
                        analysisCollection: analysisCollection,
                        datasetsCollection: datasetsCollection,
                        sourceCollection: sourceCollection,
                        session: session
                    });
                }).fetch();
            }).fetch();
        }).fetch();
  }, this).on('g:error', function () {
        minerva.router.navigate('sessions', {trigger: true});
  }, this).fetch();
```

**Comment by cjh1** [comment]
angular has:

```
$q.all(...)
```

This takes an array promises and return a promise that is resolved when all the others have been resolved ....

**Comment by cjh1** [comment]
(Javascript 6 uses the same sort of syntax ...) [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all]

**Comment by jbeezley** [comment]
A big improvement would be to make the async calls (fetch, sync, save, delete, etc) return the jqXHR object returned by the `restRequest`.  This is what the normal backbone methods do.  jqXHR objects are "pseudo" promises that support `.then(...)` chaining along with most of the other promise goodness.

This is an easy change to make, but it has problems with backward compatibility for any callers expecting these calls to return `this`.  This should probably be targeted for 2.0.

**Comment by brianhelba** [comment]
This should be resolved by the conversion to using promises instead of events to handle single asynchronous completions that we know are going to happen. From this perspective, gating multiple events no longer even makes much sense, as events can fire any number of times, and as a result of externally-controlled operations.

I'm closing this now, but feel free to reopen if anyone still sees a need for this, or wants to discuss more.
