### ISSUE TITLE
Notification and policy for pre-1.0 plugins

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#1091]
In order to allow plugins to be contributed upstream as soon as possible, our development policy should permit the contribution pre-1.0 plugins, without a stable API or  complete functionality, provided that there is a reliable ongoing effort to bring them to a 1.0 release and that they meet basic standards for code quality.

To prevent these pre-1.0 plugins from confusing end-users, we should add some logic to the plugin settings page to flag any plugin with a ``version < 1.0.0`` as "experimental" in some way (confirmation when enabling, special icon / color, etc.).

This also has the bonus of promoting the use of semantic versioning in plugins, which has been somewhat neglected.

If this proposal is ratified, action items to closing this issue are:
* add documentation of the plugin contribution policy
* add pre-1.0 checking logic to the plugin display page

**Comment by cpatrick** [comment]
:+1:

**Comment by zachmullen** [comment]
This is easy enough to implement, and I like the idea. :+1:

**Comment by zachmullen** [comment]
After our policy discussion this morning, we decided to go forward with this feature.
