### ISSUE TITLE
Add option for instance brand name

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#1093]
Currently, emails automatically sent by Girder core have the brand name `"Girder"` hardcoded in their subject line:
- [`"Girder: You've been invited to a group"`](https://github.com/girder/girder/blob/3d869245e8650cc71ab5b56975fe45f57c6f78b8/girder/api/v1/group.py#L277)
- [`'Girder: Password reset'`](https://github.com/girder/girder/blob/3d869245e8650cc71ab5b56975fe45f57c6f78b8/girder/api/v1/user.py#L308)
- [`'Girder: Temporary access'`](https://github.com/girder/girder/blob/3d869245e8650cc71ab5b56975fe45f57c6f78b8/girder/api/v1/user.py#L337)

Girder should support some sort of "brand name" setting, (which would default to `"Girder"`) that would be templated into these email subject lines.

Additionally, this "brand name" should be automatically templated into / used in:
- [email body headers](https://github.com/girder/girder/blob/3d869245e8650cc71ab5b56975fe45f57c6f78b8/girder/mail_templates/_header.mako#L3)
- [email body footers](https://github.com/girder/girder/blob/3d869245e8650cc71ab5b56975fe45f57c6f78b8/girder/mail_templates/_footer.mako)
- [the Webroot `title` property](https://github.com/girder/girder/blob/3d869245e8650cc71ab5b56975fe45f57c6f78b8/girder/utility/webroot.py#L89), for use in the [HTML title](https://github.com/girder/girder/blob/3d869245e8650cc71ab5b56975fe45f57c6f78b8/girder/utility/webroot.mako#L5)
- [the main layout header](https://github.com/girder/girder/blob/3d869245e8650cc71ab5b56975fe45f57c6f78b8/clients/web/src/templates/layout/layoutHeader.jade#L2)
- possibly [the front page](https://github.com/girder/girder/blob/3d869245e8650cc71ab5b56975fe45f57c6f78b8/clients/web/src/templates/body/frontPage.jade), but most non-trivial Girder deployments will want to override that with more custom text

**Comment by jcfr** [comment]
:+1:

**Comment by brianhelba** [comment]
@girder/developers Does anyone have time to work on this?

**Comment by zachmullen** [comment]
I can take a look at it.

**Comment by Pierre-Assemat** [comment]
Link where the brand name is used : 
https://github.com/girder/girder/blob/28d3b6679d1eb2c3e3e1c910c13cc390ac65b4d8/girder/utility/error.mako#L3
https://github.com/girder/girder/blob/2e832eb7a8fe908e3c41267b994e9556eeb039f7/clients/web/test/testEnv.pug#L5
https://github.com/girder/girder/blob/57231f3984e268822359d72320580dac439093e2/clients/jquery/browser/index.html#L4
https://github.com/girder/girder/blob/46aea1ed313283cfe676546fed36cafa03fe1b7c/plugins/worker/web_client/templates/configView.pug#L4
https://github.com/girder/girder/blob/57231f3984e268822359d72320580dac439093e2/girder/mail_templates/temporaryAccess.mako#L5
https://github.com/girder/girder/blob/46aea1ed313283cfe676546fed36cafa03fe1b7c/plugins/google_analytics/web_client/templates/configView.pug#L3
https://github.com/girder/girder/blob/1635e20230978448ac6026567271e635c5cad837/clients/jquery/browser/index.js#L30
https://github.com/girder/girder/blob/310accc1f3dfd3ca3567d76d77a089149e874521/girder/api/api_docs.mako#L23
https://github.com/girder/girder/blob/46aea1ed313283cfe676546fed36cafa03fe1b7c/clients/web/src/templates/body/filesystemImport.pug#L11
https://github.com/girder/girder/blob/46aea1ed313283cfe676546fed36cafa03fe1b7c/plugins/hdfs_assetstore/web_client/templates/newAssetstoreWidgetCreate.pug#L14
https://github.com/girder/girder/blob/25251fca0ff5354e1e9db3d2438fbbc8e85180ce/clients/web/src/templates/widgets/editAssetstoreWidget.pug#L27
https://github.com/girder/girder/blob/25251fca0ff5354e1e9db3d2438fbbc8e85180ce/clients/web/src/templates/widgets/newAssetstore.pug#L57

**Comment by Pierre-Assemat** [comment]
@brianhelba What do you think about all these file, I'm not sure we need to change them all

**Comment by brianhelba** [comment]
In my opinion, the references at:
* the email template, `girder/girder/mail_templates/temporaryAccess.mako`
* the API doc page, `girder/girder/api/api_docs.mako`

refer to a particular running instance and face normal users, so they should use the brand name. The other places either refer to Girder as a software package or do not face normal users, so they don't need to change.
