### ISSUE TITLE
Replace argv NPM package

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#1096]
The "argv" NPM package causes annoying ``WARN package.json argv@0.0.2 No repository field.`` warnings every time NPM is run, and is clearly [no longer an active or supported project](https://www.npmjs.com/package/argv).

We should replace "argv" with a better-supported argument parser. A bit of searching reveals ["yargs"](https://www.npmjs.com/package/yargs) as a fully-featured command line option tool, and ["minimist"](https://www.npmjs.com/package/minimist) to just parse the arguments (but not display options).

**Comment by zachmullen** [comment]
ping @jcfr since he introduced the argv package. yargs seems like a better choice.
