### ISSUE TITLE
Fix grunt watch for plugins

### ISSUE THREAD

**Issue by jbeezley** [girder/girder#1104]
There are a couple of problems with the grunt watch task particularly applied to plugin development.

1. The plugin specific tasks aren't initialized until the `plugin` task is run (see [here](https://github.com/girder/girder/blob/master/grunt_tasks/plugin.js#L212)).  For the moment, we can work around this by running `grunt plugin watch` instead, but that block of code should be moved to the previous loop where the plugins are detected.

2.  It appears as if some of the globs in the subtask definitions are picking up wrong and/or extra paths.  See https://github.com/Kitware/minerva/issues/208.

**Comment by mgrauer** [comment]
Update developer docs as necessary based on the outcome here.  We [describe](https://github.com/girder/girder/blob/master/docs/development.rst#configuring-your-development-environment) how to use `grunt watch` as part of the dev workflow.

**Comment by zachmullen** [comment]
Something else I noticed: changing a jade file causes the jade task to correctly rebuild, but we also need to re-run uglify as well since the template javascript gets minified along with the rest.

**Comment by jbeezley** [comment]
Yes, that is the most annoying part of `watch` that I noticed.  When a change in one file triggers building the new file, it doesn't trigger builds that the new file would normally trigger so you have to specify the entire dependency tree for each watch task.
