### ISSUE TITLE
Update source install docs post 1.4.1

### ISSUE THREAD

**Issue by mgrauer** [girder/girder#1116]
- need to specify a minimum npm version of 2, possibly a "sudo npm install -g npm" for an npm update
- need to restate "npm install" as "npm install --unsafe-perm" or "sudo npm install --unsafe-perm"
- we say to "pip install -r requirements.txt", should we suggest "scripts/InstallPythonRequirements.py", with or without "--mode=dev" instead?

**Comment by mgrauer** [comment]
If possible, can we clean up the errors and warnings tied into subtasks from the "sudo npm install --unsafe-perm" step?  It would make administrators and people trying the software out feel better.  At least we could add a note saying to expect these subtask errors/warnings, and as long as the overall task succeeds, that is what matters.

**Comment by jbeezley** [comment]
Most (if not all) of the warnings come from dependencies, so we won't be able to do much about it.

On another note, we could recommend the `--production` flag for deployment.  That will reduce the number of dependencies and may provide some additional optimizations.
