### ISSUE TITLE
Be able to specify Content-Disposition=inline response header for downloads

### ISSUE THREAD

**Issue by mgrauer** [girder/girder#1118]
I need to have pdfs displayed in the browser, and currently the only way I can get it to work is to have an HTML `object` element with the `data` attribute pointing to a file download path.  The problem is that I need to set

    cherrypy.response.headers['Content-Disposition'] = 'inline'

in order for this to display on Chrome and FF.  FF also requires me to change from the default PDF viewer to "Preview in Firefox", at least on Mac, but there's not much we can do about that here.  Safari works even without the change, which may mean it's doing the wrong thing, but it also works for "inline".

To support this, I was going to add an extra optional param (inlineContentDisposition=True) on the [File download endpoint](https://github.com/girder/girder/blob/7f9d0d14b051e8560e787f8d72f0e2f6c5e4beb5/girder/api/v1/file.py#L210-L247) and pass it through the File model, through the various assetstore_adapter implementations, and then back up to the abstract_assetstore_adapter [setContentHeaders](https://github.com/girder/girder/blob/7f9d0d14b051e8560e787f8d72f0e2f6c5e4beb5/girder/utility/abstract_assetstore_adapter.py#L199-L218) function.

Any concerns?

**Comment by zachmullen** [comment]
Nice, this is something we've needed for a long time. We should also make it work for the item download endpoint, at least for single-file items.

I'm torn on specifying the parameter as you say versus just allowing a `contentDisposition` parameter whose value overrides the default.

**Comment by cpatrick** [comment]
Yay! I lean toward the parameter as the RFC technically allows for extensions beyond `inline` and `attachment`.

**Comment by mgrauer** [comment]
I like the `contentDisposition` parameter path too, if we added the "inline" one only, we'd have to maintain support for that if we add the general parameter for `disposition-type` later.  

I'm going to punt on the `disposition-parm` part of the grammar, since we can get by without it for now.

**Comment by brianhelba** [comment]
Supporting this via an additional parameter in the model / assetstore layers would be a very welcome improvement. I've also [encountered this problem]((https://github.com/ImageMarkup/isic-archive/blob/3e9e2f276bc8137fc05dfab3bed7b5440a3a2975/server/image_utility.py#L71)) my plugins.

However, I think we should ensure that there are no security / policy implications to generally allowing the header to be set as a result of any client HTTP API request (as opposed to letting plugins create a special endpoint for selected ``inline`` downloads). I can't think of any problems off the top of my head, but it's worth considering.

FYI, [here's a list](https://www.iana.org/assignments/cont-disp/cont-disp.xhtml) of the registered extensions to ``disposition-type``.
