### ISSUE TITLE
Auto completion in user search box is broken

### ISSUE THREAD

**Issue by jcfr** [girder/girder#1131]
Typing `r` (or `R`) in the user search box doesn't return anything.

![screenshot from 2015-12-07 12 42 43](https://cloud.githubusercontent.com/assets/219043/11634705/1a6968aa-9ce0-11e5-9d64-ea6e0f31652b.png)

I would expect to see `Ricardo Ortiz`

See https://data.kitware.com/#user/55e861b98d777f6ddc3ff8f6

**Comment by zachmullen** [comment]
We use text search (a la Google) rather than regex or prefix-based search. However, I don't think you're alone in expecting a prefix-based search to work.

I'm changing the label here to feature since this would involve introducing new search technology into our stack.

**Comment by jcfr** [comment]
>  text search (a la Google)

In that case, would it make sense to disable auto completion and expect the user to hit enter ? 

Or may be a better error message. Instead of 

```
No results found
``` 

what about having

```
No results found. Search expects full word.
```

**Comment by zachmullen** [comment]
We've changed the default to be prefix-search in this case and several others throughout the web client.
