### ISSUE TITLE
Allow raw response to be sent without requiring generator

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#1133]
Right now a raw response can only be sent by returning a generator function that yields the output as a stream. In fact, "streaming" and "raw" can be orthogonal, so we should expose a simple function like `girder.api.rest.Resource.setRawResponse(self, val=True)` that a route handler could call to specify that its response should not be transformed.

ping @mgrauer this would solve the problem you described in your email just now, and would be simple to implement.

**Comment by jcfr** [comment]
:+1: 

For reference: 
* [rest.py / endpointDecorator() ](https://github.com/girder/girder/blob/563ada4b90455c53e34596f36c215b982ee7426a/girder/api/rest.py#L384-L434)
* [rest.py / _createResponse()](https://github.com/girder/girder/blob/563ada4b90455c53e34596f36c215b982ee7426a/girder/api/rest.py#L308-L330)]

That will then allow to create decorator allowing to easily customize the response. 

Particularly useful in the context of the dicomweb girder pluging.

Cc: @vovythevov

**Comment by zachmullen** [comment]
@jcfr I'm implementing this right now, do you want me to just add the decorator as well?

**Comment by jcfr** [comment]
> to just add the decorator as well?

+1
