### ISSUE TITLE
Use eslint rather than jshint/jscs

### ISSUE THREAD

**Issue by jbeezley** [girder/girder#1150]
I'm adding this issue for discussion/debate.  I have been doing some modernization of my javascript toolset and found that eslint is vastly superior jshint and jscs in a number of ways.
* [Babel](http://eslint.org/docs/2.0.0/user-guide/configuring.html#specifying-parser) can be used as a parser to support new language features
* [Extensible](http://eslint.org/docs/2.0.0/user-guide/configuring.html#extending-configuration-files) configuration files built-in so we no longer need to merge json files ourselves.
* [Integration](http://eslint.org/docs/1.10.3/user-guide/integrations.html#build-systems) with about every js build system I heard of
* [Plugins](https://www.npmjs.com/package/eslint-plugin-filenames) to enforce file name and path conventions
* About a bazillion other [plugins](https://www.npmjs.com/browse/keyword/eslintplugin)
* All the cool kids are using it<sup>[citation needed]</sup>

I have also found a fairly new "[standard](http://standardjs.com/)" javascript style guidelines that seems to be taking off.  It is trying to be something like what pep8 is for python.  The npm package installs a runnable script, but it is really just an ESLint configuration.  Some of style choices are a bit controversial, in particular the "no semicolons" rule.  (There is a variant called "[semistandard](https://github.com/Flet/semistandard)" that uses semicolons.)  One of the nice things about it is that there is a tool ([standard-format](https://github.com/maxogden/standard-format) or [semistandard-format](https://github.com/ricardofbarros/semistandard-format)) that will do most of the formatting for you, so it is a fairly painless process to do the conversion.

The "standard" conversion would be a pretty big change from the current code style, so I'm not really recommending using it at this point.  ESLint on the other hand can be configured to support the current code style.

**Comment by manthey** [comment]
Without checking, is there a summary of what rules each of the tools support (eslint, jshint, jscs)?  It would be a shame to lose testing functionality.  The 'semistandard' variant looks acceptable to me.  I think switching to the no-semicolons version is just weird, even if it is allowed and sufficient (plus I'll have to unlearn years of habit).

**Comment by zachmullen** [comment]
I am fine with moving to eslint, but definitely against not using semicolons, both for parser performance as well as removing parsing ambiguities, like [this example](http://stackoverflow.com/a/1169596/2550451).

**Comment by jbeezley** [comment]
@manthey I have no doubt that the features of eslint is a strict superset of jshint and jscs.

@zachmullen I'm conflicted about the semicolon issue.   Reading the [arguments](http://blog.izs.me/post/2353458699/an-open-letter-to-javascript-leaders-regarding), it is clear there is a lot of FUD going around.  For one, the example you link would be caught by "standard" as a style error.  The correct syntax is
```javascript
var fn = function () {
}

;(function () {})()
```
The argument is tokens at the start of the line are more noticeable than at the end.  I'm definitely not arguing for eliminating the semicolon in girder; but as stated in the link I posted, it is our obligation as competent developers to refrain from spreading FUD.

**Comment by zachmullen** [comment]
You initially called it the "no semicolons" rule, which is why I felt compelled to respond... in truth it seems to actually be the "no semicolons unless they matter rule". I still personally think that's more trouble that it's worth, but at least we agree that we can't throw them out altogether :wink:

**Comment by zachmullen** [comment]
As far as style goes, my philosophical stance on the subject is that our minifier should hopefully allow us to write whatever style looks the most pleasant to us, and optimize it without us having to worry. I don't have strong opinions about what exactly is the most pleasant to write (and more importantly, to read), so long as we are consistent.

**Comment by jbeezley** [comment]
Fair enough, the NSUTM rule. :smile:

I don't have a strong opinion about style issue either, that is one thing that I like about the standard approach.  It's not configurable to stop all of the bikeshedding about it.

**Comment by zachmullen** [comment]
Also, these two statements seem contradictory to me:

> There is no performance impact anywhere.

and

> 4\. The next line starts with [, (, +, *, /, -, ,, ., or some other binary operator that can only be found between two tokens in a single expression.

Rule 4 necessarily requires an extra parser lookahead for all lines that do not end in semicolons. It seems such a lookahead is not required in cases where the line ends with a semicolon. This was the performance concern I brought up initially. Am I missing something?

**Comment by zachmullen** [comment]
(This is moot in our case since we minify, I'm just curious about this for my own edification.)

**Comment by jbeezley** [comment]
I don't think that necessarily implies a "significant" performance impact.  If parsing javascript is a significant performance problem that semicolons solve, then you are probably doing something wrong.

I see UglifyJS as analogous to compiling a python script into bytecode.  In javascript, it just isn't part of the core library and so doesn't happen automagically.

**Comment by cpatrick** [comment]
*The Javascript community is really frustrating.*

I'm all about using eslint as I believe it is much better (for all of the reasons @jbeezley mentioned).

On the subject of standardjs, I have a personal bias toward semicolons. This bias has nothing to do with my knowledge of how the language works. Years of reading C++ code make them blend into page when reading Javascript. That said, if we really think that this is actually going to (or is) widely adopted, I'd be all for moving to it. If this is some fad, I'm going to continue to be frustrated by the Javscript community.

What I really want is a solution to style so we automate the checking (and hopefully fixing of it) and never have to talk about it again :smile_cat:.

**Comment by jeffbaumes** [comment]
An upgrade to eslint seems appropriate. Semicolons are comforting to me personally so I'd rather have them.

**Comment by danlamanna** [comment]
Additionally, these might be good to look into:
- [eslint-plugin-backbone](https://github.com/ilyavolodin/eslint-plugin-backbone)
- [eslint-plugin-jasmine](https://github.com/tlvince/eslint-plugin-jasmine)

The Backbone plugin especially has a few things that would be really nice to enforce.

**Comment by zachmullen** [comment]
@danlamanna I really like that, we should add it. Particularly that event-scope rule is very important.

**Comment by cpatrick** [comment]
:+1:

-Patrick
