### ISSUE TITLE
New folders in a user don't copy access policies from parent

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#1157]
Is there a particular reason why [new folders don't copy parent access policies if that parent is a user](https://github.com/girder/girder/blob/master/girder/models/folder.py#L492)?

If not, I proposing changing this, both to be consistent, and to facilitate plugins / use cases where users are managed (at least in part) by other administrator users.

**Comment by brianhelba** [comment]
Ping @girder/developers . Does this sound reasonable?

**Comment by mgrauer** [comment]
@brianhelba 

It makes sense that a parent doesn't copy access policies to a new folder if the parent is a user since the access policies essentially have different document properties.  A user isn't access controlled in the way that a folder or collection is.  A user can be in groups, but it can't have group access the way a folder/collection can, tied in with an access level.  A user also doesn't have access control from other users.

e.g., the following makes sense on a folder, but couldn't exist on a user.

```
{
  "groups": [
    {
      "description": "",
      "id": "5644b9cb0640fd2d5fc7a696",
      "level": 0,
      "name": "athena"
    }
  ],
  "users": [
    {
      "id": "5644a5970640fd0617c58ef4",
      "level": 0,
      "login": "admin",
      "name": "joe schnook"
    }
  ]
}
```

**Comment by brianhelba** [comment]
@mgrauer While I agree that the semantics are a little unclear about what access to a user means, as far as I know, there is technically no reason why what you describe shouldn't actually be possible.

Both a ``User`` and a ``Collection`` are subclasses of ``AccessControlledModel``, and can have arbitrary other users and groups granted access to them. The notion of a user being "in" a group is actually a separate mechanism (the ``user['groups']`` property), but there is no technical reason that a group couldn't be granted write access to a user.

Right now, we just grant users admin access to themselves, and don't expose any RESTful API for modifying the permissions on a user, so that never changes. The code in ``createFolder`` wouldn't work any differently in the typical case if we added inheritance of the user's accesses to new top-level user folders (since the new user folder would inherit admin access to the user, and get manually set with admin access to the user too). The one change will be if a site administrator creates a folder in a user's page: right now, the user does not get access to it by default, but with inheritance, the user would get access to it by default (which I see as a positive thing).

The real case for making this change comes when plugins / customized deployments want to do additional things to ACLs on users. For instance, a plugin may make all users private by default, then grant view access to those users to a select group of people (who you need to see all the users, but not be site admins). Admittedly, this specific case doesn't actually make a need for these permissions to propagate to folders, but it shows the need for proper ACLs on users.

Even if we decide as a matter of policy not to propagate the accesses to folders as a special rule, we absolutely must internally support the notion of having arbitrary other user / group accesses on users, even if there's no API for it.

**Comment by jcfr** [comment]
@brianhelba Thanks for the detailed report.

>  if we decide as a matter of policy not to propagate the accesses to folders as a special rule, we absolutely must internally support the notion of having arbitrary other user / group accesses on users, even if there's no API for it.
:+1:

**Comment by zachmullen** [comment]
We do already support that, by virtue of them being AccessControlledModels. We just haven't had any reason yet to expose that via REST or via the GUI since it's kind of an odd use case.

**Comment by mgrauer** [comment]
@brianhelba 

>While I agree that the semantics are a little unclear about what access to a user means, as far as I know, there is technically no reason why what you describe shouldn't actually be possible.

I was trying to say this, and this is more correct than what I said, thanks for providing the additional details.

**Comment by brianhelba** [comment]
@zachmullen Yes, everything works fine now (with the exception of users not having default access to folders that site admins create in their home directory). I'm just pushing back against any potential notion that first-class ACLs on users is something that Girder wouldn't support.

My proposed change is primarily motivated at making things less magical for plugins that do want to mess with permissions in a more advanced way.

**Comment by brianhelba** [comment]
In the course of explaining the logic to someone who already knew how it worked, I've actually talked myself into making this fix (I opened the issue because I was undecided). The issue of admin users creating folders in user directories is a real one, and the most elegant way is to just unify the behavior of all folder creation.

**Comment by zachmullen** [comment]
Not sure what the status of this one is, but I'll assume it's been fixed since a fixed was promised over year ago :)
