### ISSUE TITLE
Create a libs.min.css

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#1160]
There are a number of CSS files that could be concatenated during build into a single ``libs.min.css`` file.

As part of this, the un-minified ``/lib/fontello/css/fontello.css`` and ``/lib/fontello/css/animation.css`` should be switched to use a minified version from upstream, or put through Girder's CSS minifier.

**Comment by zachmullen** [comment]
This was actually the point of `ext.min.css` which now exists on master.

**Comment by brianhelba** [comment]
@zachmullen  How do you feel about renaming ``ext.min.css`` to ``libs.min.css`` for consistency with ``libs.min.js``? Is there a reason you wanted the name ``ext.min.css` instead?

**Comment by zachmullen** [comment]
If I had to do it over again, `libs.min.js` would be called `ext.min.js`. However, consistency might be better than having a good name at this point, so we can do whichever you prefer.

**Comment by brianhelba** [comment]
We could change ``libs.min.js`` to ``ext.min.js``, then make Grunt create a copy of it as ``libs.min.js`` in the static built directory, so users can fetch either one.

I personally don't care what it's called, but I'm curious, why do you feel ``ext`` is more expressive than ``libs``. Isn't the point of the file to contain 3rd party libraries?

**Comment by zachmullen** [comment]
The confusion is that, in a way, a lot of Girder js code could itself be considered a library as opposed to an application. Using "ext" makes it clear that the code in question is third party, and is also the convention used on the vtkweb side of things last I checked.
