### ISSUE TITLE
Make experiemental switch only visible for enabled plugins

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#1165]
I think https://github.com/girder/girder/pull/1115 went a little overboard, as the clutter from the warning icon on the switches of disabled experimental plugins makes it significantly harder to just tune out all disabled plugins and tell which plugins are enabled at a glance.

Can we remove the icon from the switch of disabled experimental plugins (keeping it for enabled experimental plugins). Users will still have ample warning when they enable experimental plugins, as there's still a badge next to the plugin, and the icon will appear as soon as they toggle the switch.

**Comment by brianhelba** [comment]
Ping @zachmullen .

**Comment by zachmullen** [comment]
Fair point, I'd be fine with removing the icon.

**Comment by brianhelba** [comment]
This has been fixed.
