### ISSUE TITLE
Move D3 to be provided by a plugin

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#1166]
Nothing in Girder core requires D3, so its inclusion in the default JS / CSS files is a source of bloat.

Since many plugins may depend on D3, we should move D3 to be provided by its own plugin, which other plugins can depend upon.

**Comment by aashish24** [comment]
+1

**Comment by jeffbaumes** [comment]
I talked some with @jbeezley and @brianhelba about this. Some observations:

* Nothing in girder core or girder core plugins uses D3 directly.
* Only the Vega plugin uses it indirectly through using Vega.
* Webpack and Grunt allow plugin builds to include D3 as a dependency fairly easily.
* Girder should probably not have a set of libraries available just in case some plugins use it, unless there are many plugins that need the same version of a library. This is not currently the case with D3.
* Girder already enables plugins to add npm modules to the root `node_modules` through the `girder.dependencies` section of `plugin.json`.

Given these points, I propose removing D3 from Girder's `package.json` for 2.0. Given the last point, I propose moving the Vega dependency to the Vega plugin for a clear separation of the dependency for 2.0. These changes are included in #1525.
