### ISSUE TITLE
Switch to Passlib to abstract away password hashing

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#1167]
We're going to need more support for additional password hashing schemes in the future, and [Passlib](https://pythonhosted.org/passlib/) is a well-established way to abstract away the details of integrating each hashing library directly.

Additionally, Passlib [has a utility](https://pythonhosted.org/passlib/lib/passlib.hash.bcrypt_sha256.html) for dealing with the 72-character length limitation in bcrypt, which Girder currently does not address.

**Comment by brianhelba** [comment]
If this is implemented, it should be noted in https://github.com/girder/girder/blob/master/docs/security.rst , as part of https://github.com/girder/girder/issues/356 .

**Comment by danlamanna** [comment]
To summarize an in person discussion, it appears that `passlib` also supports the TOTP specification: https://passlib.readthedocs.io/en/stable/lib/passlib.totp.html.
