### ISSUE TITLE
Considering removing CherryPy version from response headers

### ISSUE THREAD

**Issue by danlamanna** [girder/girder#1170]
@ronichoudhury brought this up on Kitware/tangelo#533, and Girder also returns CherryPy/version in its response headers.

**Comment by zachmullen** [comment]
There's probably a simple way to disable this in cherrypy, it's just a matter of tracking that down in the docs. We can certainly turn it off, from what I can tell there is no reason we should be sending the Server header at all.

**Comment by cjh1** [comment]
response.headers.server = "" will do it

**Comment by zachmullen** [comment]
Looking at our deployments, nginx actually rewrites the Server header to specify itself, so this is probably more of a deployment issue than anything.

**Comment by brianhelba** [comment]
This is a nice "onramp" (or whatever we end up calling it) issue. Adding the label.

**Comment by zachmullen** [comment]
It's onramp on the cherrypy side, but in real life we will be deferring the SSL handling to a proxy server that will need to be configured independently, which might not be as clear-cut for newbies.
