### ISSUE TITLE
Use of TestCase.assertRegexpMatches causes warnings in Python3

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#1185]
The Girder `TestCase` class inherits the methods `assertRegexpMatches` and `assertRegexpMatches` from Python's `unittest.TestCase` library.

[In Python2](https://docs.python.org/2/library/unittest.html#unittest.TestCase.assertRegexpMatches), these are the only option to natively assert that a regex matches.

[In Python3](https://docs.python.org/3.2/library/unittest.html#unittest.TestCase.assertRegex), these are deprecated in favor of the renamed `assertRegex` and `assertNotRegex`, which have identical parameters. Using `assertRegexpMatches` / `assertRegexpMatches` in Python3 raises warning messages.

It might be helpful to add `assertRegex` and `assertNotRegex` directly to Girder's `TestCase` class (overriding the base class methods), then convert all code to use the new methods. These methods would dispatch to the appropriate base class method. Six already provides an [`assertRegex` compatibility method](https://pythonhosted.org/six/#six.assertRegex) (but not one for `assertNotRegex`).

**Comment by zachmullen** [comment]
:+1:

**Comment by danlamanna** [comment]
This has been fixed for a while by using `six.assertRegex`.
