### ISSUE TITLE
Make packaging tests run faster

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#1199]
These are taking up a lot of our CI time. Some options:

* Make some of them mock out the npm calls so they don't all have to run through an entire install/build process
* Consider combining some of the plugin tests, such as packaging_plugin_install, packaging_extras_install, packaging_plugin_copy_extras so that they only need to actually do the npm install once for all three sets of assertions.

**Comment by jbeezley** [comment]
I noticed this as well.  I might take a crack at mocking the npm calls.  Like I mentioned in #1189, there is a limit to what these packaging tests are even capable of detecting.  I think I might start running my nightly tests against an install from the generated packages.

**Comment by zachmullen** [comment]
Mocking the npm calls should be simple, at least as I imagined, our wrapper test script would prepend something to that PATH that contained an executable shell script that just exits with 0.

**Comment by jbeezley** [comment]
That's what I was thinking as well.

**Comment by zachmullen** [comment]
It could also validate args or write something to disk that we could check and make sure it was actually called.
