### ISSUE TITLE
eslintrc config is difficult for symlinked plugins

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#1215]
Plugins that are symlinked into the plugins dir cannot make use of the "extends" option in eslintrc with relative paths. I read a bit about the configs, but couldn't immediately see an easy way to make this work, since the "-c" command line options overrides the eslintrc settings. @jbeezley any ideas?

**Comment by jbeezley** [comment]
@danlamanna just discussed this with me.  The only way I can see to handle it is to use a [javascript configuration file](http://eslint.org/docs/user-guide/configuring.html#configuration-file-formats) (`.eslintrc.js`).  This way you can use an absolute path as follows:

```
module.exports = {
  extends: __dirname + '/.eslintrc'
};
```

**Comment by zachmullen** [comment]
You mean inside the plugin? How would it reliably know the location of the core eslintrc?

**Comment by jbeezley** [comment]
Yes, inside the plugin.  The idea is that eslint will always be run from [girder's main directory](https://github.com/girder/girder/blob/master/tests/JavascriptTests.cmake#L52), so the node `__dirname` variable will always point there.

**Comment by zachmullen** [comment]
ah, I got it, thanks!

**Comment by zachmullen** [comment]
(For the record, it's `process.cwd()`, `__dirname` refers to the parent directory of the source file being executed.)

**Comment by jbeezley** [comment]
Right, thanks for the correction.
