### ISSUE TITLE
missing enabled plugins break plugin page

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#1247]
@cdeepakroy just ran into this. He had an external plugin that he had enabled, but then removed its directory. It then made the plugin management UI throw errors anytime a plugin was turned on.

**Comment by zachmullen** [comment]
Our workaround was to make a dummy directory with the name of the missing plugin, turn that fake plugin off via the UI, then everything was OK and we removed the dir.

**Comment by danlamanna** [comment]
Does it make sense to disable the plugin (via the mongo setting) if it's removed from the filesystem? We had a collaborator who experienced wonky issues when removing it from the filesystem because it was still technically enabled.

**Comment by zachmullen** [comment]
I'm fine with either disabling it in the setting or just gracefully ignoring it and keeping it in the setting.
