### ISSUE TITLE
cherrypy autoreloading using weird caching...?

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#1250]
I noticed this on both @cdeepakroy and my own dev install in the last two days. I have reproduced this on both cherrypy 3.7 and 4.0. When restarting the server manually, everything is fine, but when autoreloading, my instance is reverting to some weird state from weeks ago and I have no idea how or why. The plugin page shows plugins that no longer even exist in my directory (this list is cached under the cherrypy webroot, so I suspect it got serialized somewhere and is being used on autoreload), and it's also serving up static files from a few weeks ago.

Has anybody besides the two of us seen this? Cherrypy 5.0 exists now, so we can try moving to that, but if that doesn't work we may need to disable autoreload...

**Comment by jbeezley** [comment]
I've seen this as well when developing minerva.  I.e., I touch a python script watched by cherrypy, then it reloads into some half broken girder UI.  I have to restart the server every time.

**Comment by zachmullen** [comment]
I'm currently reading through cherrypy source code to try and figure out how this is possible.

**Comment by zachmullen** [comment]
I've discovered the source of the problem. I was calling girder from within my git checkout dir as follows:

`python -m girder`

The cherrypy autoreloader calls `os.execv` using the same `sys.executable` and `sys.args`, attempting to run in the same working dir that the process was initially called with. I also have a pip-installed girder in my global system python path, which is the one that was getting restarted. I'm going to do a little more digging around to see if the working dir is getting changed somewhere on autoreload.

ping @brianhelba
