### ISSUE TITLE
Add automated test for documentation generation

### ISSUE THREAD

**Issue by msmolens** [girder/girder#1284]
As of 72ff31244bf9b34d376aa662e1cea2e742338fe4, running `grunt docs` shows the following error:

    /path/to/girder/docs/developer-cookbook.rst:408: ERROR: Unknown target name: "https://midas3.kitware.com".

as well as a few warnings.

Add an automated test to detect at least the errors.

From https://github.com/girder/girder/pull/1281#discussion_r57926113

**Comment by zachmullen** [comment]
We need to change those two references from

    `https://midas3.kitware.com`_

to 

    `<https://midas3.kitware.com>`_
