### ISSUE TITLE
Display abbreviated folder descriptions in hierarchy widget

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#1297]
The description for folders currently only appears inside the folder info modal.

While descriptions can be multi-line markdown, it will be helpful to at least show the first line of each folder's description directly on the hierarchy widget. This requires two different additions.

First, for every sub-folder and sub-item in a hierarchy list, the first line of the description can be rendered in the currently-empty white space to the right of the sub-folder / sub-item link. Long lines can be truncated using [the `text-overflow: ellipsis;` CSS property](http://www.w3schools.com/cssref/css3_pr_text-overflow.asp). The text itself should be de-emphasized, with a light font color or opacity, so as not to be too overwhelming.
![bug1](https://cloud.githubusercontent.com/assets/1282879/14375488/a79fd510-fd2f-11e5-9519-9186b25258d6.png)

Second, the description of the currently-selected folder can be added to the top of the hierarchy widget. This would have the same overflow behavior as before, but can also contain a special feature: the `...` ellipsis can be a clickable link, which launches the current folder info modal (where the full description is rendered). This will help to attract people to find the full description in the info modal, which may not be an intuitive place to look. Note, even if the full first line of the description fits into the available space at the top of the widget, the `...` link should also appear if there are additional lines in the description.
![bug2](https://cloud.githubusercontent.com/assets/1282879/14375681/0ad6d8c6-fd31-11e5-91a9-a1f28468d9eb.png)

**Comment by jbeezley** [comment]
Another idea I had was to use a tooltip to display extra metadata.
