### ISSUE TITLE
Plugins loaded via entry points fail if they depend on other plugins

### ISSUE THREAD

**Issue by manthey** [girder/girder#1319]
When we load a plugin via an entry point, the plugin is imported as part of `findAllPlugins`.  Unfortunately, if the plugin itself tries to import another girder plugin, this will fail (as we haven't loaded the required plugins yet).  A plugin can be rewritten to defer these imports, but it would be better to fix this so that plugin dependencies are honored.

**Comment by zachmullen** [comment]
Normally we handle this via toposorting an explicit dependency list; do we not have that ability for entrypoint plugins?

**Comment by manthey** [comment]
In the toposort function, we call `findAllPlugins` which is doing the import (in an effort to get the config information needed for the toposort).

**Comment by manthey** [comment]
There are other issues with using a plugin via an entry point.  Sub-imports within the plugin behave very differently when imported via an entry point and via a directory.

For instance, models aren't imported, even if they exist in the models module of the plugin.  They throw an ImportError, since girder.plugins.(plugin).models is NOT in the sys.modules path.

I think we *should* set the plugin's `PLUGIN_ROOT_DIR`.

We need to add the plugin to the `girder.plugins` module via `girder.plugins.__dict__[name] = module`, so that other plugins need not care if the plugin came via an entry point or a directory. 

We need the `sys.modules` dictionary to be away that the plugin is reachable this way as well (via `sys.modules[moduleName] = module`).  I don't think this has any repercussions, but I don't really like fiddling sys.modules directly.

**Comment by danlamanna** [comment]
@jbeezley these issues should be fixed from pip-ip right?

**Comment by jbeezley** [comment]
Yes, no longer relevant.
