### ISSUE TITLE
Add dedicated metadata field for license

### ISSUE THREAD

**Issue by msmolens** [girder/girder#1320]
It could be nice to support a dedicated metadata field for an item's license. The field could be set at the time of upload/creation, potentially selected from a list of standard open source licenses.

**Comment by brianhelba** [comment]
Ping @girder/developers . I'd like to try to get this implemented soon, but feedback is most welcome now, before we start.

**Comment by zachmullen** [comment]
My main request is that the list of licenses should be editable per-instance by site admins.
