### ISSUE TITLE
docker-compose not working

### ISSUE THREAD

**Issue by satra** [girder/girder#1329]
i'm trying to use docker-compose to get an instance of girder running on rackspace. step 19 errors out.

```
Step 19 : RUN npm install --unsafe-perm && npm cache clear
 ---> Running in b19d6a12a4e2
npm WARN deprecated jade@1.3.1: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated jade@1.2.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated npmconf@2.1.1: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v6.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v6.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

> phantomjs@1.9.18 install /girder/node_modules/phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Receiving...

Killed
Service 'girder' failed to build: The command [/bin/sh -c npm install --unsafe-perm && npm cache clear] returned a non-zero code: 137
```

**Comment by zachmullen** [comment]
@Xarthisius have you run into this error before when you were using the docker compose script?

**Comment by zachmullen** [comment]
I just ran `docker-compose up` successfully on my linux machine. That exit status `137` along with the lack of any real error message would point to the build process being killed with signal 9 (SIGKILL). This typically happens when the operating system runs out of memory. What is the size of physical memory and swap on the target machine?

There is actually a bug here that is somewhat related; our dockerfile should be running the npm install with `--production`, which would skip the installation of phantomjs altogether. I'll fix that.

**Comment by Xarthisius** [comment]
Yes I did. Phantomjs is downloaded a lot and bitbucket often throws 408 (timeout), which npm can't handle properly. Unfortunately there's nothing to fix on the girder side. Just try to rebuild the image. It usually succeeds during 2nd attempt (or 3rd ;-) )

**Comment by cjh1** [comment]
I have seen the same issue ( with Phatomjs ) doing a deployment using Vagrant.

**Comment by satra** [comment]
@Xarthisius, @zachmullen  - i have it running now - took a set of random tries - but now i can connect to the girder instance.

**Comment by zachmullen** [comment]
PR #1329 will make this problem go away. @girder/developers could someone QA that?
