### ISSUE TITLE
Rename Jade -> Pug

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#1341]
Per https://github.com/pugjs/pug/issues/2184 , the Jade template engine is being reamed to Pug, to deal with trademark issues around the original name.

The transition is still in-progress (their new website and documentation isn't online yet), but once their migration is more mature, we should update all references to "Jade" in Girder's code too.

**Comment by manthey** [comment]
As long as the npm pug release is in alpha, I don't think we should use it.  pug's current version is `2.0.0-alpha7`.

**Comment by brianhelba** [comment]
Of course, but the rename is definitely going to happen, so I just wanted to make others aware and create a reminder for some time the future.

We can revisit this in a few months, when everything is stable.

**Comment by sebastienbarre** [comment]
Thanks. As far as the client side is concerned, note that most Jade uses are gone when converting to Webpack (direct uses that is, it uses a webpack loader instead). I would suggest not doing this on master, as it would conflict heavily with integration-2.0

**Comment by mgrauer** [comment]
Fixed by #1598.
