### ISSUE TITLE
Make attaching route handlers optional

### ISSUE THREAD

**Issue by jbeezley** [girder/girder#1351]
Currently girder will always attach route handlers when the source is loaded via `girder.router.route`.  This attaches a handler to Backbone's global history object.  The `girder.router.enabled` method turns these handlers into no-ops, but they are still present.  The problem with this is that Backbone will only call one route handler on `navigate`.   When you attach new routes, they are prepended to the handlers array, so the last route added that matches will be the one that is called and all others will be ignored.

The problem I'm having is that parts of the application I'm developing adds routes before girder is loaded, specifically the root path `/`.  Due to how I'm loading my modules, that's difficult to avoid.

Ideally, I think the routes should be attached in `girder.main.min.js` rather than in the library bundle, but that is difficult to do because plugins need to be able to add routes as well.  An easier option would be something like this:
```javascript
girder.router.route = function () {
  if (!girder.noRoute) {
    return Backbone.Router.prototype.route.apply(this, arguments);
  }
};
```

Then I can set `window.girder = { noRoute: true };` before loading girder.

Does that sound reasonable?

**Comment by zachmullen** [comment]
I think this will go away via the webpack changes.
