### ISSUE TITLE
a few questions about deployment using docker

### ISSUE THREAD

**Issue by satra** [girder/girder#1358]
i've installed girder using docker-compose on a public facing machine. i was wondering if there are wiki pages that describe in the docker context, how to:

- run over https
- test email
- configure db storage such that the service can be brought down and up again easily without losing data. i.e. the storage of mongodb should be outside of the docker container on a host drive
- secure attack surfaces

we intend this to be a production environment for collecting data from mobile apps.

**Comment by zachmullen** [comment]
ping @Xarthisius , he originally authored our docker-compose script and he may have addressed some of these same issues in his own work.

**Comment by Xarthisius** [comment]
Hi Satra,
I run girder behind nginx + letsencrypt, which lives in separate container. There are many ways to implement that, here's one [example](http://manas.com.ar/blog/2016/01/25/letsencrypt-certificate-auto-renewal-in-docker-powered-nginx-reverse-proxy.html). Girder-wise I just followed [proxy docs](http://girder.readthedocs.io/en/latest/deploy.html#nginx) and modified local config accordingly. As for the db storage it's already covered by using docker volumes, you can modify original `docker-compose.xml` and put db wherever you want on the host filesystem.
I don't use emails with Girder so I'm afraid I can't help you with that.

**Comment by zachmullen** [comment]
If you intend to actually send emails from your girder instance, I would recommend using a hosted email service such as mailgun, which gives you a pretty sizeable monthly quota for free and is fairly easy to setup. In the admin configuration page of girder you can point it to whatever SMTP server you want.

**Comment by satra** [comment]
@zachmullen and @Xarthisius - thank you both (i'll take a look at the examples)

@zachmullen - 
given your girder tutorial using vagrant, if there is a vagrant solution to this i would be happy to use it as well. it seems having a couple of routes may be good for different use cases. i may end up running docker-compose inside a VM and follow @Xarthisius steps. if i do, i'll send a PR with the Vagrantfile.

@zachmullen - it's not so much setting up the email server and pointing to it, it's how to test it within the girder framework (e.g., send test email to admin)

**Comment by zachmullen** [comment]
Sure, if you have a custom plugin you can follow this guide on how to send emails to admins: http://girder.readthedocs.io/en/latest/developer-cookbook.html#sending-emails

If you are just using out-of-the-box girder, the easiest way to test that your email is working would be to try to do a password reset. I don't have a vagrant or docker solution that actually contains a configured SMTP server since we don't necessarily want to prescribe one, but if you want to set one up inside your environment for testing, postfix is a good one to use.

**Comment by satra** [comment]
@zachmullen - thanks. this is running inside mit, so we have a bunch of smtp servers we can point to :)

**Comment by satra** [comment]
thank you for all the feedback. i was able to get things running with the following setup (and send email).

https://gist.github.com/satra/ca6d9aad045a1d242302244421a67341

i was also able to run it with docker-compose without vagrant.

the reason i liked vagrant was because i could create a public ip quite easily using a bridged interface.

however, the one thing that doesn't work inside the vagrantfile is having the mongodb instance save data to a shared folder. this is a known limitation (https://docs.mongodb.com/manual/administration/production-notes/#fsync-on-directories)

i'm going to be running a set of services on the machine. therefore having multiple IPs bridged through the interface would be useful. if anyone has a suggestion of how to assign/route a public IP easily to the nginx container that would be very helpful. in the meantime this issue has been addressed.
