### ISSUE TITLE
CherryPy 5.4 breaks tests

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#1362]
A [change was made for CherryPy 5.4](https://github.com/cherrypy/cherrypy/pull/1432) that causes `cherrypy.serving.response.headers['Location']` to be returned as `str` in Python2 (the same as before) and `bytes` in Python3 (different).

In addition to failing tests, this change may cause unexpected results in how some URL manipulation in the `hdfs_assetstore`, `oauth`, etc. is done. As the tests are fixed to work with CherryPy 5.4 on Python 3, a more thorough examination should be made.

In the meantime, [CherryPy 5.4 was blacklisted from `setup.py`](https://github.com/girder/girder/commit/ae940338e6d931dc67d76e310b2f2f11f9474095), so new installations will not use it. Once this bug is resolved, the blacklisting should be removed.

**Comment by poofeg** [comment]
I think it would be better solution to URL encode (percent-encoding) the redirect URL. It is suitable for all Python versions.

**Comment by brianhelba** [comment]
[This bug](https://github.com/cherrypy/cherrypy/issues/1440) has been [fixed](https://github.com/cherrypy/cherrypy/commit/0d48639e7285e033766221d4e254de32fd02d773) by our upstream friend @jaraco in CherryPy 6.0.0+. Thanks!

**Comment by zachmullen** [comment]
Woo, thanks @jaraco!

**Comment by jaraco** [comment]
Glad to help. All I did was back out the offending commit until such a time that a better implementation can be devised, but I'm hopeful this report will help capture the expectation. Cheers.
