### ISSUE TITLE
cannot download an uploaded file

### ISSUE THREAD

**Issue by satra** [girder/girder#1365]
i'm able to upload a file, see it via terminal in the assetstore, navigate to the file from the Web UI, but when i try to download the file, it says:

{
    "message": "Read access denied for folder 574eda090d461f0001351c41 (user None).",
    "type": "access"
}

**Comment by zachmullen** [comment]
Hi @satra , how is it that you are attempting to download the file? It looks like whatever mechanism you are using is failing to authenticate.

**Comment by satra** [comment]
@zachmullen - i'm simply trying to hit the download link on the Web UI, logged in as myself.

**Comment by zachmullen** [comment]
Do you have cookies enabled? To download private data via the web UI, it does require the use of a cookie due to browser limitations.

**Comment by satra** [comment]
cookies were enabled. switched browsers and it worked. will test a few more parameters later this afternoon. closing for now.
