### ISSUE TITLE
Add the ability to upload a file in the homepage plugin

### ISSUE THREAD

**Issue by mgrauer** [girder/girder#1374]
The folder markdown widget supports this, but provides that folder as a target for the upload.

An upload target would need to be specified or provided by the plugin (perhaps a new private collection named "homepage", a new folder under that user's space, etc).

follow up to #1370.

**Comment by brianhelba** [comment]
I think the private collection is the most maintainable; the most appealing thing about this plugin is that it lets me have less-technical users customize an instance that I manage. If the content is in their home directory(or across several users' homes), it's harder for me to find, and easier for them to accidentally delete. Name it something like "Homepage Assets".

**Comment by brianhelba** [comment]
@girder/developers Does anyone have time to work on this? I have several deployed sites that will benefit from it.

**Comment by fogleman** [comment]
@brianhelba I'll take a look.

**Comment by brianhelba** [comment]
@fogleman Thanks so much for the quick turnaround!
