### ISSUE TITLE
Ability to use data on data.kitware.com for writing python tests

### ISSUE THREAD

**Issue by cdeepakroy** [girder/girder#1416]
As described [here](http://girder.readthedocs.io/en/latest/developer-cookbook.html#use-external-data), there is currently a mechanism to write python tests using data on [MIDAS](https://midas3.kitware.com).

This issue concerns the development of a similar mechanism to use data stored on data.kitware.com (or more generally on a public folder on any girder instance) to write python tests for girder plugins.

Specifically, i see the following three things that need to be developed:
* Similar to the `Download key file` feature on MIDAS, we need an ability to interactively download sha512 key files for each individual file, item, or folder stored on a girder instance.
* In `add_python_test(my_test EXTERNAL_DATA test_file.txt)` make the EXTERNAL_DATA option allow automatic download of data from data.kitware.com (or any girder instance) based on the sha512 key files.

**Comment by cdeepakroy** [comment]
CC: @brianhelba @zachmullen

**Comment by jbeezley** [comment]
There is a plugin to download files by their hash (https://github.com/girder/girder/tree/master/plugins/hashsum_download), which was finished after my original ExternalData PR.  If we enable that plugin on data.kitware.com, it would be pretty easy to make the change in the test code.

**Comment by zachmullen** [comment]
It's enabled there now. I'm working on exposing the hash values to users.

**Comment by zachmullen** [comment]
@cdeepakroy this should now work, and we have projects using data.kitware.com for ExternalData. Can we close this?

**Comment by cpatrick** [comment]
I say yes. 👯
