### ISSUE TITLE
Investigate switching hdfs assetstore to hdfs3

### ISSUE THREAD

**Issue by kotfic** [girder/girder#1425]
[hdfs3](http://hdfs3.readthedocs.io/en/latest/) is a python library based on [libhdfs3](http://pivotal-data-attic.github.io/pivotalrd-libhdfs3/).  It appears that switching to hdfs3 would provide file-like read/write access for HDFS

**Comment by cpatrick** [comment]
+10000

**Comment by zachmullen** [comment]
Two major shortcomings of snakebite: (1) it doesn't support writing data, and (2) it doesn't work in python3. Hdfs3 definitely wins on (1), does it also support both python 2 and 3?

**Comment by cjh1** [comment]
According to pypi yes

**Comment by zachmullen** [comment]
Seems like a big win then, even if it does involve an extra install step.

**Comment by kotfic** [comment]
Unless this is somehow urgent I'd like to target this for the hackfest.

**Comment by cpatrick** [comment]
Nothing urgent involves Hadoop... :trollface:

**Comment by manthey** [comment]
Outdated.
