### ISSUE TITLE
Model "imports" are too verbose

### ISSUE THREAD

**Issue by fogleman** [girder/girder#1431]
I find the standard way of accessing models to be a bit verbose:

```
self.model('folder').foo
ModelImporter.model('collection').bar
```

It'd be nice if we could do something like this:

```
from girder.models import Folder, Collection

folder = Folder.get(folderId)
collection = Collection.createCollection(...)
```

The only question is if there's a reason this can't be done at import time.

Thoughts?

**Comment by zachmullen** [comment]
That would work for everything other than the lazy instantiation of the singletons.

**Comment by zachmullen** [comment]
#2376

**Comment by danlamanna** [comment]
Should our imports be structured so that we can do:
```
from girder.models import Setting, Token

# instead of
from girder.models.setting import Setting
from girder.models.token import Token
```

**Comment by zachmullen** [comment]
I thought about that, and I'm ok with importing the submodules in __init__.py.
