### ISSUE TITLE
Don't unbind external event handlers

### ISSUE THREAD

**Issue by jbeezley** [girder/girder#1447]
@danlamanna pointed out the other day that the Backbone views are [full](https://github.com/girder/girder/blob/e46ff18eb0d0b3c34ca6432c188ba5cdbe477f40/clients/web/src/views/widgets/EditFolderWidget.js#L92) of this kind of a pattern:

``` javascript
model.off().on('g:saved', ...)
```

[Sometimes](https://github.com/girder/girder/blob/e46ff18eb0d0b3c34ca6432c188ba5cdbe477f40/clients/web/src/views/body/ItemView.js#L56) it is scoped a little better:

``` javascript
model.off('g:saved').on('g:saved', ...);
```

This would be better if we insist on using anonymous functions:

``` javascript
model.off('g:saved', null, this).on('g:saved', function () {...}, this);
```

but there still might be conflicts with classes extending the view.

The safest way to prevent attaching the same handler twice is something like this:

``` javascript
function myHandler() {...}
model.off('g:saved', myHandler).on('g:saved', myHandler, this);
```

**Comment by brianhelba** [comment]
The more robust fix is for asynchronous methods to return promises, which callers can safely attach single handlers (`.done`, `.fail`, etc.) to. Event binding should be to handle potentially-recurring events, which may occur at any time. `.off` should be used extremely rarely.

Closing, as this will be resolved by a migration to promises.
