### ISSUE TITLE
Invalid item metadata renders folder inaccessible

### ISSUE THREAD

**Issue by alex-r-bigelow** [girder/girder#1462]
To replicate:

1. Create a folder A
2. Create an item B inside folder A
3. Use `/item/{id}/metadata` to attach `{"value":Infinity}` to the item.

    This will respond with a cherrypy-style, HTML internal server error (not the regular kind):

   `ValueError: Out of range float values are not JSON compliant: inf`

4. From this point, further attempts to access Folder A in the girder interface will also yield this error.

**Comment by zachmullen** [comment]
Thanks for finding this. We need to turn on strict JSON parsing of the metadata.
