### ISSUE TITLE
girder_client should use subparsers for commands

### ISSUE THREAD

**Issue by Xarthisius** [girder/girder#1471]
I'd like to add a new command to `girder_client`. However it takes a different number of arguments than `upload/download/localsync`. Providing command via `-c` switch is a bit cumbersome this way. 

I'd like to propose switching commands to separate subparsers:
```
girder-cli upload ...
girder-cli download ...
```

Since it breaks backward compatibility, I'd like to request comments from @girder/developers before implementing.

**Comment by zachmullen** [comment]
👍  I think this is definitely a good idea.
