### ISSUE TITLE
girder-client: doesn't use requirements.txt

### ISSUE THREAD

**Issue by pmlandwehr** [girder/girder#1473]
Despite the existence of [`requirements.txt`](https://github.com/Kitware/girder/blob/master/clients/python/requirements.txt), [`setup.py`](https://github.com/Kitware/girder/blob/master/clients/python/setup.py) makes references to an internal list of requirements *without* the same version pinnings. The pinnings are quite strict, so I'm ok with that, but it seems to differ from the intended design...

**Comment by zachmullen** [comment]
@jbeezley can elaborate further on this, but this is actually by design. The setup.py list is intended as the loosest possible top-level requirements, whereas the requirements.txt file is the full transitive dependency dump output by a `pip freeze`.

**Comment by jbeezley** [comment]
It is intended to avoid [dependency hell](https://en.wikipedia.org/wiki/Dependency_hell).  See the blog post here for details: <https://caremad.io/2013/07/setup-vs-requirement>
