### ISSUE TITLE
/jobs POST endpoint

### ISSUE THREAD

**Issue by mgrauer** [girder/girder#1502]
The /[jobs](https://github.com/girder/girder/blob/a135b8e219a4efaf0e31657e08e1ac969b01f9dd/plugins/jobs/server/job_rest.py#L28) POST endpoint is conspicuously absent.  Is there a reason for this, or has it simply never been implemented?

**Comment by zachmullen** [comment]
Currently absent by design; jobs are meant to be created internally as a result of other actions being triggered in the system. At least for now, creating and scheduling them is not meant to be left to end users.

If you have a compelling use case for this, though, please outline it here.

**Comment by mgrauer** [comment]
We have a use case for doing this, but it can be satisfied by creating a bespoke server side endpoint in our plugin to create the job, rather than by adding it to Girder core.

This sounds like the favored approach for creating Jobs.
