### ISSUE TITLE
Tests failing in vagrant environment

### ISSUE THREAD

**Issue by chetnieter** [girder/girder#1514]
After following the steps outlined [here](http://girder.readthedocs.io/en/latest/development.html#vagrant) and [here](http://girder.readthedocs.io/en/latest/development.html#server-side-testing) when I run 'make test' in the girder-build directory I get several test failures. After running some individual tests with the verbose flag it appears python is not able to import the test module in question.

This is related to #1520.

`(env) vagrant@girder:~/girder-build$ ctest -R server_upload -V
UpdateCTestConfiguration  from :/home/vagrant/girder-build/DartConfiguration.tcl
Parse Config file:/home/vagrant/girder-build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/vagrant/girder-build/DartConfiguration.tcl
Parse Config file:/home/vagrant/girder-build/DartConfiguration.tcl
Test project /home/vagrant/girder-build
Constructing a list of tests
Done constructing a list of tests
Checking test dependency graph...
Checking test dependency graph end
test 31
    Start 31: server_upload

31: Test command: /usr/local/bin/coverage "run" "--parallel-mode" "--rcfile=/home/vagrant/girder-build/tests/girder.coveragerc" "--source=girder,/home/vagrant/girder/clients/python/girder_client" "-m" "unittest" "-v" "tests.cases.upload_test"
31: Test timeout computed to be: 1500
31: Traceback (most recent call last):
31:   File "/usr/lib/python2.7/unittest/__main__.py", line 12, in <module>
31:     main(module=None)
31:   File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
31:     self.parseArgs(argv)
31:   File "/usr/lib/python2.7/unittest/main.py", line 149, in parseArgs
31:     self.createTests()
31:   File "/usr/lib/python2.7/unittest/main.py", line 158, in createTests
31:     self.module)
31:   File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
31:     suites = [self.loadTestsFromName(name, module) for name in names]
31:   File "/usr/lib/python2.7/unittest/loader.py", line 100, in loadTestsFromName
31:     parent, obj = obj, getattr(obj, part)
31: AttributeError: 'module' object has no attribute 'upload_test'
31: Mocking Girder log methods.
1/1 Test #31: server_upload ....................***Failed    0.73 sec`

**Comment by zachmullen** [comment]
As of right now our vagrant box is not built for development. In order to support that, we'll need to install requirements-dev.txt, the npm dev requirements, and cmake.

**Comment by zachmullen** [comment]
Superseded by #1520
