### ISSUE TITLE
Vagrant VM not setup for development

### ISSUE THREAD

**Issue by chetnieter** [girder/girder#1520]
Despite what is implied in the [Developers Guide](http://girder.readthedocs.io/en/latest/development.html#vagrant) the vagrant VM is not setup as a development environment. The following tools and packages appear to be missing.
1. The helper script mentioned in the dev guide is not present.
2. cmake and ccmake are not installed.
3. Several python packages appear to be missing (flake8, mock, etc ...). This is resolved by running 'sudo pip install -r requirements-dev.txt'
4. It is not clear how to use the virtualenv created by running make. If I activate and try to run the tests if can't find many of the python modules even after installing requirements-dev.txt. Perhaps re-running cmake would have done it.

This is the likely cause of the testing issues reported at #1514.

**Comment by zachmullen** [comment]
This supersedes #1514

**Comment by danlamanna** [comment]
#1803 resolved your first concern, and your third concern was addressed in #1561, four is sort of taken care of since girder is installed within a virtualenv as of #1561. I've addressed your second concern in #1809.

**Comment by danlamanna** [comment]
@chetnieter Does it make sense to close this out now?

**Comment by chetnieter** [comment]
Yes
