### ISSUE TITLE
Web client leaks Backbone views

### ISSUE THREAD

**Issue by msmolens** [girder/girder#1530]
On the web client front page, simply navigating between the Collections, Users, Group leaks Backbone views. This can be confirmed in Chrome by taking heap snapshots and examining 'Detached DOM tree' entries. [Backbone Debugger](https://github.com/Maluen/Backbone-Debugger) also shows the leaking objects.

Update: Backbone Debugger view list isn't compatible with how we manage views, so it shouldn't be trusted in this case.

**Comment by zachmullen** [comment]
I figured this out, the views are getting properly cleaned, but we were leaking DOM subtrees due to event bindings. In the hierarchy widget, this was actually a result of our tooltips. I'm going to try to figure out a clever way to handle these tooltips now.
