### ISSUE TITLE
AccessControlledModel.prefixSearch is missing prefixSearchFields param

### ISSUE THREAD

**Issue by mgrauer** [girder/girder#1535]
`AccessControlledModel.prefixSearch` [claims](https://github.com/girder/girder/blob/e31ed78e6fba13633ba3fe817aa921f0290c1238/girder/models/model_base.py#L1040-L1050) it has the same params as the base model `prefixSearch` method it overrides, but seems to be missing the `prefixSearchFields` param.

**Comment by msmolens** [comment]
Fixed by https://github.com/girder/girder/pull/1791?
