### ISSUE TITLE
Replace blanket with istanbul for javascript coverage

### ISSUE THREAD

**Issue by jbeezley** [girder/girder#1576]
I decided to take this on.  It doesn't look like it will be incredibly difficult.  It will work like this:

1. Instrument the code with [babel-plugin-istanbul](https://github.com/istanbuljs/babel-plugin-istanbul).  I checked that it works perfectly with our webpack setup.
2. After a test passes pass the global `__coverage__` object the instrumentation produces back to phantomjs.
3.  Phantomjs writes the coverage objects from each test to a unique file.
4. Run `istanbul report` to combine the coverage objects into standard coverage formats (and stdout reporting).
5.  Submit coverage files to CDash, codecov, coveralls, etc.
6. Profit

I think the most difficult part will be surgically removing all of the infrastructure in place for blanket coverage.

**Comment by zachmullen** [comment]
Sweet! I'm happy to help with the removal part.

**Comment by jbeezley** [comment]
@sebastienbarre I'm having a strange issue that I think might be related to [this line](https://github.com/girder/girder/blob/2.0-integration/grunt_tasks/webpack.config.js#L215) in the webpack config.  I have the following diff from the current branch:

```diff
diff --git a/clients/web/test/specRunner.js b/clients/web/test/specRunner.js
index e163293..d69040b 100644
--- a/clients/web/test/specRunner.js
+++ b/clients/web/test/specRunner.js
@@ -37,6 +37,8 @@ if (coverageOutput) {
 }

 var terminate = function () {
+    console.log('fs: ');
+    console.log(Object.keys(fs).join('\n'));
     if (!coverageOutput) {
         // setTimeout(function () {
         //     phantom.exit(0);
```

This is the output:
```
fs:
objectName
workingDirectory
separator
destroyed(QObject*)
destroyed()
deleteLater()
_size(QString)
lastModified(QString)
_copyTree(QString,QString)
makeDirectory(QString)
makeTree(QString)
_removeDirectory(QString)
_removeTree(QString)
_open(QString,QVariantMap)
_remove(QString)
_copy(QString,QString)
list(QString)
separator()
workingDirectory()
changeWorkingDirectory(QString)
absolute(QString)
fromNativeSeparators(QString)
toNativeSeparators(QString)
readLink(QString)
exists(QString)
isDirectory(QString)
isFile(QString)
isAbsolute(QString)
isExecutable(QString)
isReadable(QString)
isWritable(QString)
isLink(QString)
```

The `fs` module is missing all kinds of functions.  What's weird is this is not executing inside the phantomjs client but rather from node, so I don't know why the webpack environment would muck it up.  I need `fs.writeFileSync` to output the coverage files.  Do you have any suggestions?

**Comment by jbeezley** [comment]
Nevermind, apparently phantom uses it's own `fs` module.  It has a write method that for some reason doesn't show up when you do `Object.keys`.

**Comment by sebastienbarre** [comment]
@jbeezley sorry, I was on the road all day (to Nashville). May be able to help tomorrow (Thursday), will be on the road again Friday and Saturday, then a week in Denver with moderate availability. Will keep an eye on the good work :)
