### ISSUE TITLE
Plugin directory must be the plugin name

### ISSUE THREAD

**Issue by manthey** [girder/girder#1597]
We should be able to specify the plugin name such that it can be different than the plugin directory.  This might require that there be a plugin key in the json/yml file, and that such a key would match the Gruntfile task and the package.json name.

**Comment by zachmullen** [comment]
Do you have a use case for this? The directory name makes a convenient natural plugin key since that avoids collisions.

**Comment by manthey** [comment]
It is more to help people avoid confusing problems.  @purg was setting up a system and had placed a plugin in a directory named subtly differently from the plugin (specifically `large-image` rather than `large_image`), and got a cryptic grunt stack trace rather either it working or getting a useful error message.

I'd have no problem if we just had a useful error message instead -- 'this plugin must be in a directory called \<foo>', but it seems like by the time we have enough knowledge to print such a message, we could just allow it to be in any directory.

**Comment by danlamanna** [comment]
I believe https://github.com/girder/girder/pull/2552 renders this moot.
