### ISSUE TITLE
Add endpoint for deleting metadata keys

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#1628]
The way it's done right now is to use the endpoint for setting keys, but set ones to `null` that should be deleted. This is wonky, and it would be more intuitive to just have a separate `DELETE` metadata endpoint to remove a list of keys.

**Comment by ronichoudhury** [comment]
:+1:

I'm dealing with this limitation right now. I would also prefer to be able to use `null` as a full-fledged value, and use a `DELETE /item/<id>/metadata` endpoint to remove entries.
