### ISSUE TITLE
Running Girder ansible module without client results in uncaught NameError

### ISSUE THREAD

**Issue by cjh1** [girder/girder#1631]
```
Traceback (most recent call last):
  File "/home/cjh/debug_dir/ansible_module_girder.py", line 1038, in <module>
    class GirderClientModule(GirderClient):
NameError: name 'GirderClient' is not defined
```

We should write the error message and exit [here](https://github.com/girder/girder/blob/master/devops/ansible/roles/girder/library/girder.py#L34) before we try to use GirderClient [here](https://github.com/girder/girder/blob/master/devops/ansible/roles/girder/library/girder.py#L1038)

**Comment by cjh1** [comment]
@kotfic Here you go.

**Comment by manthey** [comment]
Closing, as we are no longer publish ansible playbooks since #3488.
