### ISSUE TITLE
Rebuild Webcode error via /api/v1/system/web_build

### ISSUE THREAD

**Issue by Purg** [girder/girder#1648]
Context: Extending girder/girder docker image to make one with custom plugins added.

Found that when I enabled plugins (even just one that's included with the base girder and then even when no plugins are enabled), the web_build endpoint would fail even when manually calling "npm run build" succeeds after ``docker exec -it <name> bash`` into the running container.

The following gist shows output from the same container using two methods that I'm assuming should be resulting in the same output:

[1] Calling ``http://localhost:8080/api/v1/system/web_build?progress=false&dev=false``
[2] Calling ``npm install --unsafe-perm && npm run build`` (what the girder Dockerfile does)

Gist: https://gist.github.com/Purg/6f49b7cf4587242ba920130e81bb4d80

Things I've noticed:
- The ``npm run build`` version looks like its running the ``webpack:dev`` task vs. the web_build call running the ``webpack:prod`` task.

**Comment by zachmullen** [comment]
The actual error message is:

```
ERROR in girder.app.min.js from UglifyJs
SyntaxError: Unexpected token: punc ()) [girder.app.min.js:7814,21]
```

I know in the past we've had to explicitly disable uglify from trying to use non-ASCII chars, this may be related.

**Comment by Purg** [comment]
Yeah, I saw that but I have no idea what that meant. =\

**Comment by Purg** [comment]
Another question I guess is why is the ``npm run build`` going in dev mode, but the web_build REST call going in prod mode?

**Comment by zachmullen** [comment]
It's assumed that if you are calling `npm run build`, you're in a dev environment, and that if you are building the code from clicking the button in the browser, you're in a production environment.

**Comment by Purg** [comment]
Maybe a good question to ask is: what is the standard way to install and activate plugins with v2.0? Install plugins with ``girder-install plugin -s <dir-path>``, turn it on via the GUI and the build-web-code + restart via GUI? If the restart via the GUI is problematic, then is there a way to pre-build the plugin web-code via the command-line before starting girder?

**Comment by zachmullen** [comment]
I have reproduced this error in the docker container by changing the line to `RUN npm run build -- --env=prod`. I'm debugging it now.

**Comment by zachmullen** [comment]
I found the source of the error. In the docker container, the webpack output still contains arrow functions, and uglify is balking because they aren't supported in ES5.

Now to figure out why those are there.
