### ISSUE TITLE
Item preview plugin doesn't work properly for items with multiple files

### ISSUE THREAD

**Issue by manthey** [girder/girder#1649]
If I have an item named `foo.jpg`, and that item contains two files, `foo.jpg` and `bar.other`, the item preview plugin will try to render the item as an image, but uses the download endpoint to access it.

It should either properly detect that this is not a simple image, or should always try to handle the first file in an item (if such a file exists).

**Comment by hwrod** [comment]
Thanks @zachmullen! Unfortunately, I won't be able to get to this until February 2017, but if this ticket is open then, I will take a look. Feel free to reassign, or wait until I have availability and I will be glad to take a look. Thanks!

**Comment by zachmullen** [comment]
After discussing with @MayeulChassagnard , I think the best path forward is to introduce a `nFiles` field on each item that tracks/caches the number of files within it. This can be used to quickly determine the number of files in an item without needing to do an extra request for the file list.

That's a significant core change and also involves a migration path to compute this value on legacy items.

**Comment by hwrod** [comment]
@zachmullen I was working a bit on this, though I see @MayeulChassagnard has a good solution as well in PR #1949 . Glad to see it's working out. I had a simple solution of replacing the image src attribute directly (below) on `ItemPreviewWidget` render, but I like his collection update method better. 

Implementing nFiles is beyond anything I can contribute right now, but at least this strategy can preview multiple-file items as images, only requesting a file list when hinted by file extension.

`ItemPreviewWidget.render:`

        ...
        supportedItems.filter(this._isImageItem).forEach(function(item) { 
            restRequest({
              path: `item/${id}/files`,
            })
            .done(function(files) {
              if (files.length > 1) {
                var image = files.find(file => file.mimeType.match(/image/))
                image && view.$(`img[data-id="${item.id}"]`)
                  .attr('src', `/api/v1/item/${image._id}/download`)
              }
        })

**Comment by manthey** [comment]
This was fixed some time ago.
