### ISSUE TITLE
use different strategy to create common Webpack chunk

### ISSUE THREAD

**Issue by sebastienbarre** [girder/girder#1652]
Creating an issue (for myself mostly) to revisit the Webpack strategy used to create the common Webpack chunk. This was mentioned in the original #1476 Webpack PR (copied below). This is as yet to be investigated, but it seems to have adverse affect on CI, as exposed by @jbeezley in DigitalSlideArchive/large_image#111:
- There still appears to be too much duplicated code going in `girder.main.min.js` and each `plugin.min.js`; this needs to be investigated and fixed by myself (Seb; consider [robertknight/webpack-bundle-size-analyzer](https://github.com/robertknight/webpack-bundle-size-analyzer)), also consider the `DllPlugin`, which would increase performance as well ([Webpack Plugins we been keepin on the DLL](https://medium.com/@soederpop/webpack-plugins-been-we-been-keepin-on-the-dll-cdfdd6cb8cd7), [Optimizing Webpack for Faster React Builds](http://engineering.invisionapp.com/post/optimizing-webpack/), [Optimizing Webpack build times and improving caching with DLL bundles](https://robertknight.github.io/posts/webpack-dll-plugins/), [webpack/examples/dll](https://github.com/webpack/webpack/tree/master/examples/dll)). Also check [trivago/parallel-webpack: Builds multi-config webpack projects in parallel](https://github.com/trivago/parallel-webpack)

**Comment by zachmullen** [comment]
The way we add other plugins is just to have a new `entry` webpack option for each plugin. In core, we have two entry points, one for the third party libraries, and one of the girder app. So my question is, does this same sort of unnecessary duplication exist between `girder.app.min.js` and `girder.ext.min.js`? If not, how did we prevent it for that case?

**Comment by sebastienbarre** [comment]
No I don't think it exists, I believe it's when the plugins were introduced that I started noticing it. Will keep you posted.

**Comment by zachmullen** [comment]
Looking at one of our plugins, I see it's only duplicating symbols from underneath girder, but the ones imported from third party libs are being imported as modules like we want (e.g. `var _jquery = __webpack_require__(4);`).

I wonder if this is due to insufficient support for ES6 modules?

**Comment by zachmullen** [comment]
@sebastienbarre I was looking into this out of curiosity and managed to get the plugin.min.js to reference girder core symbols as modules properly by adding the following plugin to webpack.config.js:

```
new CommonsChunkPlugin({
            name: 'girder.app',
            minChunks: 2
        }),
```

However, doing that caused the following error when building girder.ext:

`ERROR in CommonsChunkPlugin: While running in normal mode it's not allowed to use a non-entry chunk (girder.ext)`

I'll dig into that a bit more, was just curious if you knew of an easy fix.

**Comment by zachmullen** [comment]
Reopened since #1655 is a suboptimal hack. For posterity:

The solution I created there is too naive, it just puts any module that is referenced via more than one entry point inside the common bundle (girder.app.min.js). This sort of works, but not really; this will even move symbols from plugins that are referenced by multiple entry points. For example, it's moving the `JobStatus` symbol inside the common bundle since it's also referenced via the worker plugin entry point, and that's a bad thing.

The long-term solution to this dilemma necessarily involves the ability to map input file paths to target bundles, which means CommonsChunkPlugin by itself is not sufficient.

**Comment by zachmullen** [comment]
ping @girder/developers I think the best way to keep with the spirit of webpack's design is probably to do away with multiple bundles altogether, and force a web client rebuild each time new plugins are enabled or disabled. That would give us just one "app" bundle with all our plugins, there would be no more girder.ext.min.* nor any plugin.min.* files.

The problem with this approach is that it makes it hard for us to pre-build a library that can be used by downstreams. A simple package could just be a build of the core, and maybe that's good enough for now.

I'd love to hear others' thoughts on this, as I can't quite reconcile webpack with the notion of truly dynamic plugin loading.

**Comment by jbeezley** [comment]
I don't know that bundling multiple files gives any real benefit to a SPA like this.  My understanding is that when you rebuild with different plugins enabled, the main bundle changes anyway.  I think the only way we could get a caching benefit is if we were to use the DLL loader somehow, but I don't know much about how it works.

**Comment by sebastienbarre** [comment]
Or let Webpack take care of dynamic loading. From [What's new in webpack 2](https://gist.github.com/sokra/27b24881210b56bbaff7#code-splitting-with-es6): "The ES6 Loader spec defines System.import as method to load ES6 Modules dynamically on runtime. Webpack threads System.import as splitpoint and puts the requested module in a separate chunk"
```
function onClick() {
    System.import("./module").then(module => {
        module.default;
    }).catch(err => {
        console.log("Chunk loading failed");
    });
}
```
It's possible to pass an partial expression to System.import. This is handled similar to expressions in CommonJS (webpack creates a context with all possible files). System.import creates a separate chunk for each possible module.
```
unction route(path, query) {
    return System.import("./routes/" + path + "/route")
        .then(route => new route.Route(query));
}
// This creates a separate chunk for each possible route
```

**Comment by jbeezley** [comment]
I explored something like that, but what I found was that webpack will always build every plugin even if they are loaded dynamically.  The problem with that is that we don't want to build plugins like `vega` that require extra runtime dependencies unless we have to.

**Comment by zachmullen** [comment]
Maybe we could do that in the npm packaged environment, but just build a single bundle in the python girder installation?

**Comment by opadron** [comment]
Truly dynamic plugin loading is off the table as long as we're only pre-building bundles.  Truly dynamic plugin loading requires server support and going to [AMD](http://www.requirejs.org/docs/whyamd.html) (not as flashy as es6 on webpack, but so far the only approach that really got javascript modules right, imo).

Barring that, @sebastienbarre's suggestion with webpack is probably the closest we'll be able to get in the foreseeable future.

**Comment by sebastienbarre** [comment]
Note that as of 20 minutes ago, master now implements @zachmullen scenario (maybe accidentally). All plugin code goes in the `girder.app.min.js` chunk, mixed with some third-party code (and probably some core code).

**Comment by zachmullen** [comment]
Right. @jbeezley 's branch plus my recent change to our CommonsChunkPlugin config are what precipitated my asking the question of whether there's any point for us to do multiple bundles. From the sound of things, I'm not sure it's worth trying, and it seems like once we try to do an npm package, we can either cop out and just package the core code, or use the System.import route for plugins.

**Comment by sebastienbarre** [comment]
Maybe of interest as well:
* [Proposal: Dll-like Plugin for an external context - external manifest, dynamic module-map injection and loading · Issue #2592 · webpack/webpack](https://github.com/webpack/webpack/issues/2592)
* [How to load dynamic modules on demand without bundling all together? · Issue #1421 · webpack/webpack](https://github.com/webpack/webpack/issues/1421)
* [Require external (unmanaged) file · Issue #150 · webpack/webpack](https://github.com/webpack/webpack/issues/150)
