### ISSUE TITLE
Add Mongo 2.6 to circle ci

### ISSUE THREAD

**Issue by mgrauer** [girder/girder#1675]
Follow up to #1674

**Comment by danlamanna** [comment]
[Do we really want to still support 2.6?](https://www.mongodb.com/blog/post/mongodb-2-6-end-of-life)

> We are now approaching the end of life of this major version, and we will sunset support for MongoDB 2.6 at the end of October, 2016.

**Comment by zachmullen** [comment]
My thought as well. It's unlikely we'd actually break compatibility with 2.6 given the mongo feature set that we use in Girder, but I'd be fine with dropping it from our official support and CI testing. If that is acceptable to people, this would just be a change in our documentation, perhaps including Dan's link as a justification.
