### ISSUE TITLE
Streamline setup of developer environment

### ISSUE THREAD

**Issue by jcfr** [girder/girder#1684]
As a "quickstart" alternative to [Configuring Your Development Environment](http://girder.readthedocs.io/en/latest/development.html#configuring-your-development-environment), I would suggest to have a one-liner bash allowing to setup the full stack.

That would be similar to what is done here: https://github.com/wikimedia/mediawiki-containers#installation

Considering there is already a `docker-compose.yml` and `Dockerfile` available in the girder repo, some building blocks to enable this are already available.

Finally, coupled with the support for docker container available in tool like [PyCharm](https://blog.jetbrains.com/pycharm/2015/12/using-docker-in-pycharm/), that would streamline the overall setup.

Cc: @mgrauer

**Comment by danlamanna** [comment]
Additionally, though it would certainly take a bit to run, `vagrant up` *should* just work™.

**Comment by zachmullen** [comment]
> vagrant up *should* just work

Are you saying that it doesn't work now, or that you think it does?

**Comment by danlamanna** [comment]
I think it does, at least it did [yesterday](http://my.cdash.org/buildSummary.php?buildid=1085896).

**Comment by jcfr** [comment]
Nice. Is the Girder test suite also executed within the VM ?

Are we using the VM from vagrant as an environment for day to day development ?  @msmolens ?

**Comment by jcfr** [comment]
And to provide some background, I wanted to do some local testing with a mediawiki instance and found the docker approaches very convenient. I then thought it could be relevant for Girder ...

**Comment by danlamanna** [comment]
Those tests are meant to exercise ansible rather than vagrant, we just vagrant as a mechanism for doing so. So the full test suite isn't run, only [tests related to ansible](http://my.cdash.org/viewNotes.php?buildid=1085896).

Also see https://github.com/girder/girder/pull/1561#issue-175346653 and http://girder.readthedocs.io/en/latest/provisioning.html for more info.

**Comment by jcfr** [comment]
> ansible rather than vagrant

Thanks for confirming. Wasn't sure if I was missing something.

>  see #1561 (comment) and http://girder.readthedocs.io/en/latest/provisioning.html for more info

Then, would it make sense to have "docker-compose.yml" and companion bash script be the output of some ansible role ?  With the idea of streamlining development of Girder.

**Comment by msmolens** [comment]
@jcfr We use the VM created by Vagrant for isic-archive, but currently that's independent of any Vagrant/Ansible provisioning in Girder proper.

**Comment by danlamanna** [comment]
I think this can be closed. For quite a while now `docker-compose up` has worked. `vagrant up` typically works, but is being updated right now with https://github.com/girder/girder/pull/2923.
