### ISSUE TITLE
Pressing enter when selecting new user/group in ACL dialog causes page to refresh

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#1739]
Go to an access control widget, go to the search text input, type a name that matches a user or group, scroll down to one using the arrow keys, and hit enter/return. Rather than adding the user/group to the list (as it does when you click the result), the page is refreshed.

We likely just need to `preventDefault` on an event somewhere.

**Comment by mgrauer** [comment]
I saw the same thing in the Girder header bar site search.

**Comment by matthewma7** [comment]
Fixed with PR https://github.com/girder/girder/pull/1897
