### ISSUE TITLE
User registered with Girder/Python 3 cannot log in with Girder/Python 2

### ISSUE THREAD

**Issue by msmolens** [girder/girder#1750]
If a user registers on a server where Girder is run using Python 3, the user cannot log in if the server is restarted using Python 2. This use case may be rare and/or unsupported, but I hit this in a development environment.

The problem looks related to the usual str/bytes conversion issue. In Python 3, the user's salt is stored as binary. For example, the first user below was created in Python 2, the second user in Python 3:

    $ mongo
    > use girder
    switched to db girder
    > db.user.find({}, {'salt':1})
    { "_id" : ObjectId("57b5dd5745440b4306fbd949"), "salt" : "$2b$xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" }
    { "_id" : ObjectId("586a862845440b179108b23c"), "salt" : BinData(0,"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx") }

Here, when the second user authenticates in Python 2, authentication fails when `hash (str)` is compared to `user['salt'] (bson.binary.Binary)`:
https://github.com/girder/girder/blob/ceee691fae963ce054f706a64da37d3c61ea4178/girder/models/password.py#L122
Perhaps, in this case, salt should be decoded to a string for this comparison.

**Comment by zachmullen** [comment]
I'm not sure if this is still a problem, but I'll add the bug label for bookkeeping.

**Comment by manthey** [comment]
Outdated.
