### ISSUE TITLE
Plugin routing gets reset on syntax error.

### ISSUE THREAD

**Issue by opadron** [girder/girder#1756]
- Begin developing your own plugin
 - Set the system-wide plugin routing setting so that your plugin serves its contents from "/" and so that girder-core is served from "/girder".
 - While working on your server-side code, "accidentally" introduce a syntax error.

At this point, Girder auto-restarts, sees that your plugin is broken, and responds with a number of actions that seem to include resetting the plugin's routing.

Therefore, when you fix your code and go back, your plugin is serving on "/PLUGIN_NAME" instead of where you left it.

I propose that this behavior be regarded as a bug as the less surprising behavior, imo, would be to leave the routing alone and having your plugin work again once you fix your syntax error.  Correction of such a bug would greatly improve the plugin developer experience.

**Comment by danlamanna** [comment]
@zachmullen had brought up the autoremoval of routes when I initially added this code. One of the issues with that approach is the custom routes would be preserved forever whether or not they actually had a plugin using them.

We could do some combination of the following:
1) Track when a plugin is explicitly disabled via the settings API and remove the route then
2) Show (and allow removal) of "stale" routes which no longer have a plugin webroot associated with them

**Comment by ronichoudhury** [comment]
Autoremoval of routes seems to me to have dubious value. Changing the routes automatically is surprising to the developer, especially in the scenario @opadron describes. IMO, it should be on the admin to change routes for disabled plugins (given that they're the one who explicitly enabled those routes in the first place).

I could possibly be convinced otherwise on this point, but in the case where a plugin fails to load for some development reason (which will soon be fixed by the developer), and the route reverts because of that, I believe this behavior is a bug.

**Comment by zachmullen** [comment]
> At this point, Girder auto-restarts, sees that your plugin is broken, and responds with a number of actions that seem to include resetting the plugin's routing.

This also surprises me, I didn't realize this happened. I agree with @opadron and @ronichoudhury

**Comment by opadron** [comment]
Ok, I've dug into this issue and have gained a more detailed theory about what is happening.

The crux of the issue is that girder does not directly register webroots for plugins; the details are actually left to the plugins to fight amongst themselves for their share of the webroot namespace.

If there is a syntax error in a plugin's server code, and this syntax error causes the plugin to fail before it is loaded, then the plugin would never get the chance to register a webroot key for itself.

So, before girder restarted, it had an object that would handle requests under the name "osumo" (using osumo as an example), but after restarting, that object is gone.  With no object, girder has nothing to actually "mount".

I believe the code section relevant to how girder responds in this situation starts at [girder/utility/server.py:178](https://github.com/girder/girder/blob/master/girder/utility/server.py#L178).  It looks like just not deleting the route table entries would resolve this issue (effectively making every route a "reserved route").

What do you guys think about this idea?  I'm not too familiar with this code, so I'm not sure if "every route is now a reserved route" might have undesirable consequences?  Are there other articulable circumstances in which we're sure we'd want to cull the route table?
