### ISSUE TITLE
Symlinked plugins with package.json file break web build

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#1768]
See the conversation on #1766. Something about having the package.json file present causes a failure to load the pug runtime javascript; it's looking for the file inside the girder alias (girder/clients/web/src/node_modules) rather than girder/node_modules.

For reference, this might only occur when the plugin being linked is a sibling of the top level girder dir.

**Comment by zachmullen** [comment]
Possible solution documented here: https://github.com/xjamundx/webpack2-example/issues/1

**Comment by danlamanna** [comment]
pip installable plugins removes the notion of symlinked plugins.
