### ISSUE TITLE
The --watch-plugin option configures all plugins

### ISSUE THREAD

**Issue by jbeezley** [girder/girder#1789]
Credit to @matthewma7 for pointing this out.

When running `girder-install web --dev --watch-plugin jobs`, you get an error about `string-replace-loader` being missing.  I posted the full output [here](https://gist.github.com/jbeezley/ecb1b72b1141b9f8acab2acddabf3c07).  (To reproduce, you may need to run `npm prune`)

The issue is that watch invokes the configuration for all plugins, but not the `npm install` step.  That adds the the `string-replace-loader` from `dicom_viewer` to the webpack configuration.  Just building with the `--plugins jobs` flag still works though.

**Comment by zachmullen** [comment]
https://github.com/girder/girder/pull/1784 fixes this

**Comment by jbeezley** [comment]
Okay @zachmullen this is getting scary.
