### ISSUE TITLE
UploadWidget: Provide file IDs

### ISSUE THREAD

**Issue by msmolens** [girder/girder#1790]
UploadWidget should provide a way for clients to retrieve the unique IDs of the new file models.

**Comment by zackgalbreath** [comment]
I'd be happy to take this on, but I'll need a better understanding of the motivating use case.

After an initial investigation, I noticed that when uploading, the response from the final `POST` to `file/chunk` is the newly created file model (including its `_id`).

**Comment by msmolens** [comment]
Thanks. Here's an example:

In the view below, the user uploads a file into a folder, then later we call an endpoint that requires the ID of that file. Currently to get the file ID we manually retrieve the folder's items and the item's files:
https://github.com/ImageMarkup/isic-archive/blob/49fa6d478fe1a8c7dc14a3999770e87e5c5b84e2/web_external/Datasets/RegisterMetadataView.js#L15-L29

Ideally UploadWidget would send the file IDs with the `g:uploadFinished` event. As you noted, the widget already receives the IDs, but doesn't record them.

**Comment by zackgalbreath** [comment]
Give #1831 a try when you get a chance and let me know if it works for you.

**Comment by msmolens** [comment]
Implemented in #1831
