### ISSUE TITLE
Girder fails to start in default 'vagrant up' deployment

### ISSUE THREAD

**Issue by msmolens** [girder/girder#1796]
Girder fails to start in the default 'vagrant up' deployment for development.

To reproduce, follow documentation to set up Girder development environment:
http://girder.readthedocs.io/en/latest/development.html#vagrant

```
$ vagrant up
...
```
Expected result: Browsing to http://localhost:9080/ shows Girder web front-end.
Actual result: Browsing to http://localhost:9080/ shows `500` errors loading Girder resources.

Traceback when running `python -m girder`:
```
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/girder/local/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/home/vagrant/.virtualenvs/girder/local/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/girder/local/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 68, in __call__
    raise x
TypeError: 'BaseWebroot' object is not callable
```

**Comment by danlamanna** [comment]
I've seen this error sporadically (since introduction of #1484) and never been able to consistently reproduce it. In fact, `vagrant up` works perfectly for me.

**Comment by danlamanna** [comment]
I'm going to put some effort in trying to reproduce this, if that doesn't work I may have to figure out `vagrant package` and try to get you to send me your VM.

**Comment by msmolens** [comment]
It looks like the `Build Girder (web)` handler is never run in this case. This should be reproducible from a fresh checkout or clean repo (`git clean -dfx`). Running `girder-install web` manually after provisioning builds the web front-end successfully.

**Comment by danlamanna** [comment]
I was just posting to this.

The bug here is the issue with the Ansible handler, and also that non-existent static assets are returning 500 errors instead of 404s. I've figured out the 500 error and am opening a PR shortly.
