### ISSUE TITLE
Include babel ES6 polyfill in built sources

### ISSUE THREAD

**Issue by jeffbaumes** [girder/girder#1821]
Phantom testing, and older browsers, do not support all of ES6, so to support using ES6 code in Girder we would need to include the polyfill. One example is my attempt to use `Array.prototype.includes` in https://github.com/girder/girder/pull/1764.

**Comment by brianhelba** [comment]
@jeffbaumes The test environment is now getting a full Polyfill: #2055 

Can we be more precise about which older browsers+versions we want to be supporting? Do we need to have a multi-tiered definition of what "support" means?

If we do need to "support" things like IE in some way, perhaps it'd be better to selectively serve the polyfill, based on the `User-Agent` HTTP header? This way we don't waste bytes serving the polyfill to modern browsers.

**Comment by matthewma7** [comment]
@brianhelba, Is it possible you change to the testenv has an issue that you change included core.js into **testing.min.js**, but **testing.min.js is** is inlucded after **girder_lib.min.js**, so the codes that are executed immediate in **girder_lib.min.js** would not have the polyfill?

**Comment by jeffbaumes** [comment]
It was the lack of support in testing that prompted opening this issue (I was seeing things work in the browser that failed in testing), so yes I think this is addressed with the addition of core-js and I'm comfortable closing this. Looks like `Array.prototype.includes` is covered, even though it looks like this is actually an ES7 feature: https://github.com/zloirock/core-js#ecmascript-7-proposals

Figuring out exactly what browsers we support, documenting it well, and making our testing environment(s) match what we support, I think is a bigger/separate issue.

**Comment by brianhelba** [comment]
@matthewma7 Good point. While in theory, nothing but function definitions (and lots of `_.extends`) *should* be getting executed as a side-effect of sourcing `girder_lib.min.js` and all instantiation should happen though `document.ready` handler, I think it's still a reasonable idea to be safe in this case, and move `shim.js` out to be the first script sourced into the page. I'll make a PR.
