### ISSUE TITLE
Jobs page should automatically show new jobs

### ISSUE THREAD

**Issue by danlamanna** [girder/girder#1833]
The eventstream is used for progress bars of new jobs, but the actual new job doesn't display on the jobs page until it's manually refreshed.

**Comment by jbeezley** [comment]
Are you running the most recent version of girder?  I fixed a bug that could cause this behavior in https://github.com/girder/girder/pull/1816.

**Comment by danlamanna** [comment]
I don't think that fixed it. Ultimately `render` needs to be called there which will only happen if the collection changes. Currently I think we only change the status of objects already in the collection instead of modifying it.

**Comment by jbeezley** [comment]
You must be hitting some edge case.  The status updates correctly in my plugin that uses the job list view.  It doesn't rerender on status change, but [this line](https://github.com/girder/girder/blob/master/plugins/jobs/web_client/views/JobListWidget.js#L58) calls a method that modifies the status of the elements on the page.  I would check that the [`_statusChange`](https://github.com/girder/girder/blob/master/plugins/jobs/web_client/views/JobListWidget.js#L132) method is getting called correctly.

**Comment by jbeezley** [comment]
Okay, I misunderstood.  The issue reported here is that new jobs don't show up, not that the status doesn't update.  Something probably needs to trigger a fetch on the job collection after a new job is submitted.  I'm not sure if the event stream currently does this.

**Comment by zachmullen** [comment]
`updateJob` triggers notifications, however I don't think `createJob` does at this time. It probably should.
