### ISSUE TITLE
Stop caching webroot HTML when in development mode

### ISSUE THREAD

**Issue by danlamanna** [girder/girder#1859]
I've encountered this before and it was a little confusing, and @Purg just ran into the same thing.

If you're developing a plugin and adding js or css for the first time (i.e. your plugin just now starts creating a plugin.min.{css,js}) then it won't be rendered in the HTML until a full restart of Girder.

I believe that's because we're caching the contents of `_renderHTML`, see [webroot.py](https://github.com/girder/girder/blob/1407b56a26950cdb6e922ccbb2ff2368c78a3ae7/girder/utility/webroot.py#L57). We may want to put a check if it's development mode and if so do the extra work of checking for css/js files every render.

**Comment by Purg** [comment]
+1 I spent way too much time trying to figure out why a new stylesheet was not being used...

**Comment by zachmullen** [comment]
Works for me, as long as we still cache it in production.
