### ISSUE TITLE
Fresh girder-install web fails with a failure to resolve dependency packages

### ISSUE THREAD

**Issue by Purg** [girder/girder#1883]
Maybe its because I'm using girder v2.1.1, but I just cleaned my local python install as well as made a clean source checkout of girder. I did the usual ``pip install -e .[plugins]`` in the source, and then attempted a ``girder-install web --dev``. This failed with the following STDOUT output: https://gist.github.com/Purg/ca6d0eb30194340cb9414f6df001d353

If I manually ``npm install moment``, or other packages that were reported as not resolvable, a repeat call to ``girder-install web`` gets past those points. The following is the list of packages that I've had to manually install (including for additional plugin dependencies of geojs, mathjs and jquery-ui):
- moment
- autolinker
- d3 (geojs)
- typed-function (mathjs)
- tiny-emitter (mathjs)
- decimal.js (mathjs)
- complex.js (mathjs)
- fraction.js (mathjs)
- seed-random (mathjs)

After manually installing all of these, a ``girder-install web`` succeeds. Am I just doing something wrong?

**Comment by Purg** [comment]
I ``rm -rf``'ed the entire source root and did a full checkout after encountering a different grunt version issue.

**Comment by zachmullen** [comment]
Could you post what platform this is on, node and npm version, and commands to reproduce?

**Comment by Purg** [comment]
Fedora 23
node v4.5.0 (npm v2.15.9) [installed via nvm]

```
$ git clone https://github.com/girder/girder.git ./source
$ cd ./source
$ git checkout v2.1.1
$ pip install -e .[plugins]
$ girder-install web --all-plugins
```

**Comment by jbeezley** [comment]
We require npm >= 3.  You'll probably need to delete `node_modules` after updating.

`npm install -g npm`

**Comment by Purg** [comment]
That does it. Thanks for the command.
