### ISSUE TITLE
girder-cli defaults to https and localhost

### ISSUE THREAD

**Issue by danlamanna** [girder/girder#1890]
It seems like we've changed the default scheme for girder-cli to be https while leaving the default host as localhost (see https://github.com/girder/girder/blob/2d55c0767294ce78d6b6a90c33ebd3d9bbe12071/clients/python/girder_client/__init__.py#L172). This seems a bit counter intuitive.

Additionally, the documentation still notes the default as HTTP.. so I'm unsure if the change was intentional.

@jcfr

**Comment by danlamanna** [comment]
@jcfr Any thoughts on this? Our ansible nightlies are currently failing because they're trying to provision to https://localhost. I can go through and change each girder-ansible task to use `scheme: http`, but I want to make sure this default isn't going to be changed back.

**Comment by jcfr** [comment]
I have a wip topic. Will push it asap.
