### ISSUE TITLE
Reuse TCP connections in girder-client where possible

### ISSUE THREAD

**Issue by danlamanna** [girder/girder#1894]
When using girder-client in the context of remote jobs, it's entirely possible to send a large amount of requests to a Girder instance. It might be worth investigating if/how something like requests [session objects](http://docs.python-requests.org/en/master/user/advanced/#session-objects) could be utilized to reuse the existing tcp connection.

**Comment by zachmullen** [comment]
Makes sense to have a request session object on each GirderClient. 👍
