### ISSUE TITLE
Support poll option for 'girder-install web --watch'

### ISSUE THREAD

**Issue by msmolens** [girder/girder#1912]
When developing using Vagrant `girder-install web --watch` doesn't recognize changes to files made outside the VM. Supporting the `poll` webpack watch option should allow this workflow. 
https://webpack.js.org/configuration/watch/#watchoptions-poll

**Comment by ronichoudhury** [comment]
Just as an FYI, I recently ran into this problem for plugin development, and added the option to my plugin's webpack.helper.js. It worked nicely so I think we should mention this in the plugin dev docs, and also add it as an option to the core build.

**Comment by brianhelba** [comment]
Fixed by #2214 ! You'll have to `vagrant provision` again, once that code is merged in.
