### ISSUE TITLE
Capture all stdout and stderr into the logs

### ISSUE THREAD

**Issue by manthey** [girder/girder#1919]
Currently, there are a few exceptions that can be emitted on stderr that aren't logged.  Generally, it would be nice if anything emitted to stdout and stderr would be sent to the logs as well, as that would give a single location to check.

Similarly, we currently divide information between the info and error logs by default.  We can merge these together by specifying a single file for both, but I think it might be handier to log everything to info while still logging errors to the error log (to have separate levels for each of the logs), that way you can tail the info log to watch everything that is happening but check the error log for recent errors.

**Comment by danlamanna** [comment]
>  I think it might be handier to log everything to info while still logging errors to the error log (to have separate levels for each of the logs), that way you can tail the info log to watch everything that is happening but check the error log for recent errors.

+10

**Comment by manthey** [comment]
Added in PR #1935.
