### ISSUE TITLE
item_tasks callback URL does not use worker-visible URL

### ISSUE THREAD

**Issue by jeffbaumes** [girder/girder#1924]
It seems that when the worker is on a different server than girder, `getApiUrl` will return `localhost` and not use the worker URL in two places:

https://github.com/girder/girder/blob/master/plugins/item_tasks/server/rest.py#L262
https://github.com/girder/girder/blob/master/plugins/item_tasks/server/rest.py#L367

This should instead use the worker plugin's Girder URL config option if available and fall back to this.

@zachmullen

**Comment by danlamanna** [comment]
Since it depends on worker, you should be able to just import [getWorkerApiUrl](https://github.com/girder/girder/blob/2b365f2f84317b90bc0371e89a9df90a0c31527d/plugins/worker/server/utils.py#L25) right?

**Comment by zachmullen** [comment]
Yep

**Comment by jeffbaumes** [comment]
Ok I think I can handle that fix.
