### ISSUE TITLE
Allow more than one OAuth setup per provider

### ISSUE THREAD

**Issue by mgrauer** [girder/girder#1942]
This may conflict with how OAuth should work.

Currently we allow only a single client id/token per OAuth provider, so we are e.g. limited to having a single GitHub tied to OAuth.  Is there a reason we shouldn't allow multiple per provider?

**Comment by zachmullen** [comment]
> a single GitHub tied to OAuth

Could you elaborate? What is it you would like to be able to do?

**Comment by mgrauer** [comment]
I'll close this, as there is nothing preventing this now.

I had wanted to be able to allow OAuth for a single Girder instance from multiple GitHub orgs.

@zachmullen responded in an email discussion

>The org you use to register the client won't affect which orgs are allowed to join.  The only place that matters, to my knowledge, is what gets displayed on the authorization page Github shows you and in the list of authorized apps.

>I think the spirit of these OAuth clients is that they are meant to represent shared ownership between a GitHub account (in this case @girder) and the web site (your Girder instance on AWS). Essentially this assures users that, e.g. "The administrators of website X also have administrative access over the @girder account". GitHub *might* (haven't tested) allow the same OAuth client website to be claimed by two different github accounts, but presenting our users with two different "Login with GitHub" buttons would probably generate confusion IMO.
