### ISSUE TITLE
Sync Python client version with server version

### ISSUE THREAD

**Issue by mgrauer** [girder/girder#1959]
I realize this might be tricky to pull off (dealing with semantic API versions of both), and controversial, but it is generally much simpler for developers and users if the versions are synced.

**Comment by zachmullen** [comment]
> but it is generally much simpler for developers and users if the versions are synced.

I don't think we can take this premise as a given.

**Comment by mgrauer** [comment]
To clarify, what I meant specifically was, I think it is simpler to figure out which version of server fits with which version of client when the versions are synced.

**Comment by zachmullen** [comment]
So far, every version of the client has worked with every version of the server (modulo bugfixes). I'd like to keep it that way as long as possible. We may have to break that someday, but I'd rather not do it prematurely unless there's a compelling reason.

**Comment by mgrauer** [comment]
I'm fine with this, what I really want is something that can be communicated clearly--and I think it is good to put the design intent into that communication to further transparency.  I'd like this added to RTD as an outcome.
