### ISSUE TITLE
Candela plugin: look into reducing size

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#2007]
Right now, the candela plugin is ~11 MB in dev mode and ~5 MB minified. (By comparison, Girder's whole core codebase is ~1.5 MB.) We should figure out if there are some simple ways for us to reduce this size.

One thing to consider is how to share vega between the several plugins that now depend on it, but do not have explicit runtime dependencies between each other (jobs, vega, candela).

**Comment by ronichoudhury** [comment]
Thanks for mentioning this in the Girder context. Jeff and I have actually been discussing this issue lately, and I have a few solutions in mind, most of which depend on "externalizing" the currently bundled dependencies in Candela. This is basically the explicit advice [Webpack gives](https://webpack.js.org/guides/author-libraries/#add-externals) in the 2.0 docs. I have a tentative plan to follow this advice, then provide wrapper libraries alongside Candela that can be imported as needed to fill in some of the external deps (in case the client author doesn't want to import them directly, etc.). I may or may not do that latter thing, but it's something we're looking into.

**Comment by manthey** [comment]
This was moved to another repository.
