### ISSUE TITLE
Standardize text around DockerHub in item_tasks.

### ISSUE THREAD

**Issue by mgrauer** [girder/girder#2014]
Currently we use Docker Hub in a couple places and docker registry in others.  Unify these to use "Docker Hub".

Follow on to #2003.

I've seen instances of "docker registry" here

plugins/item_tasks/web_client/templates/configureTasks.pug
plugins/item_tasks/server/rest.py

**Comment by zachmullen** [comment]
@mgrauer PTAL at https://github.com/girder/girder/pull/2005
