### ISSUE TITLE
DICOM viewer plugin doesn't preview public item if not logged in

### ISSUE THREAD

**Issue by MayeulChassagnard** [girder/girder#2016]
As you can see on the following screenshot, we are asked to log in to render the viewer
![dicom-viewer-plugin_ask-to-log-in-to-preview-the-item](https://cloud.githubusercontent.com/assets/20341270/26371151/d9bb9008-3fc7-11e7-8ca2-6e5d16e7e477.png)

No preview if you're not logged in
![dicom-viewer-plugin_no-preview-if-not-logged-in](https://cloud.githubusercontent.com/assets/20341270/26371020/7f93c7d0-3fc7-11e7-8606-ca09ffdb9f88.png)

**Comment by zachmullen** [comment]
I reproduced this against the demo instance, here is the request that fails:

`GET http://demo.kitware.com/girdermaster/api/v1/item/59247d36db3d80000b0fbe62/dicom?filters=dummy`

With 401: `{"message": "You must be logged in.", "type": "access"}`.

The endpoint is listed as `@access.user`, but it should probably be `@access.public`.

**Comment by MayeulChassagnard** [comment]
thanks @zachmullen ! I'm going to give a try to fix this.

**Comment by zachmullen** [comment]
Cool, it should be simply changing `user` to `public` on [this line](https://github.com/girder/girder/blob/master/plugins/dicom_viewer/server/__init__.py#L15).
