### ISSUE TITLE
Creation of girder job models via REST endpoints in worker plugin

### ISSUE THREAD

**Issue by kotfic** [girder/girder#2018]
### Deliverables:
+ Post to endpoint that creates a girder job
### Technical Notes:
+ Parent-child is one to many
+ How will we implement access control on creating jobs?
+ How should access control be implemented for job creation?
+ Depending on how restrictive we want to be this to be we may want require that jobs can only be created if they are children of existing jobs
### Depends on: 
+ Allow parent-child relationships between girder job models (https://github.com/girder/girder/issues/2017 - see note above)

**Comment by zachmullen** [comment]
Re: access control, for the first pass we can require a special token scope that allows job creation, and create such a token just for the worker to use. Thus, ordinary users could not just create jobs arbitrarily.
