### ISSUE TITLE
RFC: Prepopulating the database for client tests

### ISSUE THREAD

**Issue by jbeezley** [girder/girder#2022]
A common pattern when writing client tests for girder is to create a bunch of set up code that creates users, uploads files, etc.  We have many functions in [testUtils](https://github.com/girder/girder/blob/master/clients/web/test/testUtils.js) to reduce the amount of boilerplate code necessary to do this; however, I've had a few problems with this approach.
1. The helper functions don't work for testing external plugins that don't use the main girder ui.
2. It relies on navigating the page using synthetic click events that are difficult to get right in the headless environment.
3. It creates many opportunities for race conditions in the tests and generally slows down the testing.

I'm considering adding some code to the test runner that can initialize the database to some repeatable state before starting the web server, and I want to collect comments about it before I attempt to implement it.  The idea would be to add a new optional argument to the `add_web_client_test` where you could pass in the path to a json file that would contain the desired state.

I considered the idea of just loading a mongo backup, but that would require regenerating them every time the document model changes.  Instead, I think it would be best to derive a custom format containing the information necessary to initialize the documents using girder's model API.  A possible json format would be structured as follows:
```json
{
  "users": [{
    "admin": true,
    "email": "...",
    "firstName": "...",
    "lastName": "...",
    "login": "...",
    
    "folders": [{
      "name": "...", 
      "description": "...",
      "public": true,

      "folders": [],

      "items": [{
        "name": "...", 
        "description": "...",
        "files": [{
          "name": "...",
          "mimeType": "...",
          "path": "/path/to/file/content"
        }]
      }]
    }]
  }],
  
  "collections": [
  ]
}
```
Each object would roughly contain the arguments passed to the `create*` method for each model type.  The objects would be nested to declare their intended topology.

Are there any problems with this that I'm missing?  Is this something others would be interested in using?

**Comment by zachmullen** [comment]
This sounds good to me, and it jives with [how we already allow executing arbitrary python modules at startup time with an environment variable](https://github.com/girder/girder/blob/master/tests/web_client_test.py#L161-L164).

**Comment by manthey** [comment]
I like it.

As long as we are adding convenience, since the one-file-item is such a common use case, I'd love to see it handled in some more compact way yet:
```
"items": [{
  "name": "...",
  "mimeType": "...",
  "path": "/path/to/file/content"
}]
```
Where having a `path` is sufficient to use it and the `mimeType` as the file.

**Comment by danlamanna** [comment]
Extending David's idea a bit further, using Girder's importer might be useful here. For example, I want to run client tests that take my folder `test_images` (a regular directory with several jpgs) and create a folder in Girder named `test_images` with an item for each jpg. Does that sound reasonable?
