### ISSUE TITLE
Allow installation of individual plugins in Ansible role

### ISSUE THREAD

**Issue by danlamanna** [girder/girder#2025]
There should be an ansible variable named `girder_plugins` which will allow the user to only install the plugins (and system dependencies for those plugins) they need. This will require logic in Ansible determining the system dependencies for each plugin.

Re #2024

**Comment by mgrauer** [comment]
I allowed for specifying the enabled Girder plugins in the item_tasks ansible [playbook](https://github.com/girder/girder/blob/master/plugins/item_tasks/devops/playbooks/site.yml#L7), but it doesn't do anything like solve the system dep problem.  This is to say, whenever anyone implements the `girder_plugins` variable mentioned in this issue, please update the item_tasks playbook and [post-tasks](https://github.com/girder/girder/blob/master/plugins/item_tasks/devops/playbooks/post-tasks/girder.yml#L29) to use it.

**Comment by danlamanna** [comment]
This is no longer relevant in the new role, downstream should use the `pip` module to install plugins.
