### ISSUE TITLE
Incompatibility with npm v5

### ISSUE THREAD

**Issue by jbeezley** [girder/girder#2043]
npm version 5 was recently released and made some changes that break how we install plugins in girder. `npm install <package>` now saves the package into `package.json` so when we install plugin dependencies, girder's `package.json` is modified.

**Comment by jbeezley** [comment]
Sorry hit enter too early, editing with the issue description now.

**Comment by zachmullen** [comment]
Gross.

**Comment by jbeezley** [comment]
As it turns out, you can disable the behavior with the `--no-save` option.  I'm working on a patch now.

**Comment by zachmullen** [comment]
Good news, thanks 👍
