### ISSUE TITLE
Allow S3 assetstores to be added without access keys

### ISSUE THREAD

**Issue by danlamanna** [girder/girder#2054]
When running Girder on EC2 it would be nice to have S3 work with IAM roles/instance metadata rather than a specific users credentials, see http://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html?shortFooter=true#use-roles-with-ec2.

This would mean no access/secret key would need to be provided by the administrator, instead, `boto` would automatically use the temporary credentials that exist on the instance.

**Comment by kotfic** [comment]
+1

**Comment by danlamanna** [comment]
@zachmullen It turns out that adding support for this is as simple as configuring Boto with the 's3v4' signature version. Our current logic is that if there's no credentials we assume unsigned, however if we can work around this we will be able to support everything listed here: http://boto3.readthedocs.io/en/latest/guide/configuration.html#configuring-credentials (8 being this issue).

Any thoughts on how to expose this to the user? Maybe just an "anonymous" checkbox?

**Comment by zachmullen** [comment]
To clarify, the botocore.UNSIGNED version does not work for case 8 there, you have to use 's3v4' but just omit aws_access_key_id and aws_secret_access_key? If that's true, an anonymous checkbox works for me.

**Comment by zachmullen** [comment]
Or maybe a checkbox that indicates that authentication will occur, but the credentials will be inferred rather than passed explicitly.

**Comment by danlamanna** [comment]
> To clarify, the botocore.UNSIGNED version does not work for case 8 there, you have to use 's3v4' but just omit aws_access_key_id and aws_secret_access_key?

Yes.
