### ISSUE TITLE
Create a Terms of Service plugin

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#2056]
A new plugin should be created, which will allow admins to require users to agree to a customizable "Terms of Service" (TOS) agreement before accessing some parts of a Girder instance via the web GUI. While there may be some server-side endpoints to store and retrieve info, all of the enforcement for TOS agreement will be client-side. Traditional use of the API (e.g. downloading of files) will be unaffected.

* A TOS agreement should be applicable to specific collections:
  * If the plugin is enabled, then users with admin permissions on a collection can enable the functionality and set the text.
  * Users will need to agree to the TOS for that specific collection before accessing anything in that collection's hierarchy widget, item pages in that collection, or any other views that are "within" that collection.
* A TOS agreement should be optionally applicable to the entire site
  * This will be a sub-option of the plugin, and will be enabled and configured by site admins
  * Most views will be protected, but we will need to exclude some:
    * The home page
    * A user's own account, so they can at least delete their account if they really don't want to agree to anything
  * To be future-proof, we'll probably have to protect all top-level views / routes by default, then whitelist certain exceptions.
* The TOS agreement itself will consist of some markdown-formatted text, and a buttons to accept or decline the terms
  * Accepting the terms will store the acceptance in the most persistent way possible:
    * in the database for logged-in users
    * in LocalStorage for anonymous users
    * in a JS variable as a final fallback
  * Declining the terms will redirect to the home page, and store nothing, so users could come back and accept the terms later.

**Comment by mgrauer** [comment]
Fixed by #2138
