### ISSUE TITLE
Consider redirect to root on login/logout

### ISSUE THREAD

**Issue by jeffbaumes** [girder/girder#207]
I was often confused when switching between users that the page does not change. For example, I stayed on the admin page when logged out, and stayed on item/folder pages that I did not have access to when logged out or logged in as a user without privileges to that resource. When I'm on a page that doesn't make sense, I get a message in HTML stating this (like on the admin page) or I get a popup on a failed request. The latter seems especially disrupting so that could at least be changed to an HTML message on the page.

The only plus of keeping the URL the same is that there could be a "user switching" pattern which could be interesting that enables looking at the same thing, like an item or group from different roles.

**Comment by mgrauer** [comment]
Closed by #834 .
