### ISSUE TITLE
Issues with turning off EventStream

### ISSUE THREAD

**Issue by manthey** [girder/girder#2075]
Since PR #1687, we turn off the EventStream connection when a browser tab loses focus.  When you return to the tab, stale status can be displayed because recent status updates were missed.  Also, some plugins expect to get messages and miss them.

As an example, delete or move a group of items such that the action will take a while.  Change to a different tab.  Wait until the action completes plus the expiration time of the progress message.  Navigate back to the tab, and the status of the delete or move is still displayed and won't be cleared.  Refreshing the page fixes the issue.

Some job plugin widgets expect to observe status changes through the event stream, but if they occur when the stream is not being watched and more than 30 seconds before switching back to the tab, the widget misses them and is in an incorrect state.

Either we need to save a queue of events to replay, or clients need to know when a stream was disconnected and therefore could have missed information so that they can reload the appropriate information when they regain focus.

**Comment by matthewma7** [comment]
I forget the reason we would like to close the connection. Is it the cost on the client or on the server?

Based on my experience with WebSocket, I simply had web connection open all the time but when there is a disconnection, all component would get a disconnect event and re-initialize its data. 
This pattern was easy to implement and worked great for me. (Probably attribute to socket.io implementation, it has heartbeat request etc.) Even on phones, switch out the browser app won't stop the connection, all messages are queued somewhere and will be fed to the app when user switch back to the browser app. (Not sure about the behavior if the socket.io fallback to the long poll)

**Comment by zachmullen** [comment]
> I forget the reason we would like to close the connection. Is it the cost on the client or on the server?

It was actually because we had users opening many tabs to girder, and chrome counting the event sockets against a global max concurrent connections to a single domain. Not sure if that's still an issue even, but then we figured there simply wasn't a point receiving real time events on a backgrounded tab, though that could change in the future.

**Comment by matthewma7** [comment]
Is this a time to consider switching to WebSocket? It has IE support and doesn't have the connection count limitation.

**Comment by manthey** [comment]
We want to solve this for a stopped connection regardless of the underlying technology -- you can get the same behavior by putting a laptop to sleep and then waking it up again (or switching networks and reconnecting to a vpn, etc.).

**Comment by zachmullen** [comment]
Right, websocket vs. eventsource doesn't matter here -- the main difference between those two technologies is that websockets are duplex and eventsource is one-way. Since we only need one-way, eventsource is the easier path.

**Comment by matthewma7** [comment]
Sorry if I wasn't clear. I was thinking we don't need purpose disconnect with WebSocket, which would greatly reduce the disconnection. And if real disconnection happens, we send global disconnect event to reload data at the component level, which may cost a little bit work on the server and a little bit visual disruption on the client.

**Comment by manthey** [comment]
As of PR #2163, events are triggered when the event stream stops and starts.  This allows the core code that relies on it to recover.  Any external plugins that expects to have a permanent connection will have to listen for the appropriate message and take the appropriate action when the connection is broken or comes back.
