### ISSUE TITLE
Fix deployment on Heroku

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#2078]
Girder used to have the ability to deploy to Heroku, but it broke over time due to lack of support and testing. Heroku-specific files were removed by #2076 .

If support for Heroku deployment is desired, the deployment files and documentation will need to be brought up to date. Ideally, testing should be added, to ensure breakage does not occur again due to lack of attention.

**Comment by zachmullen** [comment]
If anyone cares about this, please post or resurrect this issue.
