### ISSUE TITLE
Allow data to be included as part of POST /file

### ISSUE THREAD

**Issue by manthey** [girder/girder#2088]
Allow data to included as part of `POST /file` like it is included in `POST /file/chunk`.  This would be equivalent of calling `POST /file` without the data and then calling `POST /file/chunk` with the data and an offset of 0.  If the data is the entire file, `POST /file` would return a file object.  If it is not the entire file, it would return an upload object.

This allows small files to be sent as a single request.  For files large enough that they must be chunked, it can still reduce the number of requests by 1.

Increase the version number and allow the girder-cli to use this more efficient method for the first chunk of a file.

**Comment by manthey** [comment]
We may also want to make a similar change to `PUT /file/{id}/contents`.

**Comment by manthey** [comment]
If the data is the complete data for the file, I'd like to consider avoiding saving the upload to the db (which would be a change to `createUpload` and `createUploadToFile`).  Doing so would skip sending the `model.upload.(validate|save|save.created|save.after)` events, but would speed things up.  This might be undesirable as those events may be monitored.

**Comment by manthey** [comment]
Added ind PR #2111.

**Comment by zachmullen** [comment]
We need to test this with S3 assetstores in the direct upload case, to make sure our clients work in this new mode when dealing with a redirect.
