### ISSUE TITLE
Test flakiness after move to jquery 3

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#2093]
[These tests](http://my.cdash.org/viewTest.php?onlyfailed&buildid=1226366) are failing somewhat frequently now. I believe the move to jquery 3 has caused some new race conditions to emerge.

ping @brianhelba

**Comment by brianhelba** [comment]
I think the `web_client_autojoin.autojoin` failure is a server-side issue. The API request which should [simply create a new user](https://github.com/girder/girder/blob/971d7b60710dba77da626cdbb0078bb78c951bbb/plugins/autojoin/plugin_tests/autojoinSpec.js#L116) is failing as:
```
  {
    "opts": {
      "dataType": "json",
      "type": "POST",
      "error": null,
      "path": "/user",
      "data": {
        "login": "user1",
        "password": "password",
        "email": "user1@example.com",
        "firstName": "Joe",
        "lastName": "User"
      },
      "url": "http://localhost:30023/api/v1/user"
    },
    "status": "error",
    "errorThrown": "Bad Request"
  }
```
with the error message (see screenshot) `Attempt to load null ObjectId: None`.

**Comment by brianhelba** [comment]
`web_client_jobs.jobs` may be client-side. I'll take a look.

**Comment by zachmullen** [comment]
Hm, that does look strange, I'll check into the autojoin test.

**Comment by zachmullen** [comment]
The autojoin test failure is a result of a client-side race condition, combined with poor validation of the setting on the server side that makes the error message unhelpful.

**Comment by sutartmelson** [comment]
I'm still getting this on #2091 
I rebased after the #2094 fix

**Comment by zachmullen** [comment]
Yeah, @brianhelba is currently fixing the jobs test, so that's expected. If you see the autojoin test still failing, that would be unexpected.

**Comment by manthey** [comment]
I haven't seen these tests flake out in quite a while, so I'm closing this issue.
