### ISSUE TITLE
Add a token model method to require token scope

### ISSUE THREAD

**Issue by msmolens** [girder/girder#2117]
Calling [`ensureTokenScope`](https://github.com/girder/girder/blob/637ab0e919bc355cbcb63a827eaabb8073c94408/girder/api/rest.py#L1026) always allows user auth tokens. Endpoint implementations that want to require a token scope need to do something like:
````
if not self.model('token').hasScope(token, scope):
    raise AccessException('Invalid token scopes: ...')
````
See discussion: https://github.com/girder/girder/pull/2098#discussion_r122524023

**Comment by dorukozturk** [comment]
@msmolens I have a PR that has a fix for this. See https://github.com/girder/girder/pull/2031/files#diff-18db8a6ce4005eba88078edf38f66280R135
