### ISSUE TITLE
Create docker-compose to bring up local hdfs cluster for testing assetstore.

### ISSUE THREAD

**Issue by kotfic** [girder/girder#2121]
There are several repo's we can look too for inspiration: 

https://bitbucket.org/uhopper/hadoop-docker
https://github.com/bigdatafoundation/docker-hadoop
https://github.com/big-data-europe/docker-hadoop

In particular this will be nice because once you have data-nodes set up you can scale them easily: 

```sh
docker-compose scale datanode=5
```

@zachmullen @mgrauer

**Comment by manthey** [comment]
No longer relevant.
