### ISSUE TITLE
Redefining sys.stdout breaks readline

### ISSUE THREAD

**Issue by danlamanna** [girder/girder#2131]
When spawning a repl using the `code` module, using arrow keys for history outputs control characters due to [this line](https://github.com/girder/girder/blob/656e421c8b11f1318ac7198403616e587c0563e7/girder/__init__.py#L206) in our logging setup.

To reproduce from a python shell:
```
import girder, code
code.interact()
# try using up/down arrows
```

Leave out `import girder` to see the arrow keys functioning correctly.

**Comment by zachmullen** [comment]
Is there an easy fix?

**Comment by danlamanna** [comment]
Interestingly enough, `IPython.embed` figures things out, though I didn't want to assume the user has IPython installed. This is for a small helper I wrote here: https://github.com/girder/girder/blob/989f2625d409a0ede9eb97250dafb56af47cd8ac/girder/utility/shell.py

**Comment by zachmullen** [comment]
Maybe we could defer/condition the standard pipe redirection so that it just doesn't happen in a REPL setting. For instance, we could do it during the server startup.

**Comment by danlamanna** [comment]
> Maybe we could defer/condition the standard pipe redirection so that it just doesn't happen in a REPL setting. For instance, we could do it during the server startup.

The issue is that we want to start the server up for the REPL so we can access different things we do at runtime, namely the syspath hacking to access our plugins.

I'm not fully familiar with exactly how/why we're redefining stdout/stderr, but I'm worried it might just be a bit brittle.

**Comment by zachmullen** [comment]
Paging @manthey re: https://github.com/girder/girder/commit/2e9d6f7c0d8241c5822d63ea4f138cffac8c6d6f

**Comment by manthey** [comment]
Looking in to this, Python's readline does a comparison with actual stdout at a pretty deep level, so I'm not sure how to fix this AND maintain logging all stdout/stderr.  We could just invoke the stream redirection when the server is starting, but we want to do that as soon as possible so as to not miss any output.

I'll post a PR.
