### ISSUE TITLE
Add various improvements in Ansible files

### ISSUE THREAD

**Issue by danlamanna** [girder/girder#2207]
- [x] Use YAML syntax (`:` instead of `=`)
- [x] Look into Ansible linting
- [ ] More thoroughly make use of `{{ ansible_managed }}`
- [ ] Make use of `changed_when` where applicable
- [ ] Determine when to use `no_log` when dealing with credentialed tasks
- [ ] Thoroughly exercise and test idempotence of all playbooks/modules (filesystem assetstore)

**Comment by manthey** [comment]
Closing, as we are no longer publish ansible playbooks since #3488.
