### ISSUE TITLE
API keys should be shown only once

### ISSUE THREAD

**Issue by mathstuf** [girder/girder#2221]
API keys should be displayed upon creation and then never shown again.

Cc: @danlamanna

**Comment by ronichoudhury** [comment]
Can you explain the reasoning behind this statement? In case I need to do something like transcribe an API key into some other service (e.g., Travis), should I create a new key for that purpose?

**Comment by mathstuf** [comment]
Cc: @zackgalbreath

**Comment by brianhelba** [comment]
For now, I'd oppose adding this functionality. API keys are still an under-utilized feature of Girder, and our goal should be to push people away from authenticating `girder_client`, etc. with username / password and make API keys as easy as possible to use. IMO, the positive security benefits from using API keys at all far outweigh the benefits from forcing people to create new API keys every time they fail to locally save an old key.

**Comment by zachmullen** [comment]
I agree with Brian on this one -- unless we have users/customers asking for this feature, I don't think it adds enough value to be worth implementing right now.

**Comment by mathstuf** [comment]
The ability of Girder to do this means that the API keys are stored in the plain on the server. API keys are basically passwords, so why do we store them unencrypted?

**Comment by zachmullen** [comment]
API keys are not like user passwords, where a user might use the same password for dozens of different services, and compromising it could compromise other sites. They're ad hoc for the Girder instance.

It's worth mentioning that, e.g. AWS, although it only shows you the secret once, also must store it in plaintext in order to perform HMAC.

**Comment by zachmullen** [comment]
(Also the same reason that when using SSH, your private key lives in a persistent file that you can look at as many times as you want.)

**Comment by zachmullen** [comment]
Closing for now... someone can reopen if there is a customer need for this feature.
