### ISSUE TITLE
Organize web client files by component, not file type

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#2239]
Rather than have `templates`, `stylesheets`, `views/body`, `views/layout`, and `views/widgets` directories, web client files should be grouped into directories on a per-component basis. All JS view files, Stylus files, and Pug files for a common component should reside in the same directory.

Models, collections, and utilities would likely stay in separate directories, as they presently are.

**Comment by mgrauer** [comment]
We will pursue this policy in Girder Web Components.
