### ISSUE TITLE
Allow the "contact" link to point to a different email

### ISSUE THREAD

**Issue by mgrauer** [girder/girder#2266]
The Contact [link](https://github.com/girder/girder/blob/f445dca9b4f95c77374b335c04e717d102d9dbc6/clients/web/src/templates/layout/layoutFooter.pug#L3) on the web client currently goes to "kitware@kitware.com".  I need to make this configurable, so a particular deployment can point elsewhere.

**Comment by danlamanna** [comment]
Related #1093.

**Comment by mgrauer** [comment]
I'm in support of doing all of #1093, it would be good to batch up with this work.

**Comment by mgrauer** [comment]
@brianhelba @zachmullen I'd like @Pierre-Assemat to start on this one next if possible--can you and any others provide guidance on this specific issue?  Let's tackle this one and see how it goes before expanding to include #1093.

**Comment by Pierre-Assemat** [comment]
Do you think it has to be set by a configuration file or directly change inside the browser maybe in adding a setting tool ?

**Comment by brianhelba** [comment]
We already have a system setting `Email from address`:
![screenshot](https://user-images.githubusercontent.com/1282879/29140867-0b910650-7d1a-11e7-835b-bbee4c5ee043.png)
which controls the email address used for outgoing server-sent emails.

@mgrauer Would be sufficient to generalize this setting into something like `Instance email address`, and use it for both the `From: ` address on outgoing emails, and the `mailto: ` address that's listed on the front page footer?

**Comment by zachmullen** [comment]
> use it for both the From: address on outgoing emails, and the mailto: address that's listed on the front page footer?

I don't think so -- the "from" value will often be a no-reply value, whereas the mailto address obviously needs to be a real account that can receive messages.

**Comment by mgrauer** [comment]
I'd like to suggest this as a starting point:

 * Add a new system setting for contact email, defaulting to kitware@kitware.com
 * Add an admin console for setting this contact email, in a separate UI container from current ones
 * Web client gets this system setting by contacting the server
 * Web client populates the contact link with this value

This has the advantage that a Girder site admin can change this value through the admin console, and the front end doesn't need to be rebuilt upon a change.  It has the downside of adding an additional REST call upon first rendering, though that particular call is fairly cheap.

**Comment by brianhelba** [comment]
@zachmullen I'm fine with adding a new setting in general, but I'm not totally understanding the use case where an instance is configured with a live SMTP relay such that it can send emails, but the site admin isn't able to set up an email address to service support requests. Do we want to support instances that are sending lots of emails to users, but with no way to reply back to the maintainers (i.e. where the reply address is a `no-reply@...`? Do we want *end users* (as distinct from sysadmins or plugin developers) of an instance to send emails to kitware@kitware.com for support on instances that are installed by third parties? This smells to me like a default setting value that may have outlived its usefulness.

@mgrauer I don't think we need an Ajax call to get the initial value, we can just inline it into `webroot.mako`. I've already discussed this approach with @Pierre-Assemat .

@danlamanna  Note, inlining settings into `webroot.mako` will have implications on the ability to use a strict Content Security Policy applied by a proxy server. However the more robust and usable solution may be to move the setting of a CSP into the Girder server itself.

**Comment by danlamanna** [comment]
> @danlamanna Note, inlining settings into `webroot.mako` will have
> implications on the ability to use a strict Content Security Policy
> applied by a proxy server.

How would that happen? Are you talking about inlining this as a
javascript variable? In that case, it would break. I would assume by
inlining you would mean doing so in a manner similar to
"g-global-info-apiroot".

> However the more robust and usable solution may be to move the setting
> of a CSP into the Girder server itself.

I've generally tried to avoid putting too many deployment details into
the Girder administration panel if possible.
