### ISSUE TITLE
Validate email addresses

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#2282]
Email addresses are used in 3 different ways:

* Every user account has an email address that's associated with it. These are validated using the [`email_regex` config option](https://github.com/girder/girder/blob/d99f46c11367f8253d4a9cc66c8f87a56f754423/girder/models/user.py#L98) before being saved. These are not transformed before being used for outgoing mails or included in a web page.

* The `EMAIL_FROM_ADDRESS` setting is set by site admins, and is [used to send outgoing emails](https://github.com/girder/girder/blob/d99f46c11367f8253d4a9cc66c8f87a56f754423/girder/utility/mail_utils.py#L112) This is [not validated (except to ensure it's not empty)](https://github.com/girder/girder/blob/d99f46c11367f8253d4a9cc66c8f87a56f754423/girder/models/setting.py#L277) before being saved. This is not transformed before being used for outgoing mails or included in web pages.

* The `CONTACT_EMAIL_ADDRESS` setting is set by site admins, and is used to display "Contact" hyperlinks, for users to contact the instance admins for support. This is not validated (except to ensure it's not empty) before being saved. This is not transformed before being used for outgoing mails or included in web pages.

---

Since all of these are fundamentally an email address, they should be validated in the same way, likely using [a robust regex](https://html.spec.whatwg.org/multipage/input.html#valid-e-mail-address). The `email_regex` config option should be removed, as whether an email address is valid should not vary from instance to instance. Allowing selective registration to only users from a certain email domain is a separate problem, and should probably be handled by a normal instance setting within a plugin, possibly [the `autojoin` plugin](https://github.com/girder/girder/tree/d99f46c11367f8253d4a9cc66c8f87a56f754423/plugins/autojoin).

Additionally, email addresses often need to be transformed or encoded before being used or rendered on a webpage. Because this transformation is typically not idempotent, it should be done just-in-time before rendering, rather than in the setting validator. Accordingly:
* Anything in a `mailto: ` link should be encoded per [RFC6068](https://tools.ietf.org/html/rfc6068)
* Other HTML-embedded links probably need to be encoded per [RFC5322](https://tools.ietf.org/html/rfc5322).
* Encoding of addresses into MIME headers should also be considered

**Comment by danlamanna** [comment]
> The `email_regex` config option should be removed, as whether an email
> address is valid should not vary from instance-to-instance.

+1. Our current email_regex looks to be a bit buggy, addresses like
"@foo.bar" pass without issue.

**Comment by zachmullen** [comment]
> The email_regex config option should be removed, as whether an email address is valid should not vary from instance to instance.

I think the original motivation for this was to be able to easily restrict registration to a specific mail domain e.g. `@kitware.com`, however that feature doesn't belong in the config file anyway, so I agree. It was a very early feature and nobody uses it to my knowledge.

**Comment by brianhelba** [comment]
> Allowing selective registration to only users from a certain email domain is a separate problem, and should probably be handled by a normal instance setting within a plugin, possibly [the `autojoin` plugin](https://github.com/girder/girder/tree/d99f46c11367f8253d4a9cc66c8f87a56f754423/plugins/autojoin).

@zachmullen Do you think this feature is useful enough to file a bug to implement it properly?

**Comment by zachmullen** [comment]
Up to you.
