### ISSUE TITLE
Add python3-dev to packages to install in prerequisites

### ISSUE THREAD

**Issue by jeffbaumes** [girder/girder#2286]
This seems to be needed if it is a Python 3 installation.

**Comment by brianhelba** [comment]
I'll incorporate into https://github.com/girder/girder/pull/2222

**Comment by brianhelba** [comment]
After further discussion with @danlamanna , it may be cleanest to first wait for Python 3 to be supported by all built-in plugins (to prevent new users from seeing 'broken' plugins on Python 3) and also wait for Ubuntu 18.04 to be properly supported by MongoDB and other external dependencies. At that point, we can drop quickstart support for Ubuntu 14.04, add quickstart support for 18.04, and update the quickstart guide to use Python 3 for both 16.04 and 18.04 (RHEL 7 will still use Python 2).

**Comment by manthey** [comment]
Outdated.
