### ISSUE TITLE
Remove requirements.txt files from builtin plugins

### ISSUE THREAD

**Issue by jeffbaumes** [girder/girder#2287]
Currently in the plugins folder:

```
find . | grep requirements.txt
./hdfs_assetstore/requirements.txt
./dicom_viewer/requirements.txt
./celery_jobs/requirements.txt
./thumbnails/requirements.txt
./metadata_extractor/requirements.txt
./geospatial/requirements.txt`
```

Instead, `pip install girder[plugin-name]` should be the true way to install plugin dependencies, via the `setup.py` for the plugin, at least for all builtin plugins.

**Comment by zachmullen** [comment]
`find ./plugins | grep requirements.txt | xargs git rm`

**Comment by jeffbaumes** [comment]
@zachmullen yes :) Before doing this, we should be sure no plugins depend on having these files, that we are not making some deploy modes break.

**Comment by danlamanna** [comment]
pip-installable plugins removed these.
