### ISSUE TITLE
Remove girder_client.HttpError

### ISSUE THREAD

**Issue by danlamanna** [girder/girder#2290]
For more context, see https://github.com/girder/girder/pull/2223.

In particular:
> In girder_client 3.0, change the thrown exceptions to be requests.HttpError (or better yet, remove entirely some places that these are explicitly thrown, allowing exceptions to bubble up from requests via things like raise_for_status).

**Comment by jeffbaumes** [comment]
@danlamanna does this seem feasible for 3.0? I've assigned it to you.

**Comment by mgrauer** [comment]
We are closing this, the changes would be better suited to a complete restart of the Girder Python client/CLI.
