### ISSUE TITLE
Installing Girder from PyPI doesn't allow girder-install web --dev

### ISSUE THREAD

**Issue by danlamanna** [girder/girder#2303]
The `--dev` flag can't be used when installing Girder from PyPi since it tries to use `testEnv.pug` which is excluded from our MANIFEST.in file.

Sidebar: Maybe we should have a packaging label?

**Comment by zachmullen** [comment]
If we don't want to support the full `--dev` features in packaged installations, we should at least expose a flag that allows building source maps.

**Comment by danlamanna** [comment]
This is fixed in Girder 3.
