### ISSUE TITLE
Guard against plugin webpack errors

### ISSUE THREAD

**Issue by manthey** [girder/girder#2316]
If a plugin's `webpack.helper.js` script throws an error, none of the plugins will build.  At the very least, there should be a guard around where `webpackHelper` function is executed.  The offending plugin should probably be marked failing in some manner so that it can't be enabled.

The guard is straightforward:
```
try {
    var newConfig = webpackHelper(baseConfig, helperConfig);
} catch (err) {
    grunt.log.error(`Failed to run webpack helper for ${plugin}: ${err.message}`);
    return;
}
```

I'm not sure how to disable the plugin in this case.

**Comment by jbeezley** [comment]
The bigger problem is that you also need to disable anything that depends on the broken plugin.  The dependency resolution happens in python, so there isn't a clear path to figure that out.  Maybe just logging the error as done in your code block as a hint to the developer is enough?
