### ISSUE TITLE
Separate common/unique DICOM metadata from file and store them into the item   

### ISSUE THREAD

**Issue by Pierre-Assemat** [girder/girder#2319]
We need to change the way DICOM metadata are stored into each file to move the common metadata under a special key like :
`item['dicomMeta'] = {
  'commonKey': 'commonValue',
  ...
}`

And the same with unique metadata, which could be a list of each data :
`item['dicomFiles'] = [
  {
    'fileId': ObjectId(...),
    'meta': {
      'uniqueKey: 'uniqueValue',
      ...
    }
  },
  ...
]`

**Comment by Pierre-Assemat** [comment]
Fixes : #2320

**Comment by zachmullen** [comment]
I think we should approach this design iteratively. In the first pass, let's not store the `dicomFiles` key at all, since there is concern about the size of that document, and its utility is still unclear.

Also, since the common tags are necessarily a superset of all the tags on any given item, in this first pass I think we should just naively dump the entire set of tags on a *single* file into the item dictionary. It's unclear what having strictly the common set of elements really gains us in terms of search-related functionality -- if we're assuming users will be searching only by "common" tags anyway, having the additional file-specific tags in that list (as an undocumented side-effect that may go away in the future) will not cause any problems.

**Comment by brianhelba** [comment]
I think it's reasonable to not store `dicomFiles` for right now.

However, I don't think we should go so far as to arbitrarily pick the first file / slice and use that as the sole source of metadata. We don't just use metadata for searching: we also display it in a table. To "contaminate" this table with slice-specific metadata would make it more difficult to distinguish the generally-more-important common metadata from the generally-less-important slice-specific metadata.

So, at this point, we should have each "DICOM item" contain just the field:
```
item['dicomMeta'] = {
    'commonKey': 'commonValue', ... 
}
```

It can be set and updated efficiently by the following algorithm (in pseudo-code):
```
def removeUniqueMetadata(commonMetadata, newMetadata):
    """
    Remove (in-place) any elements from commonMetadata that
    do not overlap with newMetadata.
    """
    TODO: implement this

def makeDicomItem(item):
    """
    Try to convert an existing item into a "DICOM item", which contains a
    "dicomMeta" field with DICOM metadata that is common to all DICOM files.
    """
    files = filter(isDicomFile, Item.childFiles(item))
    if not files:
        return
    item['dicomMeta'] = extractDicomMetadata(file[0])
    for additionalFile in files[1:]:
        additionalFileMetadata = extractDicomMetadata(additionalFile)
        removeUniqueMetadata(item['dicomMeta'], additionalFileMetadata)
    item = Item.save(item)

def onAdditionalFileUploadedToDicomItem(event):
    """
    Whenever an additional file is uploaded to a "DICOM item", will remove any
    DICOM metadata that is no longer common to all DICOM files in the item.
    """
    item = event.info['item']
    additionalFile = event.info['file']
    if not isDicomFile(additionalFile):
        return
    additionalFileMetadata = extractDicomMetadata(additionalFile)
    removeUniqueMetadata(item['dicomMeta'], additionalFileMetadata)
    item = Item.save(item)
```

@manthey @zachmullen  What do you think?

**Comment by zachmullen** [comment]
I'm fine with that, though we won't be able to use `itemModel.save` since this is running asynchronously and multiple files could be uploaded to the item simultaneously. We'll need to use atomic updates instead.

**Comment by brianhelba** [comment]
@zachmullen Agreed, and we'll need to `$unset` each of the removed fields specifically, not `$set` the `dicomMeta` field as a whole. This may necessitate that we refactor my pseudocode a bit, if we want to keep it unit testable.
