### ISSUE TITLE
Uploading thousands of items into single folder slows down over time

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#2333]
When uploading a few thousand items (user claimed it was noticeable with 1000 items) into a single parent folder as a normal user, the process starts out very quickly but then begins to slow down. The first items complete in a matter of milliseconds, but by the thousandth item it was taking seconds per item. The items reportedly do not have name collisions, and the backing assetstore is the local filesystem.

**Comment by sutartmelson** [comment]
Was the upload done on the web or python client?

**Comment by zachmullen** [comment]
Python client

**Comment by zachmullen** [comment]
Do you have your test script for the python client somewhere? I'd like to try and reproduce it myself, too.

**Comment by sutartmelson** [comment]
``` python
import girder_client

for i in range(3000):
    filename = 'file' + str(i) + '.txt'
    f = open(filename, 'w')
    f.write(filename)
    f.close()

c = girder_client.GirderClient(apiUrl='http://localhost:8080/api/v1')
c.authenticate('', '')
id = ''
path = '.'
c.upload(path, id)
```

**Comment by zachmullen** [comment]
thanks

**Comment by manthey** [comment]
We were unable to reproduce and now have users who have been using 100,000 plus files without reporting this.
