### ISSUE TITLE
Add system/shutdown endpoint and event

### ISSUE THREAD

**Issue by manthey** [girder/girder#2349]
We should have a PUT `system/shutdown` endpoint, much like the `system/restart` endpoint.

Further, both of these should emit an event so that plugins can listen for them and release resources or do other clean up if appropriate.  We can hook into the rest event (`rest.put.system.restart.before`), but since any plugin could elect to cancel this event, it might not be appropriate to perform shutdown actions.  cherrypy might emit a usable event, but a grider-specific event would be more appropriate.

**Comment by danlamanna** [comment]
I think Girder can emit an event when shutting down if we want, but I don't think we should add more endpoints that control the state of the girder process. With the coming PR to remove server restart I think it makes sense to close this, but I'll leave it open in case anyone disagrees.
