### ISSUE TITLE
Girder 3.0 RFC: "Name" instead of first and last names

### ISSUE THREAD

**Issue by jeffbaumes** [girder/girder#2351]
New logins would just have a "name" field and UI would just use this - all uses of first and last name fields would be removed from the UI/server. For a natural upgrade from 2.0, the first time a user record is encountered without a "name" field, create one as "${first} ${last}" and save to the database.

**Comment by zachmullen** [comment]
This is not a comprehensive list, just some thoughts:

Pros:

* We don't have to worry about supporting all the forms of names across cultures
* Simpler registration form

Cons:

* Can no longer sort by last name
* Cannot separate first and last names, so we couldn't e.g. address a user by just their first name

**Comment by jeffbaumes** [comment]
@girder/developers Last call: it is looking like this will be removed from the 3.0 milestone.

**Comment by manthey** [comment]
Outdated.
