### ISSUE TITLE
JSONEditor popup bug

### ISSUE THREAD

**Issue by sutartmelson** [girder/girder#2358]
When editing metdata, if you switch the jsoneditor to `Code` the text pop up remains. If you swtch back to `Tree` another pop up remains. I'm not yet sure if this is an issue with the JSONEditor package or girder web. 
![screenshot](https://user-images.githubusercontent.com/7495148/30823404-0af6df26-a1fa-11e7-8b12-2ee9b9cc23d4.png)

**Comment by zachmullen** [comment]
@sutartmelson did this present only after #2295 was merged?

**Comment by sutartmelson** [comment]
@zachmullen I'm almost positive it wasn't there immediately after #2284, but I haven't checked since then. So I'll look into it.

**Comment by zachmullen** [comment]
@brianhelba I verified that this issue appeared as a result of #2295 -- prior to that, the button just had a native tooltip, and the browser cleaned that up when the element changed.

**Comment by sutartmelson** [comment]
@zachmullen @brianhelba Yes, it appears #2295 introduced this bug.
