### ISSUE TITLE
Move packaging for pypi/npm to CI

### ISSUE THREAD

**Issue by danlamanna** [girder/girder#2365]
This is good for producing packages from a pristine-ish environment, and will ultimately be less burdensome if we end up creating packages for each core plugin.

Additionally this will allow us to take advantage of the various pre-release type features mentioned in #974.

**Comment by jcfr** [comment]
👍 

For python package, here is an example of tests checking that source and binary distributions can be installed.

Also, nightly (aka development) packaged can also be uploaded into a Github release named `latest`. The use of [publish-github-release-py add-on](http://scikit-ci-addons.readthedocs.io/en/latest/addons.html#publish-github-release-py) is convenient for that.

**Comment by danlamanna** [comment]
This tool could be useful for testing the scripting associated with automated releases on PyPI: https://packaging.python.org/guides/using-testpypi/.

**Comment by jbeezley** [comment]
The pypi portion of this is done by #2956.
