### ISSUE TITLE
Remove importlib guesswork behavior from ModelImporter

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#2377]
Require models to use the new explicit registration behavior for those who need to look them up using strings.

**Comment by mgrauer** [comment]
@zachmullen Can you provide a code example of what the current behavior is and the desired?

**Comment by jeffbaumes** [comment]
@zachmullen looks like we just need to make a PR that removes fallback code. I'm assigning it to you for the 3.0 milestone.

**Comment by jbeezley** [comment]
FWIW, it's already [removed for plugins](https://github.com/girder/girder/blob/master/girder/utility/model_importer.py#L90).
