### ISSUE TITLE
Retire old/unsupported plugins

### ISSUE THREAD

**Issue by mgrauer** [girder/girder#2385]
We'll need to decide which ones of the built-in plugins should be removed as part of the Girder 3.0 release.

**Comment by danlamanna** [comment]
Current candidates for removal are:
- celery_jobs
- metadata extractor
- geospatial
- Mongo search
- Vega
- Item preview

@girder/developers should chime in on any built in plugins they're using or know are being used from the list and plan migration paths or remove them from the list.

**Comment by brianhelba** [comment]
I'd add `jquery_widgets`  to the list.

**Comment by zachmullen** [comment]
I know we have downstreams actively using geospatial, as well as metadata extractor. So for those two, at least, we should migrate them out of built-in status but keep them around under the girder org and only maintain them when the need arises.

**Comment by jcfr** [comment]
👍 

Can we add a section in the doc (http://girder.readthedocs.io/en/latest/plugins.html) mentioning when each plugin was removed and which girder core functionality could be used as a replacement ...

**Comment by danlamanna** [comment]
Updated list:

- celery_jobs
- jquery_widgets
- metadata extractor (to be migrated out of core)
- geospatial (to be migrated out of core)
- Mongo search
- Vega
- Item preview

**Comment by manthey** [comment]
The vega plugin was updated recently, so perhaps it shouldn't be removed.

**Comment by brianhelba** [comment]
Should we perhaps move `vega` out of core instead? Having a plugin which only activates when the magic `vega` metadata field is set seems pretty niche, and the actual code / logic within the plugin is extremely minimal (it just serves to inject Vega elements into the item page).

**Comment by jcfr** [comment]
To extract commit history, you could look at what was done in https://github.com/Slicer/SlicerLegacyModules#how-to-extract-module-history-from-slicer-and-include-it-in-this-extension-

**Comment by waxlamp** [comment]
We could instead detect that a given JSON file is in fact a Vega spec,
which can be done by examining the `$schema` top-level field. The magic
field could instead be used to disable visualizing a particular Vega spec.

**Comment by mgrauer** [comment]
Also in the discussion: be more explicit about what plugins we want to include and why, any categories (experimental, blessed), what decision framework to use to decide this (funding, interest, sprawl of features). Possibly add these flags to the python package metadata.

**Comment by jeffbaumes** [comment]
@danlamanna can we consider this closed?

**Comment by jeffbaumes** [comment]
I'll reverse the question: @girder/developers does anyone else have an outstanding plugin that should be slated for removal? Otherwise I'll close.

**Comment by danlamanna** [comment]
I think this can be closed, I can't remember why past me reopened it.

As a result of our initial discussion, it seems there should be a follow up about potentially promoting certain plugins to being built in to Girder.
