### ISSUE TITLE
Require $/jQuery import explicitly rather than using ProvidePlugin

### ISSUE THREAD

**Issue by mgrauer** [girder/girder#2390]
at least remove from build system rules

**Comment by jbeezley** [comment]
I think all of the instances of relying on the `ProvidePlugin` have been removed from girder's source; however, it is still necessary for shimming certain jquery plugins.  We could either:
1. Scope the `ProvidePlugin` configuration to apply only to those jquery plugins that require it.
2. Use the [imports-loader](https://github.com/webpack-contrib/imports-loader) to inject the jquery object into these plugins.

Either way, this change is best implemented along with the webpack config changes in #2552.

**Comment by zachmullen** [comment]
Should we close this then? It's going to become moot in 3.x with the new web client anyway since we won't be using jQuery at all.

**Comment by zachmullen** [comment]
Vue-Moot
