### ISSUE TITLE
Using the REST API to get the list of Folders and Items failed if we don't pass an Id or an text for searching

### ISSUE THREAD

**Issue by Pierre-Assemat** [girder/girder#2396]
Trying to get the list of folders and items by the REST API respond as bad request : 

![screenshot from 2017-10-10 13-11-03](https://user-images.githubusercontent.com/29961430/31400159-99f9a884-adbc-11e7-9072-ecdc750503fc.png)
 
The response is the same for the route : `http://localhost:8079/api/v1/item?limit=50&sort=lowerName&sortdir=1`

Do you have any thoughts  @girder/developers ?

**Comment by zachmullen** [comment]
That endpoint requires you to pass either a folderId or text field. If you don't pass either, it doesn't know what to do. If you want, we can add a `notes` to the description that says as much.

**Comment by Pierre-Assemat** [comment]
Yeah I just saw that in the function `find`

**Comment by Pierre-Assemat** [comment]
I think it's clear in the code, maybe not enough in the REST API, I don't know

**Comment by zachmullen** [comment]
Let's go ahead and add the `notes` field to the description.
