### ISSUE TITLE
Pass resource name to Resource subclass constructors

### ISSUE THREAD

**Issue by mgrauer** [girder/girder#2400]
Pass resource name (or potentially a full path) to Resource subclasses in their constructors, rather than hardcoding them in the classes. Also make it so we can mount subsets of the REST API under their own prefixes.

**Comment by cjh1** [comment]
This is related to #2395 which used the mount point to determine the prefix, thus allowing APIs to have their own prefixes.

**Comment by mgrauer** [comment]
@cjh1 I was transcribing this issue from a document, and I believe the issue came from a discussion between you and @zachmullen . Does #2395 get you both what you need, or do have further needs that could be specified here?

**Comment by cjh1** [comment]
#2395 gets me what I need if others are happy with it. It also details a breaking change that I would like to added for Girder 3.

**Comment by jeffbaumes** [comment]
@cjh1 if this issue is for the further breaking change described in #2395, it appears you are the champion for it. If you are still interested in pursuing this for 3.0, please provide details for a plan for getting this done over the coming weeks.

**Comment by cjh1** [comment]
@jeffbaumes Sorry I missed that comment, I will take a look.

**Comment by cjh1** [comment]
@jeffbaumes After looking at this again, I think we can closed this off with no change. #2395 has given me what I need and the depreciation of ```resourceName``` is probably not worth the effort.

**Comment by jeffbaumes** [comment]
Thanks for looking at this @cjh1. Closing now.
