### ISSUE TITLE
Track which plugins were explicitly enabled

### ISSUE THREAD

**Issue by manthey** [girder/girder#2434]
Currently, when a user turns on a plugin that requires other plugins, all of those plugins are turned on as well.  If the user then turns off the first plugin, none of the others are turned off.  It would be better if plugins that were only on because of requirements were so marked so that they could be disabled when the requiring plugin is disabled.

plugins that are on because of a dependency should disable the on-off slider or change it (always on)-(on when required).  As part of this, such plugins could list what plugin(s) required them to be on as a tool tip or in some other way.  The UI experience of not being able to turn off something and having no explanation of why is poor.

**Comment by danlamanna** [comment]
@brianhelba Can this be closed now?

**Comment by brianhelba** [comment]
Issue is now obsolete.
