### ISSUE TITLE
GirderClient should always have a session object

### ISSUE THREAD

**Issue by mgrauer** [girder/girder#2436]
Follow on work from #2433.

GirderClient would always have a session object present that we could manipulate, that way this flag would just require setting ctx.obj.session.verify = False.

It would also be good to clearly specify the API surface of the GirderClient as part of this work, see #2433 for discussion.

**Comment by jeffbaumes** [comment]
@danlamanna I'm assigning this to you for now. Is this feasible for 3.0?

**Comment by danlamanna** [comment]
Yes!

**Comment by mgrauer** [comment]
We are closing this, the changes would be better suited to a complete restart of the Girder Python client/CLI.
