### ISSUE TITLE
/system/version endpoint should not depend on the web client build for Git info

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#2448]
Presently, [the `/system/version` endpoint)[https://github.com/girder/girder/blob/7235f8fbff8bddaec17d779be40d0dd2660038e6/girder/api/v1/system.py#L173] depends on the `VERSION` constant (getting set from the `girder-version.json` file)[https://github.com/girder/girder/blob/7235f8fbff8bddaec17d779be40d0dd2660038e6/girder/constants.py#L53], as an import-time side effect. Since the  `girder-version.json` file [is created by Grunt during the web client build process](https://github.com/girder/girder/blob/7235f8fbff8bddaec17d779be40d0dd2660038e6/grunt_tasks/version.js#L45), the `/system/version` endpoint does not return the correct version info if the web client was not built.

Since the Git version and the API functionality have no reason to depend on the (optional) web client, this dependency should be removed.

**Comment by danlamanna** [comment]
ref #1933, #1931

**Comment by brianhelba** [comment]
Closing as a duplicate of #1933 .
