### ISSUE TITLE
Make it harder to delete collections

### ISSUE THREAD

**Issue by manthey** [girder/girder#2469]
We've had a request to make it harder to delete collections.  A user thought they were deleting a file and accidentally deleted a large collection when clicked the confirmation dialog.  They recommend something like Github uses where you must type the name of the collection to confirm deleting it -- something like "Please type 'DELETE <collection name>' and click the Delete button to confirm deleting the collection".

Perhaps this should also apply to deleting users.

**Comment by zachmullen** [comment]
+1

**Comment by mgrauer** [comment]
I'm quite sympathetic to this because I once deleted a folder with 200 G in subfolders--so this case (folder) still wouldn't be covered, but Collection seems like the right level to avoid annoying the user with confirmations for every delete request.

Perhaps as part of the deletion confirmation, we could say "you want to delete a User/Collection with X folders and Y bytes" so they can see the consequences--though we may have that info easily at hand.

**Comment by manthey** [comment]
At the peril of making things complicated, we could have a number-of-things and size-of-data threshold when deleting folders to engage the harder-to-delete method.

**Comment by kotfic** [comment]
+1 for thresholds

**Comment by Pierre-Assemat** [comment]
Just to have some clarification, the idea is to make sure the user know what is doing?
- This is limited only to Collection? or others models like folder, or user too?
- Do you think only a message with size-of-data or number of element is sufficient? 
- Or do we need an user interaction like enter a message ('delete', or 'yes'...)?

**Comment by danlamanna** [comment]
> At the peril of making things complicated, we could have a
> number-of-things and size-of-data threshold when deleting folders to
> engage the harder-to-delete method.

Length of time the collection has been around could be another useful
metric.

**Comment by manthey** [comment]
I think that initially this just applies to collections, but should be made so it can be reused when we decide where else we want it.  I *think* we'll also want it for users.  I imagine that the delete confirmation would become a dialog, sort of like this:


![image](https://user-images.githubusercontent.com/8781639/32629676-ffc434f0-c567-11e7-9de1-4d483badd0dd.png)

**Comment by Pierre-Assemat** [comment]
Ok so let start on a dialog box reusable, maybe by specifying the type (folder, user, collection...)
I will make a PR soon with the first prototype.

**Comment by mgrauer** [comment]
This sounds like a good approach to me. The only concern I'd have is if the collection has a long name or maybe a name that isn't easy to type on a certain keyboard, that could be a pain. Minor quibble.

How about requiring Users to type "DELETE". 

or "DELETE Junk" in the general case would work 😜

**Comment by manthey** [comment]
Cut and pasting the name works for tedious names -- the main thing is that it is a more conscious action than just clicking Delete.

**Comment by danlamanna** [comment]
Another potential use case for this in the future could be deleting API Keys.

**Comment by Pierre-Assemat** [comment]
And if the message to enter was the user identifier, or a password ?

**Comment by ronichoudhury** [comment]
I've always liked Google's method where the action happens but is
undo-able. I know supporting an undo for deletions is much more difficult
than a confirmation dialog but it's a nice UX feature that makes things
easier on the customer, and something to consider.
