### ISSUE TITLE
Evaluate alternative Ansible roles for MongoDB

### ISSUE THREAD

**Issue by danlamanna** [girder/girder#2472]
The solution in the past has been to use https://github.com/Stouts/Stouts.mongodb, which is almost completely unmaintained at this point.

Requirements for an upstream role:
- Support Ubuntu 14/16
- Support CentOS 7
- Allow specifying custom configuration options without templating
- Ideally is available on Ansible Galaxy

We should compile a list of any other features we deem necessary, and then evaluate any roles we can find against them. Unfortunately I think creating our own role here may be the only way forward.

Here's a couple of random search results:
- https://github.com/lesmyrmidons/ansible-role-mongodb
  This one seems to have some changes from the unmaintained Stouts role.
- https://github.com/UnderGreen/ansible-role-mongodb 

cc: @brianhelba @cjh1 I know you've both had concerns/maybe rolled your own versions of this role in the past.

**Comment by cjh1** [comment]
I tend to agree with @danlamanna we may have to create our own, all the ones I have evaluated in the past have their own problems.

**Comment by brianhelba** [comment]
Resolved: https://github.com/girder/ansible-role-girder-mongodb
