### ISSUE TITLE
OPTIONS request for urls with parameters fails with 405 (CherryPy == 11.1.0)

### ISSUE THREAD

**Issue by Xarthisius** [girder/girder#2475]
It's not exactly related with Girder per se, nevertheless I'm opening this issue since it's affecting Girder.

With `CherryPy == 11.1.0` following request:

```
curl -X OPTIONS 'http://localhost:8080/api/v1/folder?sort=created&sortdir=1&text=foo'
```

yields

```
<h2>405 Method Not Allowed</h2>
<p>Specified method is invalid for this resource.</p>
<p><i>Powered by <a href="https://girder.readthedocs.io">Girder</a></i></p>
```

even though:

```
$ curl -I 'http://localhost:8080/api/v1/folder?sort=created&sortdir=1&text=foo'
HTTP/1.1 200 OK
Date: Fri, 10 Nov 2017 19:26:33 GMT
Content-Length: 2
Content-Type: application/json
Allow: DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT
Server: Girder 2.4.0
```
Downgrading to `CherryPy==11.0.0` "fixes" the issue:

**Comment by Xarthisius** [comment]
Git bisect on CherryPy, shows this commit: https://github.com/cherrypy/cherrypy/commit/c87bc9f73740dfe35e4d2ca9082dccb6278bdc53 as a culprit

**Comment by manthey** [comment]
This is https://github.com/cherrypy/cherrypy/issues/1662.
