### ISSUE TITLE
item_tasks client test is locale dependent

### ISSUE THREAD

**Issue by manthey** [girder/girder#2482]
The item_tasks client tasks test is locale dependent, and fails when the tests are run in the C locale instead of the en.UTF-8 locale.

We expect names to be sorted alphabetically, which means that, in e.UTF-8, they are in the order 'item-tasks-demo', 'me/my_image', 'PET phantom...', but in the C locale this changes to 'PET phantom...', 'item-tasks-demo', 'me/my_image'.  To make the test more robust, we either need to (a) make sure that they sort correctly regardless of locale (e.g., change "PET phantom..." to "pet phantom..."), (b) change the client test to find the correct item in the list and not insist on a strict position, (c) force mongo to use a specific locale (but that requires Mongo >= 3.4).

**Comment by danlamanna** [comment]
Is running the test suite in a different locale as simple as specifying
LANG=C ctest ... ? Was this the only test that failed out of our test
suite?

**Comment by manthey** [comment]
Yes, that is all that is required to run in another locale, and, yes, this was the only test that failed.

I encountered this on @brianhelba's provisional circle-ci version 2 branch in their environment (for Python 3, though I don't think that is relevant).  There, I *can't* just change the locale via LANG=en.UTF-8, as they don't have the English locale installed.

**Comment by manthey** [comment]
I've fixed the test in PR #2483 via method (b).
