### ISSUE TITLE
Python client can't ignore SSL warnings, or use self-signed certificate

### ISSUE THREAD

**Issue by venabled** [girder/girder#2484]
The Python CLI interface supports both ignoring SSL verification, and using user-provided certs, but the core library does not. 

I've been able to work around by creating a `requests.Session` object with my desired configuration and setting `GirderClient._session` to that instance, not sure if you'd take a PR with some additional functionality to support it.

**Comment by danlamanna** [comment]
Thanks for the issue! The `GirderClient` is getting a few changes in Girder 3 to ensure it follows conventions of the `requests` library more closely. In particular, a `Session` object will always be exposed to the user for direct use/manipulation (see #2436). I believe this will directly solve the problems you're seeing.

In the meantime, note that the session object can also be customized without directly modifying `GirderClient._session` like so:

```
gc = GirderClient(...)
session = requests.Session()
session.verify = False

with gc.session(session):
    gc.downloadFile(...)
```
The [GirderClient.session](https://github.com/girder/girder/blob/d8c05f18067ee6decabf282449e5628e3c006fce/clients/python/girder_client/__init__.py#L264) docs have a little bit more on that.

**Comment by venabled** [comment]
Thanks for the response, the workaround seems to be working, should I close this for now?

**Comment by mgrauer** [comment]
I'll go ahead and close this because we have this issue tracked as part of the Girder 3.0 milestone.

Thanks again for your report.
