### ISSUE TITLE
Add a cookiecutter template for Girder plugins

### ISSUE THREAD

**Issue by danlamanna** [girder/girder#2503]
Related #2128

**Comment by zachmullen** [comment]
Not a breaking change but we want it to be available for 3.0.

**Comment by zachmullen** [comment]
We have a user request for this feature from discourse: https://discourse.girder.org/t/is-there-a-cookiecutter-for-plugins-v3/179

**Comment by jbeezley** [comment]
See https://github.com/jbeezley/cookiecutter-girder-plugin (should be moved to `girder/cookiecutter-girder-plugin`) for basic implementation.  It can be tested with:
```
cookiecutter gh:jbeezley/cookiecutter-girder-plugin
```
