### ISSUE TITLE
Officially drop support for Python3 <3.5 and MongoDB <3.2

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#2516]
Officially drop support for Python3 <3.5 (but keeping Python 2.7), because:
* It's the [minimum version supported by Ansible](https://docs.ansible.com/ansible/2.4/dev_guide/developing_python3.html#minimum-version-of-python-3-x-and-python-2-x) (and Ansible will fail on Python <=3.4)
* Girder is not able to fully test Python 3.4, as the CircleCI machine environment requires Ansible to provision itself
* It's the [default Python on the current Ubuntu LTS (16.04)](https://packages.ubuntu.com/zesty/python3)
  * Ubuntu 14.04 ships with Python 2.7 as the default interpreter, which Girder will continue to support
* It's installable on nearly any platform [via `pyenv`](https://github.com/pyenv/pyenv)

Also, officially drop support for MongoDB <3.2 because:
* MongoDB 2.7 dropped [support on October 2016](https://www.mongodb.com/support-policy)
* MongoDB 3.2 contains [a number of desirable features](https://docs.mongodb.com/v3.2/release-notes/3.2/) that are not available in 3.0:
  * WiredTiger storage engine enabled by default
  * The `$lookup` (aka JOIN) aggregation stage (which will be critical if Girder is ever going to do scalable access filtering in-database)
  * Indexes on aggregation stages
  * Improved support for case-insensitive search (allowing Girder to eventually drop `lowerName`)

If this moves forward, we'll update the Girder documentation and test environment to use these versions as their minimums. No other changes should be necessary.

**Comment by zachmullen** [comment]
I'm fine with pulling the trigger on the mongo part, in particular I'd like to make all of our CI testing use the ramdisk mongo configuration, which requires dropping 2.x from testing.

As for python 3.4, I dislike the idea of dropping support for intermediate python versions... do we know why ansible doesn't support it?

**Comment by manthey** [comment]
Ansible says: "Python-3.5 was chosen as a minimum because it is the earliest Python-3 version adopted as the default Python by a Long Term Support (LTS) Linux distribution (in this case, Ubuntu-16.04)." https://docs.ansible.com/ansible/2.4/dev_guide/developing_python3.html

**Comment by zachmullen** [comment]
Ok, seems reasonable. I'm fine with both proposals.

**Comment by mgrauer** [comment]
I'm ok with this. Do we need to update any Ansible or Docker for the Mongo change?

@brianhelba Have you started using features that are Mongo >= 3.2 only?

**Comment by brianhelba** [comment]
I use features that are 3.4-only and 3.6 only in downstream plugins, where I have a lot of aggregation pipelines.

However, for just core Girder, I think the features that I enumerated above provide an important set of functionally that ought to always be accessible and which core could start to leverage now.

**Comment by manthey** [comment]
I think we should leave this issue up a "while" so that potential external users could have a chance to chime in (or at least see this before it happens).  I know that we have had external users as recently as six months ago still on Mongo 2.6, even though they were using the latest Girder.

Having said that, I look forward to dropping Mongo 2.6.

**Comment by hugovk** [comment]
Here's the pip installs for girder from PyPI for the last month (via `pypinfo --percent --pip girder pyversion`), very little for Python 3.0-3.4:

| python_version | percent | download_count |
| -------------- | ------- | -------------- |
| 2.7            |   68.5% |            102 |
| 3.5            |   25.5% |             38 |
| 3.6            |    5.4% |              8 |
| 3.4            |    0.7% |              1 |

**Comment by mgrauer** [comment]
Thanks @hugovk . It's nice to be able to make a data driven decision, especially for a data management platform!

🏆
