### ISSUE TITLE
Decide on one format for reporting JS coverage to Codecov

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#2539]
Depending on the file format that coverage information is serialized as, Codecov reports subtly different results. We should settle on using one format, that expresses coverage in a way that's most useful to us as developers.

Istanbul can support [the following coverage formats](https://github.com/istanbuljs/istanbuljs/tree/master/packages/istanbul-reports/lib). Codecov can support at least [the following coverage formats](https://docs.codecov.io/v4.3.0/reference#section-acceptable-report-formats).

For reference, here are Codecov outputs for:
* [The status quo (Lcov and Cobertura)](https://codecov.io/gh/girder/girder/tree/accf0a2497b074f6edd36123b2e58f29820a00ec/clients/web/src)
* [Lcov](https://codecov.io/gh/girder/girder/tree/f3ee9d8c4e9139edbf8fee6b1d30fb474fe7418a/clients/web/src)
* [Cobertura](https://codecov.io/gh/girder/girder/tree/3c4bed8c9c250a61407ec8983d72d5e2c2485749/clients/web/src)
* [Istanbul JSON](https://codecov.io/gh/girder/girder/tree/528357af82a0e71a46a3a8c3c73faa87189166cb/clients/web/src)
* [Clover XML](https://codecov.io/gh/girder/girder/tree/5ae2736a1310eeccf497a731a18b246aa596144f/clients/web/src)

**Comment by brianhelba** [comment]
I think the two finalists here are Cobertura and Clover XML, as both can express partial line hits (i.e. branch coverage), however there are differences between the two as to when they count a line as partially vs. fully covered and whether function definitions count as LOC.

@manthey @jbeezley @girder/developers Can you PTAL at these two example outputs and render an opinion as to which you think is the most useful to end developers?

I think it's worth spending a little time on this, as we may re-use the results of this decision when deciding how to setup JS coverage reporting in other projects too.

**Comment by jbeezley** [comment]
Another useful tool is the native html reports.  We don't store these reports as artifacts in the circle 2 workflows (any reason why?).  The last circle 1 run I could find is [here](https://4144-11854950-gh.circle-artifacts.com/2/tmp/circle-artifacts.8MsAhz2/coverage/js/index.html).  This report is clearly far more granular as it reports 84% statement coverage.  I tend to look at the native report when evaluating the code I write myself as boiling it all down to a single number is clearly misrepresentative.

I would be fine with any of the options for the codecov reporting.  I do think we should upload only a single format.

**Comment by manthey** [comment]
The differences between Cobertura and Clover are peculiar.  I like the Cobertura reporting on branch coverage a little better, and since Cobertura is including function definitions, it will appear as a less profound drop in coverage.  Clover supposedly gives a little more information, but browsing our code, I don't see any useful difference.  I'm not passionate about one versus the other.

**Comment by brianhelba** [comment]
@jbeezley Yes, storing the native HTML JS coverage reports with CircleCI should happen as a small part of these changes. It's more technically awkward than I wanted, which is why it isn't already happening (like it is for Python).

**Comment by brianhelba** [comment]
@manthey Looking at Cobertura vs Clover reports on Codecov in more detail, I think Cobertura handles partial coverage in an objectively more sane way. For that reason alone, I'm also voting to go with Cobertura.
