### ISSUE TITLE
When Description.produces is set to a binary type, Swagger does not show errors

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#2553]
Setting
```
@describeRoute(
    Description()
    .produces('image/png')
)
```
on a `Resource` route causes Swagger to not show 400 errors from the endpoint.

**Comment by manthey** [comment]
Changing this would require a change to swagger-ui (perhaps just upgrading would solve the problem).  If `produces` is not set it defaults to `application/json`.  If `application/json` is included 400 errors are shown, but non-json results aren't rendered properly (even if they are included in the list of `produces`).

**Comment by brianhelba** [comment]
@manthey Agreed.

**Comment by manthey** [comment]
We upgraded the swagger UI.  If this is still a problem, let's open a new issue.
