### ISSUE TITLE
Removing `router.navigate()` calls from event handlers for links that have `href` properties results in obscure buggy behavior

### ISSUE THREAD

**Issue by ronichoudhury** [girder/girder#2558]
Though removing the `router.navigate()` calls seems to works for human-driven testing (i.e., the UI behaves as it ought to), the testing fails in obscure ways. The automated tests that do things like click on a link to the homepage after opening the admin console will time out. Unclear why this is happening.

This issue was revealed during development of #2489.

**Comment by manthey** [comment]
I think we have explained the behavior (and fixed some links to use the right elements, too).  If anyone disagrees, please reopne.
