### ISSUE TITLE
Swagger UI generates corrupted zip file

### ISSUE THREAD

**Issue by matthewma7** [girder/girder#2561]
As we know, when an item has multiple files, the item/download will produce a zip file. However, using the download link provided in the Swagger UI will produce a corrupted zip file. 
@manthey found out it is because there are extra bytes for UTF-8 being inserted into the file between chunks.

**Comment by manthey** [comment]
The data we emit from Girder is correct.  Swagger buffers the responses as a blob and offers a link to get that blob.  It is the blob that has extra UTF-8 BOM markers injected into it.  Surprisingly, the extra bytes are not aligned with the chunks we emit from the zip generation.  This is a swagger/browser issues, so we'll either need an extra setting for swagger or some other solution.

**Comment by manthey** [comment]
See https://github.com/swagger-api/swagger-ui/issues/1605
