### ISSUE TITLE
Adding issue and pull request templates

### ISSUE THREAD

**Issue by dorukozturk** [girder/girder#2568]
Adding issue and pull request templates can be good for standardizing issues and pull requests which might make the reviewers part slightly easier. 

We can put checkboxes like other projects so that the author knows what the reviewer might look for ([example](https://github.com/tox-dev/tox/blob/master/.github/PULL_REQUEST_TEMPLATE.md)).

If makes sense I can do the first pass on this.

**Comment by danlamanna** [comment]
We're making use of PR templates for the merge window. I'm closing this, feel free to reopen if someone wants to make an issue template.
