### ISSUE TITLE
Unify Docker images for Python 2 and 3

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#2580]
The Dockerfiles for Python 2 and Python 3 versions of Girder are nearly identical, and it would be easier to maintain if there was only one Dockerfile. This would also make it simpler and lower-risk for downstreams to use Girder's Docker image, as there'd be simply one image, which provided both Python 2 and 3 within it.

This would grow the image size by a few MB, as both development headers and Pip versions would need to be installed, but the current images is 700MB overall already.

The one challenge would be that we'd have to pick a default version of Python to use for the built-in entrypoint/command. Users wanting the non-default version would have to include the optional `<COMMAND>` parameter in their `docker run` invocation.

**Comment by brianhelba** [comment]
For maximum compatibility, perhaps it'd be best to make Python 2.7 be the default version of the `latest` and release images. This way, existing users of the Python 2 image would not have any risk of breakage. Users of the `latest-py3` would be expected to switch to `latest` and update their `docker run` invocation in order to continue getting the latest builds.

@cjh1 Would this be acceptable to your usage?

**Comment by cjh1** [comment]
@brianhelba Yes, I could update things accordingly. 

Reducing the image size is something I would like see, #2403, is the image size increase really only a few MB?

**Comment by kotfic** [comment]
Personally i'd like to see the ```latest-py3``` tag stick around,  but i don't see why the Dockerfile.py3 couldn't be significantly reduced in size,  E.g.
```
FROM girder/girder:latest

ENTRYPOINT ["python3", "-m", "girder"]
```

Unless that effects the version it will automatically build from on dockerhub (i.e.  if girder/girder:latest-py3 builds before girder/girder:latest)?

**Comment by xkortex** [comment]
You can only alias `pip` to pip2 or pip3, depending on the last executable ran against `get-pip.py`
```
RUN wget https://bootstrap.pypa.io/get-pip.py && python3 get-pip.py
```

So unfortunately you cannot just change the entrypoint to get a python3 girder runtime. 

IMHO, you should switch the default to py3 and make py2 the legacy, sooner rather than later. [Py2 End of Life](https://pythonclock.org/) is in less than 5 months. ;)

**Comment by manthey** [comment]
Outdated.
