### ISSUE TITLE
Static root should be set at Webpack build time

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#2590]
Webpack needs to know the URL prefix to where static content is served, in order for `file-loader`, etc. to resolve included assets to a JS URL string.

Since the `staticRoot` is currently allowed to be set dynamically, it must be set at JS load time by assigning a value to `__webpack_public_path__`. Ideally, this could be assigned in a JS file which was included only from Girder's Webpack entry point file, but not in Girder's npm-published JS library.

However, due to the use of Webpack's `Dll*Plugin`, and the fact that  `__webpack_public_path__` is scoped to individual Webpack bundles, `__webpack_public_path__` is currently being [set within `rest.js`](https://github.com/girder/girder/blob/master/clients/web/src/rest.js#L57). This causes several problems:
* plugins still don't work with imported assets (this is just never noticed because none of Girder' current built-in plugins robustly use imported assets)
* external consumers of the Girder JS library are stuck with code assigning to `__webpack_public_path__`, which is a syntax error under any other build system

The best solution here is probably to make `staticRoot` (and hence Webpack's `publicPath`) set at JS build time. This should also correspond to moving `staticRoot` out of the database as a runtime-configurable setting, and in to the `girder.config.*` file as a deploy-time-configurable setting.

**Comment by brianhelba** [comment]
@girder/developers Who is currently setting `staticRoot` to something else in their deployments? How about `apiRoot`?

This is going to require a breaking change. I don't know whether we'll need to do it under Girder 3, or just call it a bugfix and do it sooner. Either way, I'd like to better understand the actual use cases around this feature (setting `staticRoot` and `apiRoot`).

**Comment by zachmullen** [comment]
[This used to be a config file setting](https://github.com/girder/girder/blob/1.x-maintenance/girder/conf/girder.dist.cfg#L22) but was changed as part of the route table feature. Not sure whether anyone is actually depending on a dynamic route for the static content, but I am in favor of removing it.

**Comment by brianhelba** [comment]
Removing it entirely, or moving it back to the config? I'm advocating the latter.

**Comment by zachmullen** [comment]
Moving it back to the config file (sorry for the ambiguous language)

**Comment by manthey** [comment]
If/when changes are made, we should add some explicit tests for proxy environments where the external url is not the same as the internal url.

**Comment by danlamanna** [comment]
@brianhelba Is this still relevant now?

**Comment by brianhelba** [comment]
This has been fixed.
