### ISSUE TITLE
Add a sanity check to detect early if name of a plugin repo is correct

### ISSUE THREAD

**Issue by Pierre-Assemat** [girder/girder#2603]
That will permit to avoid big change and error while building the web client for external girder plugins

**Comment by mgrauer** [comment]
e.g., currently if a plugin has a `-` in the name, the error message from the build is a bit cryptic:

>`ERROR in plugin.min.js from UglifyJs
Unexpected token: operator (-) [plugin.min.js:1,24]`

**Comment by manthey** [comment]
This could probably just be `name.isidentifier() and not keyword.iskeyword(name)`, except that `isidentifier` is a Python 3 function.  [python_future](http://python-future.org/_modules/future/utils.html) shows that this can be handled as `re.match(r'[a-zA-Z_][a-zA-Z0-9_]*$', name)`.

**Comment by mgrauer** [comment]
@Pierre-Assemat This would be a good one for you to fix--and that way you are helping your past self!

⏳

**Comment by danlamanna** [comment]
Is this issue still relevant?

**Comment by zachmullen** [comment]
Doubt it. Someone can reopen if it is.
