### ISSUE TITLE
girder-client API docs not building on RTD

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#2604]
They are supposed to be in [this section](http://girder.readthedocs.io/en/latest/python-client.html#further-examples-and-function-level-documentation), but it's blank.

@brianhelba as part of your recent fixes to get our RTD docs building properly, did you notice this issue?

**Comment by brianhelba** [comment]
#2577 should fix this. I'll try to finish that up soon.

**Comment by danlamanna** [comment]
#2577 fixed this.
