### ISSUE TITLE
RFC: Support for convenience targets in a top-level Makefile

### ISSUE THREAD

**Issue by jcfr** [girder/girder#2650]
### motivation

To streamline the developer experience, in python projects I maintained, I conveniently support command like these ones:

```
$ make
make [target]

  targets:
    clean       - remove build and testing artifacts
    lint        - check style with flake8
    test        - run tests quickly with the default Python
    test-all    - run tests on every Python version with tox
    coverage    - check code coverage quickly with the default Python
    docs-only   - generate Sphinx HTML documentation, including API docs
    docs        - same as 'docs-only' and load HTML using default web browser
    release     - package and upload a release
    dist        - package
```

This help as it provides a consistent interface to all the projects I maintained.

### is it a common practice ? 

It is also a common practice, you will find a `Makefile` in a lot of projects:

* https://github.com/pandas-dev/pandas/blob/master/Makefile

* https://github.com/search?q=clean-pyc&type=Code&utf8=%E2%9C%93

* https://krzysztofzuraw.com/blog/2016/makefiles-in-python-projects.html

* https://github.com/Nekroze/cookiecutter-pypackage/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/Makefile

* https://github.com/audreyr/cookiecutter-pypackage/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/Makefile

### what prompted this issue ? 

Following the improvement to the documentation system done in #2577 , we can now generate the girder documentation using "standard" python approach (somewhat expected with a python project):

```
tox -e docs
```

It would be nice to support top-level target like `docs` and `docs-only`

```
    docs-only   - generate Sphinx HTML documentation, including API docs
    docs        - same as 'docs-only' and load HTML using default web browser
```

### what about windows ?

If support for windows is wanted, we would instead have a `build.ninja` file, and have `ninja` package as a dev requirements.

But I would stick with the "established practice" ... the `Makefile` is a short text file that can help streamline dev.

**Comment by danlamanna** [comment]
We're moving this type of functionality towards tox in the future, and that is already the case with documentation and publishing releases.
