### ISSUE TITLE
No longer possible to restart a single step of a CI build

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#2658]
See for example: https://circleci.com/gh/girder/girder/8919

The cache restore step fails. Is there anything we can do in our CircleCI config to support this?

**Comment by brianhelba** [comment]
The `Attaching Workspace (skipped)` step is where the problem actually is. That step is showing:
> Warning: skipping this step: Missing workflow workspace identifiers, this step must be run in the context of a workflow.

Accordingly, the build filesystem is not getting attached and subsequent build steps fail.

This seems like a bug in CircleCI, but how exactly are you restarting the single step? I believe there are a few different ways to do it, and I'm curious whether all of them fail to attach the workspace.

**Comment by zachmullen** [comment]
I was hitting rerun from the build list.

**Comment by brianhelba** [comment]
There are a few different ways to restart builds, and it's possible that what you're choosing may be causing the build to execute outside a workflow context. If we can get precise steps to reproduce this, it sounds like a reportable bug in CircleCI.
