### ISSUE TITLE
Move FUSE binding lifecycle management outside girder server process

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#2687]
ping @girder/developers please outline the technical plan in comments.

**Comment by manthey** [comment]
@aashish24 Doing this is a much better solution to using mapnik with FUSE than forking to process mapnik tiles.

**Comment by manthey** [comment]
The bulk of the Girder fuse plugin becomes `girder/cli/mount.py`.  In think the remaining functionality in Girder should move to core (not in a plugin that requires enabling).  This functionality extends `File().getLocalFilePath()` and adds a `getFuseFilePath` method (currently accessed via the fuse plugin namespace).  This latter function I would propose adding to the `File()` model.

The actual creation of the mount command is easy -- handling the tests will take the bulk of the effort.

**Comment by aashish24** [comment]
> @aashish24 Doing this is a much better solution to using mapnik with FUSE than forking to process mapnik tiles.

thanks, this looks like a cleaner approach.

**Comment by manthey** [comment]
Resolved by #2691.
