### ISSUE TITLE
ansible role doesn't work with ansible 2.5

### ISSUE THREAD

**Issue by manthey** [girder/girder#2690]
Ansible 2.5 introduced a bug (https://github.com/ansible/ansible/issues/37912).  There is a PR in ansible which should eventually fix it (https://github.com/ansible/ansible/pull/37973), but until then you can't install Girder outside of a virtualenv.

**Comment by kotfic** [comment]
See also: https://github.com/ansible/ansible/pull/40129

**Comment by manthey** [comment]
Outdated.
