### ISSUE TITLE
User API no longer supports revoking site admin privileges

### ISSUE THREAD

**Issue by msmolens** [girder/girder#2719]
The `PUT /user/{id}` endpoint, which updates a user's information, no longer supports revoking site admin privileges by setting the `admin` parameter to `False`:
https://github.com/girder/girder/blob/f53e907c653e4a4c59b5dc6850401d4c978987c9/girder/api/v1/user.py#L238-L242

This behavior changed in https://github.com/girder/girder/commit/1a0fa0a71bf0cfa1c19ee2c05bdbb9dad6cdb8b8.

**Comment by zachmullen** [comment]
Good catch, do you want me to fix this or are you planning to?
