### ISSUE TITLE
GDPR support

### ISSUE THREAD

**Issue by satra** [girder/girder#2722]
i think girder is well placed to provide GDPR compliance. has anybody in the team worked on it/working on it?

from a different forum, but has some relevant pieces: https://meta.discourse.org/t/gdpr-countdown-and-compliance/87190/77

**Comment by mgrauer** [comment]
Thanks @satra , we are indeed thinking about this. I found this to be a great article to calm irritated nerves around [GDPR Hysteria](https://jacquesmattheij.com/gdpr-hysteria). I am not trying to imply in any way that we aren't taking this seriously, just that we should move thoughtfully here, and not panic.

**Comment by mgrauer** [comment]
As a starting point, we could add another link in the footer that says `Privacy Notice`, and allow the site admin to set that link target in the Girder Admin settings.

**Comment by satra** [comment]
@mgrauer - indeed i like that article. and the privacy notice sounds good.

regarding a few simple steps, i think:
- privacy notice link
- creating hashed audit trails, ip logs
- providing a clear delete my account button
would all be relatively straightforward

and future: export my data + import my data would round up the features necessary i think.

**Comment by mgrauer** [comment]
I'm not sure yet what hashed audit trails are, I haven't come across those yet in my GDPR reading--can you describe what this is? We do have an [audit trail feature](https://github.com/girder/girder/pull/2702) currently pending, I doubt we'd want to expand the scope of that, but it could be something to build on.

The problem with ip logs is that it is also a deployment concern and not just a Girder application concern--we do log ips it seems in the Girder info logs, but these will also be logged in nginx that we set up through Ansible and potentially other deployment types (Docker?).

There is a delete my account button, but it isn't visible from the account page (when you go to the `my account` dropdown under your logged in username), rather you have to look up your user in the Users list. Perhaps that should be made visible from both places?

<img width="1073" alt="screen shot 2018-05-25 at 5 36 31 pm" src="https://user-images.githubusercontent.com/595023/40567392-0e169cde-6043-11e8-82d3-5e4dc9253db7.png">

Export my data + import my data could get tricky with shared and copied data, and what counts as personal data or not. This one sounds complicated!

**Comment by manthey** [comment]
Done in #2728.
