### ISSUE TITLE
autoDescribeRoute doesn't support required header parameters

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#2724]
The logic for `autoDescribeRoute` does not support required header parameters. Attempting to add a `.param` with both `paramType='header'` and `required=True` causes the route to always return a 400 error with the message `Parameter "..." is required.`.

**Comment by zachmullen** [comment]
In fact, we don't treat parameters passed in headers in the same way as parameters passed in the query string or body, i.e. they are not passed to the wrapped function as a parameter, nor transformed by any of the arguments to `param()`; you just have to read them manually via `cherrypy.request.headers`.

We can either

1. Start treating these as normal parameters and subject them to all the same behavior as other `param()`s passed via `autoDescribeRoute`.

or

2. Allow them to be documented in swagger, but do not do any of the normal `param()` transformation and validation behavior.

Option 1 seems better, and as long as we don't remove the value from the request headers, I don't think it will break existing usage. @brianhelba what would you prefer for your case?

**Comment by brianhelba** [comment]
I'd be fine with 2 if it's faster for now, as it would unblock the errors I'm encountering in #2655. However, I agree that 1 would be more consistent with the value that `autoDescribeRoute` provides, so I'd be happy to see it eventually.

**Comment by zachmullen** [comment]
I mean, the truly quick fix would be just not to document the parameter in your `Description` -- not desirable, of course, since it won't be usable via swagger, but unless that's a hard requirement then it may be OK temporarily.

**Comment by brianhelba** [comment]
In some cases, the header is mandatory, so I'd rather not render Swagger unusable in those cases. I'm fine to wait for some sort of fix to this issue, if it's possible to address soon.

**Comment by zachmullen** [comment]
I'll implement option 1, just wanting to make sure no one objected to it.
