### ISSUE TITLE
POST /api_key/token sends a Set-Cookie with the token

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#2749]
@girder/developers @Purg this isn't necessarily a bug, but I wanted to open this up for discussion. Paul ran into some confusing behavior when he accidentally logged in as someone else using a found API key via the swagger UI, which happened because we set the cookie in the response headers from the token creation endpoint in the same way that we would during a normal login.

This feature was added for the sake of consistency, and to facilitate clients that may for some reason want to use cookie-based access, but I don't know of any reason why a client *would* want to do that.

Your thoughts? Bug or feature?

**Comment by brianhelba** [comment]
I'd call it a feature. A number of CLI / script interfaces have the capability to persist cookie data, and the cookie may be the best place to store the token value in some cases.

From a purity standpoint, I think we should strive to treat all tokens the same way, regardless of how they were issued. In this case, it seems consistent that getting a token (whether via password login or API key presentation) should always set a cookie with the new token. Of course, clarifying this in documentation (probably the endpoint description) would probably be helpful.

I don't feel incredibly strong about this, so I'd be happy to hear other perspectives.

**Comment by zachmullen** [comment]
I'm also leaning toward feature. I'll close this, if there's someone who dissents, feel free to reopen.
