### ISSUE TITLE
Upload.uploadFromFile returns incorrectly when passed an empty file

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#2773]
When passed an empty (`size==0`), [`Upload.uploadFromFile`](https://github.com/girder/girder/blob/master/girder/models/upload.py#L55) does not create a `File`, and instead returns an `Upload` object.

The correct behavior is for a `File` object (with an empty file) to be created and returned.

This bug is due to the fact that [`Upload.handleChunk`](https://github.com/girder/girder/blob/master/girder/models/upload.py#L108) is never called.

**Comment by brianhelba** [comment]
In my opinion, the design of `Upload.handleChunk`, whereby it sometimes returns a `File` and sometimes returns an `Upload`, is the real bug. This sort of variable return typing is dangerous (especially since both types are just a simple Python `dict`) and makes callers more prone to experiencing bugs (as in this case).

**Comment by brianhelba** [comment]
@girder/developers Is anyone able to fix this before the 3.0 release?

**Comment by zachmullen** [comment]
Seems like this should be a really quick fix. I can take a look.
