### ISSUE TITLE
TableView plugin unable to render csv file

### ISSUE THREAD

**Issue by qwilka** [girder/girder#2792]
With reference to issue #2791
I am unable to render this (or any other) csv file with the TableView plugin previewer:
> width [mm], height [mm]
100,200

All I see is a spinner and the message "Loading..."

The problem appears to be occurring on this line https://github.com/girder/girder/blob/9b8bfd54aeba75fe1fe6a15a8762d7e226fe1c73/plugins/table_view/web_client/views/TableWidget.js#L68
I have added some print-outs to loader.loader() (and also a «catch» to get the rejected promise):
```
        console.log("*** updateData.tableParser: ", parser);
        loader.loader().load(this.file.downloadUrl()).then((data) => {
            console.log("*** updateData.loader().load: ", data);
            data = loader.read(data, {type: parser, parse: 'auto'});
            console.log("*** after loader().load: ", data);
            this.data = data;
            this.columns = _.keys(data[0]);
            this.state = this.states.DATA_READY;
            this.render();
            return data;
        }).catch( (error) => {
            console.error("loader.catch:", error);
            this.state = this.states.DATA_ERROR;
            this.render();
            return null;
        });
```

That gives me this in the browser:

![2018-09-10-223815_1276x743_scrot](https://user-images.githubusercontent.com/37806070/45326667-6ddad500-b54c-11e8-97ad-fd0fa9186f8c.png)

**Comment by manthey** [comment]
On my version of Girder master, I don't see this problem.  Are you using the master branch or a previous version?

**Comment by qwilka** [comment]
I'm using the 2.5.0 released version of Girder
https://github.com/girder/girder/tree/v2.5.0
TableView in this version uses datalib, and works most of the time for me, except for this issue #2791 

TableView plugin is taken from the current repository version master branch ("Switch from datalib to vega-loader")
https://github.com/girder/girder/tree/master/plugins/table_view
https://github.com/girder/girder/commit/0b56df4ae1d77b81b2469c15654bf1c22d4f6a85

**Comment by qwilka** [comment]
I have just updated the Jobs, Vega and a bunch of other plugins, and re-built Girder. That seems to have resolved the CSV load and preview issue I was experiencing, thanks @manthey, I guess I can proceed to close this issue out. 
It does however point to a bigger issue about whether plugin builds should be independent of each other?
Also, there is still an issue in the current TableView code concerning catching the rejected promise in vega-loader:  
https://github.com/girder/girder/blob/12cc5a756db3839c9d233ee24381c8641afacea2/plugins/table_view/web_client/views/TableWidget.js#L67
https://github.com/vega/vega-loader#load
