### ISSUE TITLE
Coverage is broken

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#2794]
Not sure if this is a codecov issue or a local issue, but it seems likely that it's local.

**Comment by manthey** [comment]
I see that the coverage file sent to codecov on on a successful coverage branch from late August was [600kb](https://circleci.com/gh/girder/girder/12853), whereas a recent submission from the same step was only [450kb](https://circleci.com/gh/girder/girder/13190).

**Comment by manthey** [comment]
In the circleci environment, the last working coverage used pytest 3.7.3 and pytest-cov 2.5.1.  The broken coverage has pytest 3.8.0 and pytest-cov 2.6.0.  A crude test of pinning pytest <3.8 and pytest-cov <2.6 makes coverage work again.

**Comment by zachmullen** [comment]
Good to know, at least we can pin those temporarily until we can sort out what's really wrong.

**Comment by manthey** [comment]
I see that working versions store coverage in a file called something like `girder/build/test/coverage/python_temp/.coverage.692a993cea2b.3978.292632`, whereas the newer version store coverage in `girder/build/test/coverage/python_temp/.coverage`.

**Comment by manthey** [comment]
I'll check if we have to pin pytest (I assume we have to pin pytest-cov).  Pinning both definitely works.

**Comment by manthey** [comment]
Outdated.
