### ISSUE TITLE
Girder library is incompatible with nodejs

### ISSUE THREAD

**Issue by luistelmocosta** [girder/girder#2838]
Hello, I’ve been trying to run this framework but when importing to standard nodejs server, I keep getting “Unexpected identifier” errors. I tried to transpile the module but Babel-loader ignores the Girder folder. 
Question 1: How are you running the client?
Question 2: Is there anyway to import Girder to nodejs using ES6? 
Kind regards

**Comment by zachmullen** [comment]
Which library do you mean? The only Girder javascript libraries I know of are meant to be run in the web browser, they won't work in node. If you're looking for a programmatic client to run in node, I'm afraid I do not know of any, though it would be great if you want to write one!
