### ISSUE TITLE
Remove ModelImporter as base class to Model and Resource

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#2851]
I've added this to the release milestone as it is a follow up to #2377 and #2845 

We could expand this to @jbeezley 's stronger suggestion of removing the ModelImporter class altogether, but at a minimum we should consider removing it as a mixin to other core classes.

**Comment by jeffbaumes** [comment]
@zachmullen, @jbeezley would someone be willing to assign this to themselves?
