### ISSUE TITLE
Support for multiple CORS domains.

### ISSUE THREAD

**Issue by subdavis** [girder/girder#2905]
The use case for this change is described in girder/girder_web_components#58

In summary, the fix from #639 only applies in cases where an exact origin matches for the `Access-Control-Allow-Origin` domain.

The following are not currently possible.

* multiple distinct domains should match, such as `https://example1.com https://example2.com`
* or all domains should be allowed CORS features, but only a small whitelist should allow CORS-based cookie setting, such as `* https://example1.com` .

[This stackoverflow question](https://stackoverflow.com/questions/1653308/access-control-allow-origin-multiple-origin-domains) describes a popular way of handling this issue.

## Solution 1: respond with CORS iff it's in the whitelist.

Given the whitelist includes `['*', 'https://example1.com']`,

* Request from `https://example2.com` would get `Access-Control-Allow-Origin: *`
* Request from `https://example1.com` would get `Access-Control-Allow-Origin: https://example1.com`

This would not change the security model for girder.  Origins not on the explicit whitelist like example2.com would continue to have use of CORS features, but could not use cookies.

## Solution 2: Query string authentication 

The goal is to allow girder to set the `girderToken` cookie, which browser will only do when the CORS domain matches.  This cookie is needed to load resource on the page: `<img>` and `<video>` because we can't explicitly send the token header when loading a resource from the DOM.

If the token were able to be set in the query string: `/resource/download?token=<girdertoken>` a cookie would not be needed.

I don't think this solution is as good as the first because it doesn't allow for pages with hard-coded resource paths.

**Comment by zachmullen** [comment]
Excellent write up, I am in favor of the 1st solution

**Comment by jbeezley** [comment]
Solution 1 sounds fine to me.

FWIW, by default [Flask-CORS](https://flask-cors.corydolphin.com/en/latest/api.html) replaces wildcards with the request's `Origin` header.  This would be an alternative, but less secure, solution.

**Comment by zachmullen** [comment]
Is anyone assigned to this? I can take this on if not

**Comment by subdavis** [comment]
@zachmullen I wouldn't mind giving this a try.  I probably won't be able to look at it until tomorrow or Monday.

I've been wanting to get more familiar with Girder, so this might be a good opportunity for that.  That said, I'm also not terribly attached to this particular issue.

**Comment by zachmullen** [comment]
It was very quick to create a candidate solution (ae4a27c). I'll add tests to verify correctness.
