### ISSUE TITLE
Wrong Velodyne Pcap data

### ISSUE THREAD

**Issue by Francisobiagwu** [girder/girder#2939]
Hello,
I am running some experiment on the sample Velodyne VLP-16 pcap data provided. So I found out that the data provided is for 32 lasers not for VLP-16 as described.  Please can you verify this problem and get back to me.

https://data.kitware.com/#collection/5b7f46f98d777f06857cb206/folder/5b7fff608d777f06857cb539

**Comment by zachmullen** [comment]
Hi @Francisobiagwu , please email the paraview mailing list, as they are the maintainers of this dataset. Thanks for letting us know.
