### ISSUE TITLE
"girder build" is failing to set static root

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#2952]
Following #2948, running `girder build` gives stdout looking like:
```bash
$ girder build 
...
> @girder/meta-build@ build /home/ubuntu/.venvs/girder/lib/python2.7/site-packages/girder/web_client
> grunt "--static-path=/home/ubuntu/.venvs/girder/share/girder/static" "--static-url=None" "--no-progress=false" "--env=prod"
```
and Webpack actually emits files with internal URL references like `None/built/assets/open-sans-latin-300-521d17bc.woff`

This is on a deployment (with a running database, installed `girder`, etc.) where `girder build` was working properly prior to pulling in #2948.

**Comment by brianhelba** [comment]
As one possible resolution, there is the approach from #2893, which removes `staticRoot` entirely.

@girder/developers Is anyone aware of a case where anyone has ever changed this setting in a production environment?

**Comment by zachmullen** [comment]
This is a bug resulting from syntactic associativity. It should have read

```python
'--static-url=%s' % (static_root or getStaticRoot())
```
