### ISSUE TITLE
Bug: girderToken cookie takes precedence over Girder-Token header when both are set

### ISSUE THREAD

**Issue by based64god** [girder/girder#2966]
Exactly what the title says. This is pretty easy to reproduce with a couple `curl`s.
Steps to reproduce:

1.  Retrieve your girder api key. Set `GIRDER_API_KEY` equal to it in your shell. 
2. Find a file you want to download. Grab the download url. Set `DOWNLOAD_URL` equal to it.
3. Run the following script.
```
GIRDER_TOKEN1=$(curl -sSL -X POST "https://data.kitware.com/api/v1/api_key/token?key=${GIRDER_API_KEY}&duration=1" -H "Content-Length: 0" | jq .authToken.token)

GIRDER_TOKEN2=$(curl -sSL -X POST "https://data.kitware.com/api/v1/api_key/token?key=${GIRDER_API_KEY}&duration=1" -H "Content-Length: 0" | jq .authToken.token)

curl -vsSL "${DOWNLOAD_URL}" \
        -H "Cookie: girderToken=${GIRDER_TOKEN1}" \
        -H "Girder-Token: ${GIRDER_TOKEN2}" \
        -o "outfile"
```
Which will use `GIRDER_TOKEN1`. This causes difficult to diagnose behavior if `GIRDER_TOKEN1` has expired.
4. Cry silently

**Comment by zachmullen** [comment]
Note: this only happens on endpoints decorated by `access.cookie`.
