### ISSUE TITLE
Small feature request on girder client: retrieve the current user id

### ISSUE THREAD

**Issue by CharlesGueunet** [girder/girder#2987]
There is no native function to retrieve the current user id using the girder-client.
Suggestions:
* The `authenticate` method could return the user id (instead of dropping it).
* A small utility could be created like `getCurrentUser()`, calling a `get` on `user/me`

For now, the solution is to build the request like this:

```
currentUserId = client.get('user/me')['_id']
```

**Comment by zachmullen** [comment]
👍  for having `authenticate` return the user document
👎 for a new method
