### ISSUE TITLE
Move setting enum definitions, defaults, and validators to the same place

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#3006]
Part of this will involve ordering the existing definitions, and fixing a few contradictions and omissions that have crept into the settings over time. This is related to #2994 

An open question is where should the new setting data reside:
* within `girder/models/setting.py`
  * this makes the API for using settings and the definitions all in the same place, making it easier to import and inspect
* within a new `girder/settings.py`
  * this separates the definitions of core settings from the model API (which is independently used by plugins) and keeps the model file in line with the other models

If desired, we could import the new location back into `girder/constants.py`, providing backwards compatibility for downstreams importing from the old location.

**Comment by danlamanna** [comment]
I'd vote for girder/settings.py.

**Comment by manthey** [comment]
We've had requests for access-controlled settings (#1292).  If we think we are going to do that, then having settings be in models would make more sense.

**Comment by brianhelba** [comment]
I'm going to go with `girder/settings.py`, primarily because that file will only service core settings. Plugin settings will continue to be defined in their own files. `girder/models/settings.py` will contain the general database logic to manipulate settings from both core and plugins.
