### ISSUE TITLE
doc: Add license section to readthedocs

### ISSUE THREAD

**Issue by jcfr** [girder/girder#3021]
While reviewing https://github.com/girder/girder/pull/3019, I realized that there was no section  in the documentation explaining what was the Girder license.

What about adding a "License" section to https://girder.readthedocs.io ?

And also indicate that while we would welcome contributions, we also understand that sometimes it is relevant to copy and re-use code. In that case, we recommend that after copying the file into an other code base, the following header should be included:

```
# header ... 
```

We could also indicate that it is sensible to indicate in the commit message the Girder commit at which the file was copied.

**Comment by zachmullen** [comment]
We have the license badge at the top of RTD, and the LICENSE file in the source for those looking to read the full text. Do you think we need more than that?

**Comment by jcfr** [comment]
> We have the license badge at the top of RTD

Good point. I missed that and simply typed "License" in the search box available in the doc page. And  only got results showing up source code files (that either won't be there after this PR is merged or may only show license from third party)

**Comment by zachmullen** [comment]
Ok. Reopen if you think we need more.
