### ISSUE TITLE
Can't run command 'girder-install web'

### ISSUE THREAD

**Issue by MurielCuiCui** [girder/girder#3034]
I followed all instructions of installation ,but when I run 'girder-install web ' ,it went wrong.
![image](https://user-images.githubusercontent.com/37406633/57429784-1d914f80-7260-11e9-83f7-c97378d1fb5a.png)
I don't know how to fix it ？

And then I 'docker-compose up '  with docke-compose.yml ,it also stop because 'girder-install web - alldependecy'

**Comment by zachmullen** [comment]
@MurielCuiCui could you provide minimal steps that reproduce this issue?
