### ISSUE TITLE
Null values in URL query string keys cause MongoDB errors

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#3076]
When REST requests are added to the `auditLogger`, the URL query string [is added as a `dict` at `details.params` of the logger record](https://github.com/girder/girder/blob/0befa8de71472b6e9c7e8768c802af10fa7bc9c5/girder/api/rest.py#L573). While Python allows any string to be used for the keys of this `details.params` `dict`, this dict may later be [inserted into MongoDB by the `audit_logs` plugin](https://github.com/girder/girder/blob/0befa8de71472b6e9c7e8768c802af10fa7bc9c5/plugins/audit_logs/girder_audit_logs/__init__.py#L23), and [MongoDB has restrictions on the names of Python-`dict` / JSON-`Object` keys](https://docs.mongodb.com/manual/core/document/#field-names). In particular, MongoDB does not allow the null character in key names at any location within a document.

Accordingly, a query like `/item?%00=foo` will decode to a Python-`dict` of `'\u0000': 'foo'`, which causes an `InvalidDocument` exception to be raised within the `audit_logs` plugin.

[RFC3986 states that](https://tools.ietf.org/html/rfc3986) (emphasis added):
> Percent-encoded octets must be decoded at some point during the dereference process.  Applications must split the URI into its components and subcomponents prior to decoding the octets, as otherwise the decoded octets might be mistaken for delimiters. Security checks of the data within a URI should be applied after decoding the octets. **Note, however, that the "%00" percent-encoding (NUL) may require special handling and should be rejected if the application is not expecting to receive raw data within a component.**

So, it's probably a good idea to either:
* Sanitize the keys of null characters `details.params` before they're added to auditLogger records
* Sanitize all query string parameters of null characters as soon as Girder receives them

The second option is probably more robust against other similar errors (or attacks). However, if binary, non-Base64 data is ever expected to be provided via a query string, the second option could break such usages.

**Comment by brianhelba** [comment]
Since the `params` also holds the full data of any `x-www-form-urlencoded` bodies, and cannot be distinguished from URL query strings, I'm just going to go with the first option.

For what it's worth, I realized this means that the `audit_logs` plugin is also storing the entire body of any `x-www-form-urlencoded` request. :man_shrugging:

**Comment by zachmullen** [comment]
> For what it's worth, I realized this means that the audit_logs plugin is also storing the entire body of any x-www-form-urlencoded request.

That's by design. We could have some kind of feature in audit_logs itself that truncates data that's too long, however that's a tough call to make if the purpose is to record everything.
