### ISSUE TITLE
Web client build fails due to unreliable google-webfonts-helper service

### ISSUE THREAD

**Issue by wphicks** [girder/girder#3088]
On 2.x-maintenance, the web client code is currently failing to build because we're getting "Service Unavailable" when trying to access google-webfonts-helper. [Related bug from google-fonts-webpack-helper](https://github.com/gabiseabra/google-fonts-webpack-plugin/issues/21) and [underlying issue](https://github.com/majodev/google-webfonts-helper/issues/46#issuecomment-376187190) suggesting that this service should not be relied upon.

To reproduce this, checkout 2.x-maintenance and run `docker-compose build`. If the service is down (as it has been for most of today), you will see an unhandled promise rejection error during build. Once you bring the system up and try to access the web interface, you will instead see this:
![Screenshot_2019-06-27 Girder](https://user-images.githubusercontent.com/11039110/60294132-ad618a80-98ee-11e9-98a6-6f6cc0766978.png)

**Comment by manthey** [comment]
Outdated.
