### ISSUE TITLE
Option in web app to view contents of file without downloading

### ISSUE THREAD

**Issue by ronichoudhury** [girder/girder#309]

**Comment by brianhelba** [comment]
Once merged, https://github.com/girder/girder/pull/1123 should take care of the server-side part of this issue. A GUI preview element is needed to resolve it completely, though this is not feasible to do for any arbitrary file type.

@girder/developers @ronichoudhury @scottwittenburg Do we want to target a small subset of common file types to develop preview capabilities for?

**Comment by jcfr** [comment]
> Do we want to target a small subset of common file types to develop preview capabilities for?

:+1:   

System plugin that would create the preview based on the mime-type, file extension, and optionally metadata ?

**Comment by zachmullen** [comment]
👍 , but I think that's too open-ended to remain an open issue. If we have demand for specific file types, we can open issues for them. The preview plugin exists now, and can be the place to add previews for widely used data formats.
