### ISSUE TITLE
Combine custom filters using a logical AND

### ISSUE THREAD

**Issue by sgratzl** [girder/girder#3130]
right now in the `Folder.childItems` method the given filters can override the folder query:

https://github.com/girder/girder/blob/da5c16e5e2fa51cd8948a5d730eb3b2764d8968f/girder/models/folder.py#L407-L410

Imo instead of a plain update one should combine the queries using a logical AND, as in 
```python
if filters:
  q = {
    '$and': [q, filters ]
  }
```

This will ensure that only children of this filter will be considered by the filter. Otherwise, I can do something like:

```python
.childItems(filters={ 'folderId': {'$exists': True}})
```

to get all items in the datastore.

**Comment by zachmullen** [comment]
If you're looking for all the items in the datastore, `Folder.childItems` is the wrong function to use, instead do `Item().find()`. The `find()` method provides full control over the query into each underlying collection.

As a side note, `$and` is the default behavior when passing a query object with multiple keys.
