### ISSUE TITLE
Correctly handle range requests from video players

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#3135]
> If girder is asked for the whole file (Range 0-), then it responds with a 200.  Reading https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests, we probably should still send a 206.

**Comment by manthey** [comment]
Nothing we've done that I know of requires multipart range requests.  We probably should return a 416 if asked for a multipart range request (I think, but haven't checked, that we return a 200 with the full data, which is also allowed).

**Comment by manthey** [comment]
Reading the specification (https://tools.ietf.org/html/rfc7233#section-4.4), 416 is only appropriate if the range is outside of the file.  The spec permits just sending the whole file with a 200 response if we don't support multipart range requests.

Our current behavior of sending a 200 when the range request is the whole file is within spec, since it reads the server SHOULD send a 206, as opposed to requiring it.  We still should change that.

**Comment by zachmullen** [comment]
Did we check that changing to 206 fixes the particular video issue we were seeing?

**Comment by manthey** [comment]
Yes.  I did a quick hack to `girder/utility/abstract_assetstore_adapter.py`, changing
```
        if (offset or endByte < file['size']) and file['size']:
```
to
```
        isRangeRequest = False
        try:
            import cherrypy
            isRangeRequest = bool(cherrypy.request.headers.get('Range'))
        except Exception:
            pass
        if (offset or endByte < file['size'] or isRangeRequest) and file['size']:
```
and Chrome reads the first few bytes in the first request and then makes range requests henceforth.

This is not how I would do this for production, but it worked for a test.  I would avoid a cherrypy import outside of the `girder/api` modules.  And, looking at `girder/api/v1/file.py`, I think if we send a multipart range request we respond with the first part only (we should respond with a 200 and the whole file instead).

**Comment by zachmullen** [comment]
That actually looks like the real solution to me. We're already importing cherrypy symbols into that module, and the function itself is designed to deal with HTTP headers, so it doesn't seem out of place.

I'll also fix the multipart behavior.
