### ISSUE TITLE
Generate typescript client library from openapi spec.

### ISSUE THREAD

**Issue by subdavis** [girder/girder#3146]
Talked with some people last night who were using https://www.npmjs.com/package/@openapitools/openapi-generator-cli

They would generate a TypeScript library for interacting with their backend in the backend's CI, and publish it to NPM.  Then, any client application that wants to interact with the backend can include this autogenerated library. 

I think Girder would be a great candidate for doing this.  There are dozens of client apps backed by girder at this point.   I know many of those apps involve plugins where the API is extended in some way, so that may throw a wrench in this, but I'm not sure.

Girder's API doesn't change too often, so this would be more of a developer quality-of-life concession than something to protect apps from changes to the API surface.  I'm imagining importing the library in my project and getting great autocomplete for all the routes and params and enums in girder, and save us from having to do string interpolation all over the place, as well as giving us access to girder's contants such as the modelTypes.

I think I'll try generating a client when I have time just to play with.  

## Reference

https://github.com/jackkoppa/typesafe-api-clients-demo

**Comment by danlamanna** [comment]
It's been my experience that these types of tools generally don't work well with Girder, but I would love to be proven wrong. Before going down this route I would attempt to use an OpenAPI validator to fix the schema that Girder generates. As it stands Girder doesn't generate an OpenAPI compliant document.
