### ISSUE TITLE
Password exposure in Logs

### ISSUE THREAD

**Issue by CarstenWalther** [girder/girder#3184]
When I change the password, the old and new password appear in the girder logs in plain text like this:
```
172.22.0.4 - - [22/Jan/2020:13:58:40] "PUT /api/v1/user/password?old=myOldPassword&new=myNewPassword HTTP/1.1" 200 32 "http://localhost/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
```
Besides girder, web proxies also often log the url including parameters. Because of that, the url should not contain sensitive information.

Affected routes are:
* `POST /user`
* `PUT /user/{id}/password`
* `PUT /user/password`

Some routes contain a token. This could also be a problem depending on the properties of that token.
* `PUT /user/{id}/verification`
* `GET /user/password/temporary/{id}`

My recommendation is to put sensitive information in the body of the request to avoid it appearing in logs.

**Comment by zachmullen** [comment]
Unfortunately we can't stop arbitrary clients from putting sensitive information in URLs, however we can stop our own clients from doing so. I just checked, and the default Girder web client does not do this bad behavior. Are you aware of which client application is sending this request?

(In the default Girder web client, the code for changing password starts [here](https://github.com/girder/girder/blob/master/girder/web_client/src/models/UserModel.js#L91-L105). That ends up passing the `data` parameter down to `$.ajax` [here](https://github.com/girder/girder/blob/master/girder/web_client/src/rest.js#L140), which uses a `application/x-www-form-urlencoded` body to send the parameters.)

One thing we could do to at least help mitigate this case would be to explicitly check how the parameters were sent on the few REST routes that accept password parameters, and give a 400 response if they were passed via URL. That would at least force authors of other clients to do the right thing if they want their app to work.

**Comment by zachmullen** [comment]
On further exploration, I discovered that our swagger page *is* in fact doing the bad thing. Insofar as that is one of our clients, we should fix that.

**Comment by CarstenWalther** [comment]
Ah, I didn't know that it is possible to send the parameters with `application/x-www-form-urlencoded`. This solves the problem.

We (and surely others) followed the swagger documentation which uses normal url parameters. Maybe it is possible to reject these. However this would be a breaking change.

**Comment by zachmullen** [comment]
I'm going through and changing the OAS specs for the endpoints you identified. Thanks for the report.

**Comment by zachmullen** [comment]
I'm going to close this via #3185 but I am going to open a new issue because I don't have a good solution for `GET /user/password/temporary/{id}` at this time. GET requests are not allowed to have bodies, so one option would be to force the token to be passed via a header, which is fine. However that would be a breaking change involving deprecating a route and adding a new one, which is a little out of scope for #3185.

**Comment by CarstenWalther** [comment]
Thanks for the fast response!
