### ISSUE TITLE
Settings cache leads to unexpected behavior

### ISSUE THREAD

**Issue by manthey** [girder/girder#3201]
If you've enable the dogpile setting cache and have an event listener on `model.setting.save.after`, the event will get the old value of the setting, not the new value.

Specifically, if you configure the cache via the ini file like:
```
[cache]
enabled: True
cache.global.backend = "dogpile.cache.memory"
```
and, in some code, bind to the settings change:
```
events.bind('model.setting.save.after', 'cool.plugin', onSettingChange)
```
Then in the function `onSettingChange`, `Setting().get(<setting name>)`, will get the old value.  The event has the new value.

Within the setting model, this could be prevented by invalidating the cache before the save (e.g., change:
```
        setting = self.save(setting)
        self._get.set(setting, self, key)
```
to:
```
        self._get.invalidate(self, key)
        setting = self.save(setting)
        self._get.set(setting, self, key)
```
though there will still be race conditions if multiple threads are changing the setting concurrently.

**Comment by manthey** [comment]
I can make a PR with the `self._get.invalidate` line added.  There is still the possibility of wrong answers if multiple threads are changing the same setting, but, I think, this is strictly better than the current behavior.

**Comment by zachmullen** [comment]
Please do make that change, thanks!
