### ISSUE TITLE
Can girder work with another OAuth2 provider that isn't Google?

### ISSUE THREAD

**Issue by xdoan** [girder/girder#3208]
Synapse is an OAuth2 [server](https://docs.synapse.org/articles/using_synapse_as_an_oauth_server.html) and I was wondering if it is possible to use it as an OAuth provider instead of Google as shown on the [docs](https://girder.readthedocs.io/en/stable/plugins.html#oauth2-login)

**Comment by mgrauer** [comment]
Girder currently works with multiple different OAuth2 providers, including Google, Globus, Linkedin, Box, BitBucket, GitHub. 

It isn't too much code to add a new OAuth2 compliant provider, see these [examples](https://github.com/girder/girder/tree/master/plugins/oauth/girder_oauth/providers).
