### ISSUE TITLE
Add Attribute Based Access Control to Girder's OAuth/OIDC integration

### ISSUE THREAD

**Issue by brucehoff** [girder/girder#3212]
OpenID Connect (OIDC) allows an external identity provider (IdP) to return user metadata when the IdP is used to log in.  [Synapse](https://www.synapse.org) is an OIDC IdP which has both users and groups (called Teams).  When a relying party (like Girder) authenticates via Synapse it can retrieve team membership information.  (Details [here](https://docs.synapse.org/articles/using_synapse_as_an_oauth_server.html).)  It would be very useful if an instance of Girder could be configured to assign permissions to a Girder user based on their team membership in Synapse (or other metadata in this or other OIDC IdPs).  This way, when a user is assigned an attribute in the IdP, access to resources in Girder could be unlocked.  (This method of controlling access to resources is called "Attributed Based Access Control".)

A system which does this today is the OIDC aggregator, [Keycloak](https://www.keycloak.org/documentation.html).  Keycloak allows the administrator to define various types of "Mappers" one of which is a "Claim to Role" mapper.  The admin' can map an OIDC claim from a selected OIDC IdP to a Keycloak role.  We have demonstrated that Synapse team membership can be used as a basis for giving a user a role in Keycloak.

**Comment by zachmullen** [comment]
I would argue that using team membership to mediate access to a resource is more akin to RBAC than ABAC -- ultimately, a "role" is no different than any other subject attribute. If we want to say Girder supports ABAC, I think it would require core changes to allow for Object Attributes on data resources, and support of ABAC Boolean policies to mediate that access. While this is actually a fundamental desire for the future of Girder, it's not something we intend to support in the system as it exists today.

All that is to say, I would encourage you to do this Synapse team logic in your own plugin, which is certainly possible, if a little messy. (For one there's a synchronization issue.) We already expose hooks in the OAuth plugin to allow additional scopes per provider, and people have used those hooks successfully to provide deeper integration with an OAuth Provider.

**Comment by brucehoff** [comment]
> people have used those hooks successfully to provide deeper integration with an OAuth Provider
Are there examples of this in the Girder code base?

**Comment by zachmullen** [comment]
I wrote a simple one recently but just remembered it's private, unfortunately. But I found one that was written a while ago on the WholeTale project: [here](https://github.com/whole-tale/girder_wholetale/blob/341376e1f49642b44cf68794ef0502d8522322f8/server/__init__.py#L480). That event is the one you'd hook into to intercept OAuth logins and do something special with the response, e.g. adding team membership info into the user's document in Mongodb.

If you need to request more scopes from a given provider during the OAuth flow, then during your plugin setup you can simply extend that provider's `_AUTH_SCOPES` class-level attribute, e.g.

```python
from girder_oauth.providers import Google
Google._AUTH_SCOPES += ['some_other_custom_scope']
```
