### ISSUE TITLE
Make Girder in cherrypy respond appropriately to SIGTERM

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#3247]
Right now `SIGTERM` sent to `girder serve` does nothing. According to [these cherrypy docs](https://docs.cherrypy.org/en/latest/pkg/cherrypy.process.html#cherrypy.process.plugins.SignalHandler), cherrypy should exit gracefully when SIGTERM is sent, but it doesn't. We should figure out why that is. Are we overriding these defaults somehow? Or is this an upstream bug?

**Comment by zachmullen** [comment]
Update: this only happens inside docker, and only because Girder is running as PID 1, which is immune to SIGTERM. This is apparently not an issue with cherrypy.

**Comment by subdavis** [comment]
For posterity:

* https://engineeringblog.yelp.com/2016/01/dumb-init-an-init-for-docker.html
* https://docs.docker.com/engine/reference/run/#specify-an-init-process
