### ISSUE TITLE
Range Request handling for /item/download endpoint

### ISSUE THREAD

**Issue by BryonLewis** [girder/girder#3302]
Currently the `/item/download` endpoint will return a 206 response when accessed but will not properly handle the range request. This is most easily seen in attempting playback of large streaming videos. It will attempt to download the file from the beginning of to the point of the range request.  I.E - if you have a large video (~700MB) and seek a few seconds in it will grab ~15-10MB of data, seeking to the end it will attempt to grab ~670-700MB of data.

The `file/download` endpoint has the proper behavior where it properly limits the range request to a subset of the data. Jumping anywhere in the video will grab a surrounding area of data instead of the whole thing.

My understanding is that /item/download may download multiple files so handling only in the case of a single-file-item might be necessary.

References for previous related issues/PRs:
Issue #3135 
Fixed in PR #3136

**Comment by jbeezley** [comment]
https://github.com/girder/girder/blob/master/girder/api/v1/item.py#L293 I wonder if redirecting to the file download endpoint would be the simplest solution here.
