### ISSUE TITLE
Package tests as well

### ISSUE THREAD

**Issue by mcepl** [girder/girder#3314]
Many third party distributors (talking for the OpenSUSE Linux distribution, but I guess brew, BSD ports, pkgsrc, anaconda and other maintainers are in the same boat) want to run the test suite to check for at least basic functionality of the generated packages.

Life would be much easier if we get the test suite stored in the release tarball as well.

**Comment by zachmullen** [comment]
Hi @mcepl , could you provide some story / context to motivate this desire? Is there something concrete you're attempting to achieve?

Feel free to submit a PR related to this, if that is an easier way to express your desired changes.

Thanks!

**Comment by mcepl** [comment]
> Hi @mcepl , could you provide some story / context to motivate this desire? Is there something concrete you're attempting to achieve?

Typical OpenSUSE package (e.g., [python-setuptools](https://build.opensuse.org/package/live_build_log/devel:languages:python/python-setuptools:test/openSUSE_Tumbleweed/x86_64)) runs whole test suite when being build. Even when we have to eliminate some cases (either because it accesses network, which is not available in the build environment, or because it uses some specialized hardware), it still gives at least some level of certainty that we are providing to our users something which at least resembles working package. Also this testing on various different platforms (both hardware and operating systems) helps you, the upstream, with more extensive testing in situations which are unfamiliar to you (we file hundreds of bugs and patches for them).

We could (and we do it when not other way is available) download `test*/` directory from GitHub and use it, but it would be much more convenient if those tests were directly packages in the distribution tarball.

**Comment by zachmullen** [comment]
I see, are you attempting to build a Girder package for OpenSUSE?

**Comment by mcepl** [comment]
Well, not me, one of our volunteer community developers, but yes.

**Comment by zachmullen** [comment]
Interesting, I don't think the girder maintainers were aware of that effort at all. We've only really sought to support installation via pip/pypi. And as for testing we've only sought to support it in dev environments and CI.

I'd be interested to discuss with whoever is undertaking the effort. The major complication in this case is that Girder's test suite, or at least the vast majority of it, depends on having a running mongo service.

**Comment by MeggyCal** [comment]
Hi, I was trying to package it. But we found out it would be too complicated for us to package and maintain with tests, as it requires set up mongo service (we just considered the tests as nice-to-have). So thanks for your care and feel free to close this issue :) .

**Comment by zachmullen** [comment]
Thanks @MeggyCal , good luck!
