### ISSUE TITLE
Does girder support MS SQL server ?

### ISSUE THREAD

**Issue by rsurdikar** [girder/girder#3315]
Hi,

I am new to the girder platform. I couldn't find if there is SQL Server database support. 

Could anyone please comment if it supports it and how?

**Comment by zachmullen** [comment]
Hi @rsurdikar , what kind of support are you talking about? Could you describe your need?

**Comment by rsurdikar** [comment]
Hi, @zachmullen Thanks for responding. 

We have an existing SQL Server DB & We want to quickly build a python based API/UI on top of it with the user authentication.

But when I looked into girder documentation, I see it supports MongoDB so I was wondering do I have to migrate my MSSQL DB to MongoDB or If there is something (maybe plugin) in a girder to work with SQL server. Thanks.

**Comment by zachmullen** [comment]
You could of course build a plugin that uses some SQL python library to communicate with your RDBMS. It may or may not be easier than just using some other framework e.g. Django on top of your existing database.

**Comment by rsurdikar** [comment]
Thanks, @zachmullen for the reply,  This is helpful. To summarize, I will need to build a plugin to support the MS SQL server.

**Comment by zachmullen** [comment]
Sure thing! Best of luck with the plugin. I'll close this issue now.
