### ISSUE TITLE
girder-client upload with spaces in folder name

### ISSUE THREAD

**Issue by knappa** [girder/girder#3317]
Spaces in the folder name make the girder client unhappy when uploading.

Ex:
```
girder-client <omitted> upload 5fc92dbac13b1bfaa5ff1c03 Brian\'s\ converted\ VTK\ files/
Usage: girder-cli upload [OPTIONS] PARENT_ID LOCAL_FOLDER...
Try 'girder-cli upload -h' for help.

Error: Invalid value for 'LOCAL_FOLDER...': Path 'Brian's' does not exist.
```

**Comment by knappa** [comment]
BTW, this is only for the folder coming in as a command line argument, subfolders with spaces work fine.

**Comment by zachmullen** [comment]
Does it work when you put quotes around the filename on your shell?

**Comment by jbeezley** [comment]
I couldn't reproduce:
```
$ girder-client <omitted> upload 5f7b71a77b14063a6758baa3 Brian\'s\ converted\ VTK\ files/
Creating Folder from Brian's converted VTK files
```

And when it doesn't exist:
```
$ girder-client <omitted> upload 5f7b71a77b14063a6758baa3 does\ not\ exist/
Usage: girder-client upload [OPTIONS] PARENT_ID LOCAL_FOLDER...
Try 'girder-client upload -h' for help.

Error: Invalid value for 'LOCAL_FOLDER...': Path 'does not exist/' does not exist.

```

**Comment by knappa** [comment]
No, quotes didn't help. 

Here's some version info, if it helps:
Python 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 23:03:20)
GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)

**Comment by knappa** [comment]
Never mind, shell scripting issue.
