### ISSUE TITLE
sftp service should provide time information

### ISSUE THREAD

**Issue by bilke** [girder/girder#3325]
First thanks for this awesome project!

Here comes a feature request:

The sftp service should expose `mtime` (modified time) and `atime` (access time) as this is really helpful to determine if a file needs to be downloaded again.

**Comment by zachmullen** [comment]
I think we are already setting `mtime` [here](https://github.com/girder/girder/blob/master/girder/api/sftp.py#L50-L53). As far as `atime`, that's not information we record on the documents.

**Comment by bilke** [comment]
@zachmullen Yes I have seen this too. I could fix this by also setting `atime`! See my PR..

**Comment by bilke** [comment]
Simply by also setting `atime` both of my clients (Cyberduck and pysftp) show the modified time.

**Comment by zachmullen** [comment]
Great! Thanks, I'll merge the PR once it passes CI.
