### ISSUE TITLE
question: method to authenticate with Girder front end via token or api key

### ISSUE THREAD

**Issue by gkois** [girder/girder#3335]
Hello,

I would like to ask if there is a way to authenticate with the front end app bypassing the login screen and providing either a girder token or an api key?

My aim is to integrate girder inside a react/express node application using iframe and to authenticate user only once.

thank you in advance.

**Comment by zachmullen** [comment]
You can use [authentication tokens}(https://girder.readthedocs.io/en/latest/developer-cookbook.html#authenticating-to-the-web-api).

You can also use API keys, and simply exchange the key for an authorization token via the `POST api_key/token` REST endpoint.
