### ISSUE TITLE
Segmentation error

### ISSUE THREAD

**Issue by ryankerney** [girder/girder#3349]
I am trying to use the segment tool on this slide
https://images.slide-atlas.org/#item/5eeb68425cc6d12cc7b29952

and am getting the error message "DetectSections has not been transferred" I would like to export these sections for serial reconstruction in Fiji.

**Comment by manthey** [comment]
@ryankerney What segment tool are you using?  It's not clear how this relates to Girder.  If you are using Slide-Atlas, you should post your issue there (https://github.com/SlideAtlas/SlideAtlas-viewer). 

I'm closing this.  If it actually has to do with Girder, please reopen.

**Comment by ryankerney** [comment]
OK - it looked like Girder was the back end of slide-atlas. I’ve posted to their forum.
On Apr 1, 2021, 11:53 AM -0400, David Manthey , wrote:

@ryankerney<https://github.com/ryankerney> What segment tool are you using? It's not clear how this relates to Girder. If you are using Slide-Atlas, you should post your issue there (https://github.com/SlideAtlas/SlideAtlas-viewer).

I'm closing this. If it actually has to do with Girder, please reopen.
