### ISSUE TITLE
pymongo.errors.OperationFailure and vagrant error

### ISSUE THREAD

**Issue by sunaifei** [girder/girder#3373]
When I install girder follow the HismoicsUI respository，execute “girder serve”,
I get pymongo.errors as follows:
pymongo.errors.OperationFailure: command createIndexes requires authentication, full error: {'ok': 0.0, 'errmsg': 'command createIndexes requires authentication', 'code': 13, 'codeName': 'Unauthorized'}

And when I install girder follow the Developer Documentation, after "vagrant up" and "vagrant ssh", execute “girder serve”,
I get errors as follows: -bash: girder: command not found

**Comment by zachmullen** [comment]
Thanks for the report @sunaifei , since this is from the HistomicsUI instructions, could you please re-open the issue there?

**Comment by sunaifei** [comment]
> Thanks for the report @sunaifei , since this is from the HistomicsUI instructions, could you please re-open the issue there?

Thanks for your quick reply, I will report the issue in HistomicsUI.
But when I used vagrant method to install, it showed that -bash: girder: command not found. Did I miss any step?
