### ISSUE TITLE
LDAP plugin now showing in web UI

### ISSUE THREAD

**Issue by btsherid** [girder/girder#3374]
Hi,

I'm wondering if someone might be able to help me out in getting the LDAP plugin to show up in the web UI. Here's what I did:

docker exec -it 67d810e4452e /bin/bash
apt-get update
apt-get install libldap2-dev libsasl2-dev
pip install girder-ldap
girder build

All those commands completed successfully but the Plugins page in the web UI doesn't look any different.

I am using the docker-compose method of running histomics. If I can get this LDAP plugin figured out, I will also have to figure out how to make it persistent if I run docker-compose down and docker-compose up. I have updated the Dockerfile to include the apt packages and the plugin, but I'm hoping I don't have to rebuild because that would remove all the user accounts/assetstores/etc.

Thanks,
Brendan

**Comment by zachmullen** [comment]
Installing new plugins won't have an effect until the server is restarted, so I don't think it'll work with `docker exec` unless you can also restart the server without stopping the container.

**Comment by manthey** [comment]
If you ran this in a running docker, Girder won't have restarted to load the plugin.  Do a `docker restart <container id>`, and you should see the changes.

For persistence, you could add this as part of the docker-compose girder `command`.
