### ISSUE TITLE
`Error 400: redirect_uri_mismatch` for Google and GitHub OAuth

### ISSUE THREAD

**Issue by fepegar** [girder/girder#3382]
Hello again,

I would like to have support for OAuth using [Azure Active Directory](https://azure.microsoft.com/en-us/services/active-directory/).

First, I thought I'd try a provider that was already implemented in Girder. Unfortunately, I'm getting a `redirect_uri_mismatch ` error for GitHub and Google.

After logging in GitHub, I get redirected to a URL and I can read:

```json
{
    "message": "Provider returned error: 'redirect_uri_mismatch'.",
    "type": "rest"
}
```

The URL is https://dsamsr.azurewebsites.net/api/v1/oauth/github/callback?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=1hryXDsRKDDGn42Jd2GwumOV4x8q0ukrxPL0RNb63PsfxyA7irWwZ4mzDvk2mBXy.https%3A%2F%2Fdsamsr.azurewebsites.net%2F%23

As you can see, it says "The redirect_uri MUST match the registered callback URL for this application".

I get something similar from Google, but nicer:

![google](https://user-images.githubusercontent.com/12688084/156406759-d9afdd27-0b76-4dfe-b00d-2a7ee21d1ad0.PNG)

I don't think I've messed up the redirect URIs for both... there's not a lot of possibilities for mistakes here, specially for the GitHub app, which has very little configuration choices.

Am I doing anything obviously wrong here?

**Comment by fepegar** [comment]
It does. I copied the URI shown in `[dsaweb]/#plugins/oauth/config` and pasted it on the provider's app settings. I just tried with BitBucket too, and got a similar error.

**Comment by fepegar** [comment]
OAuth works when I deploy the DSA on a virtual machine. I am now pretty sure that authentication wasn't working as [it's not supported yet for multi-container Azure web apps](https://docs.microsoft.com/en-us/answers/questions/11673/azure-web-app-for-multi-containers-no-access-to-au.html?sort=votes). I'm happy to close this issue now, if you are.

**Comment by zachmullen** [comment]
Ok, thanks!
