### ISSUE TITLE
Unable to use API call "resource/<folder_id>/items?type=folder" with API key

### ISSUE THREAD

**Issue by ant0nsc** [girder/girder#3436]
I'm struggling badly with the API call to read all child items in a folder, via the `resource/<folder_id>/items?type=folder` API call. It all works fine when I'm logged into DSA and use the API directly from the web page, I get all the expected items back.

However, when using an API key to authenticate (via the `girder_client` package), I always get
```
HTTP error 401: GET https://dsa.somewhere.com/api/v1/resource/6374dcbe26eb3de41c3a4ac0/items?type=folder
Response text: {"message": "Read access denied for folder 6374dcbe26eb3de41c3a4ac0 (user None).", "type": "access"}
```
I've played with all sorts of permissions on the API key - I'm now using one that has scope ` ["core.data.read", "core.data.write",  "core.data.own", "core.assetstore.read", "core.setting.read", "core.user_info.read"]`, still without success.

Can anyone please clarify what permissions are necessary to read items in a folder?

**Comment by zachmullen** [comment]
Have you tried an API key that has full access rather than scoped access?

**Comment by zachmullen** [comment]
The way this works is that each API endpoint can be annotated with the token scopes that are required to use it. However, if no annotation is provided for an endpoint, the only way to call it is with one of these all-powerful tokens. We should probably resolve this issue by adding a scope to the endpoint in question.

**Comment by manthey** [comment]
The `GET resource/<id>/items` endpoint isn't actually in Girder -- it is added by the HistomicsUI plugin.  Looking at its code, somehow that and one other endpoint aren't annotated with required scopes (they should be).  Ideally, this should be an issue in https://github.com/DigitalSlideArchive/HistomicsUI and we can fix it there.

I'll close this here and reopen it there.
