### ISSUE TITLE
running girder with url prefix

### ISSUE THREAD

**Issue by matuskosut** [girder/girder#3442]
Hi,

Is it possible to run girder within url prefix e.g. http://example.com/services/girder ?

accessing these urls works:
- http://example.com/
- http://example.com/api/v1

accessing expected urls doesn't work (404):
- http://example.com/services/girder/
- http://example.com/services/girder/api/v1

I tried the settings below (also in different combinations), but it didn't seem to change anything:

```
[global]
server.socket_host = "0.0.0.0"
tools.proxy.on = True
tools.proxy.base = "http://example.com/services/girder"
tools.proxy.local = ""

[server]
api_root = "/services/girder/api/v1"
static_public_path = "/services/girder/static"
```

Is this something that should be doable with girder.cfg setup or should I look into running some proxy in front of girder instead?

**Comment by manthey** [comment]
This is discussed in the docs (https://girder.readthedocs.io/en/latest/deployment-alternatives.html#reverse-proxy) and is supported by using a reverse proxy, such as nginx along with some girder settings.

**Comment by matuskosut** [comment]
@manthey Of course I started there, but it is rather unclear how to set this up without spending 1 day experimenting with configs. I would suggest rephrasing the nginx part a little. Basically when using URL prefix reverse proxy is not optional but necessary.
