### ISSUE TITLE
Issue with large JSON files

### ISSUE THREAD

**Issue by madhusikha** [girder/girder#3457]
Hello,

I have been trying to visualize annotations (JSON format) of a whole slide image in DSA-Staging.
If the JSON file size if less than 1 GB, the annotations are being loaded in few minutes, but if the JSON file is larger than 1 GB, they are not being shown up. Can you please look into this and suggest me a solution.

Thanks and Regards,
Madhu Babu Sikha

**Comment by madhusikha** [comment]
Thanks for the reply David Manthey.
Can you please suggest me some references to follow for the solutions you have mentioned. It really helps me. Thanks in advance.
-Madhu
________________________________

**Comment by manthey** [comment]
@madhusikha This really should have been made configurable, so I've made a branch that does so (in https://github.com/girder/large_image/pull/1264).  See the last configuration entry here https://github.com/girder/large_image/blob/cb3c43d7b06ac0ee0706fa3b822fe44dd3691a25/docs/config_options.rst#configuration-options for details.  The docker images for the DSA will include this after all CI checks pass. 

I'll close this issue; if you still have questions related to this, can you open a new issue in the https://github.com/girder/large_image repo?
