### ISSUE TITLE
AccessControlMixin doesn't work with models defined in plugins

### ISSUE THREAD

**Issue by Xarthisius** [girder/girder#3535]
### Description

`AccessControlMixin` uses `ModelImporter.load` to load a proper model class throughout its methods. The signature of the latter is:
https://github.com/girder/girder/blob/dc40cd62a192beda71ec4e0ed7620a166958a378/girder/utility/model_importer.py#L37

However, almost all invocation of `ModelImporter.load` in `AccessControlMixin` simply pass a single argument `self.resourceColl`. The only place where the additional `plugin` kwarg is handled is here:

https://github.com/girder/girder/blob/dc40cd62a192beda71ec4e0ed7620a166958a378/girder/utility/acl_mixin.py#L56-L57

### Expected results

Handle models defined in plugins, e.g.:

```
# server/models/form.py
class Form(AccessControlledModel):
    def initialize(self):
        self.name = "form"

# server/models/entry.py
class FormEntry(acl_mixin.AccessControlMixin, Model):
    def initialize(self):
        self.name = "entry"
        self.ensureIndices(["formId", "data.sampleId"])
        self.resourceColl = ("form", "jsonforms")
        self.resourceParent = "formId"
```

### Actual results

```
Traceback (most recent call last):
  File "/girder/girder/api/rest.py", line 630, in endpointDecorator
    val = fun(self, path, params)
  File "/girder/girder/api/rest.py", line 1216, in GET
    return self.handleRoute('GET', path, params)
  File "/girder/girder/api/rest.py", line 970, in handleRoute
    val = handler(**kwargs)
  File "/girder/girder/api/describe.py", line 709, in wrapped
    return fun(*args, **kwargs)
  File "/girder/girder/api/rest.py", line 445, in wrapped
    val = fun(*args, **kwargs)
  File "/girder/plugins/jsonforms/server/rest/entry.py", line 38, in listFormEntry
    cursor = FormEntryModel().findWithPermissions(
  File "/girder/girder/utility/acl_mixin.py", line 303, in findWithPermissions
    if (not isinstance(self.model(self.resourceColl), AccessControlledModel) or
  File "/girder/girder/utility/model_importer.py", line 88, in model
    module = 'girder.models.%s' % model
```

**Comment by zachmullen** [comment]
One solution would be to add a special attribute to `AccessControlMixin` called `model_name: str`, and if present, would override the default behavior.

**Comment by zachmullen** [comment]
Or better yet, rather than calling the model importer, we could just use `self`, since this is meant to be mixed into models... or am I oversimplifying?
