### ISSUE TITLE
api uploadFile parameter reference 

### ISSUE THREAD

**Issue by logincat** [girder/girder#3546]
this information is passed to the data.process event when the upload is complete.

![Uploading Snipaste_2024-06-24_19-29-32.jpg…]()

where can find the example about the reference , [optional reference to send along with the upload.].
i want to convert to item's annotaions when the target file upload

**Comment by zachmullen** [comment]
The reference is an opaque value that is up to each application how to use it. Is this question in reference to a specific application of Girder?

**Comment by logincat** [comment]
oh, right ,it use for histomics

**Comment by zachmullen** [comment]
I would suggest opening an issue in https://github.com/DigitalSlideArchive/HistomicsUI or https://github.com/DigitalSlideArchive/digital_slide_archive

Thanks!
