### ISSUE TITLE
Loading resources with `fields` kwarg resets metadata (girder-5)

### ISSUE THREAD

**Issue by Xarthisius** [girder/girder#3550]
### Description

Simply loading a folder or an item with `fields={}` results in deletion of its metadata. I tested that it doesn't happen in girder < 5.

### How to test?
Following test shows the issue:

```
from girder.constants import AccessType
from girder.models.folder import Folder


def test_folder_not_clearing_metadata(admin):
    metadata = {"metadata": "very important!!!"}
    # Create a folder
    folder = Folder().createFolder(
        parent=admin, parentType="user", creator=admin, name="Test Folder", public=True
    )

    Folder().setMetadata(folder, metadata)

    # Check that the folder has metadata after regular load
    folder = Folder().load(folder["_id"], user=admin, level=AccessType.READ)
    assert folder["meta"] == metadata

    # TODO: this should be fixed
    folder = Folder().load(folder["_id"], user=admin, level=AccessType.READ, fields={})
    # Check that the folder has metadata after previous load with fields={}
    folder = Folder().load(folder["_id"], user=admin, level=AccessType.READ)
    assert folder["meta"] == metadata
```

### Expected result
Calling `load()` does not modify the database entry. Folder should still contain `meta: {"metadata": "very important!!!"}`

### Actual results
`meta` changes to `{}`

Tested on https://github.com/girder/girder/commit/7ce8ad1f3477c3d2bb4c754cfa895e9719317731

**Comment by zachmullen** [comment]
Thanks for the report, I've verified this locally. Will investigate.

**Comment by zachmullen** [comment]
@Xarthisius I am pretty sure this does occur on Girder < 5, as the faulty logic appears on master branch and has for a long time: https://github.com/girder/girder/blob/master/girder/models/item.py#L106-L134

**Comment by zachmullen** [comment]
Good to know, I'll go ahead and merge master into v4-integration. Are you using git directly, or one of the alpha releases on pypi?

**Comment by Xarthisius** [comment]
Git directly.

**Comment by zachmullen** [comment]
Ok, latest master is merged to `v4-integration`.
