### ISSUE TITLE
Document what steps we've taken to protect against security threats

### ISSUE THREAD

**Issue by mgrauer** [girder/girder#356]
paraphrasing myself from an email

I think it makes sense to include in the Girder documentation our security and threat mitigation practices for each threat we've dealt with.  This can make adoption much easier for external groups, and we can refer anyone with questions to the public docs rather than asking on email, etc.

We should have an authoritative source(s) for security threats, and issues for each of these so we can address them.  I found these lists of common security threats, not sure if anyone has a better list that is public.

https://www.owasp.org/index.php/Category:OWASP_Best_Practices:_Use_of_Web_Application_Firewalls

especially A3.2 & A5 .

**Comment by brianhelba** [comment]
@mgrauer @manthey @girder/developers Is https://github.com/girder/girder/blob/master/docs/security.rst sufficient to consider this issue resolved?

**Comment by zachmullen** [comment]
We should add a blurb about how we store passwords with bcrypt.

**Comment by brianhelba** [comment]
As part of this, if https://github.com/girder/girder/issues/1167 is implemented, it should be noted in https://github.com/girder/girder/blob/master/docs/security.rst .
