### ISSUE TITLE
Make FileHandle's maximum read size configurable

### ISSUE THREAD

**Issue by Xarthisius** [girder/girder#3567]
I'm using `girder.utility.abstract_assetstore_adapter.FileHandle` to open files that are larger than 16MB. Currently that size limit is hardcoded:

https://github.com/girder/girder/blob/37e66ea768c1e9d98a9660f03e8c9dab70088972/girder/utility/abstract_assetstore_adapter.py#L40

I'd like to propose making it configurable. Should I use `Setting()` for that (e.g. `FILEHANDLE_MAX_SIZE = 'core.filehandle_max_size'` or rather env var (`GIRDER_FILEHANDLE_MAX_SIZE`)?

**Comment by zachmullen** [comment]
`Setting` is good for this. All Settings can now be set via environment variables (which is the preferred way).
