### ISSUE TITLE
Add JavaScript web client models and utilities to API documentation

### ISSUE THREAD

**Issue by jamiesnape** [girder/girder#373]
Something like this would generate RST from JsDoc:
https://github.com/juhamust/jsdoc-toolkit-rst-template

**Comment by zachmullen** [comment]
After many years, we finally have some javascript documentation: https://doc.esdoc.org/github.com/girder/girder/

Long term it might be nice to switch to something like the service you mention, but for now I'll close this until we become unhappy with the status quo.
