### ISSUE TITLE
GeoJSON plugin returns coordinates as quoted strings

### ISSUE THREAD

**Issue by jamiesnape** [girder/girder#380]
For example

``` json
{
    "type": "Polygon",
    "coordinates": [[["1.0", "2.0"], ["3.0", "4.0"],  ["5.0", "6.0"],  ["1.0", "2.0"]]]
}
```

which is not valid GeoJSON. It should be

``` json
{
    "type": "Polygon",
    "coordinates": [[[1.0, 2.0], [3.0, 4.0], [5.0, 6.0],  [1.0, 2.0]]]
}
```

**Comment by markstos** [comment]
@jamiesnape Could you provide a reference to the GeoJSON spec that says that quoting the coordinate values is not valid? I'm trying to check that detail myself now and can't find it.

**Comment by jamiesnape** [comment]
http://geojson.org/geojson-spec.html#positions

> A position is represented by an array of numbers.

Everything in the [examples](http://geojson.org/geojson-spec.html#appendix-a-geometry-examples) is also unquoted.

**Comment by markstos** [comment]
Thanks. I further found that the definition of "number" is given as being defined in how the JSON spec defines a number, and the JSON spec is quite clear that numbers are not quoted:
http://json.org/
