### ISSUE TITLE
Allow uploading more than one file to an item through the web client

### ISSUE THREAD

**Issue by manthey** [girder/girder#429]
We should add uploading additional files to an item to the UI.  Also, add a method to create Link Files.  The replace file contents on a Link File doesn't really make sense; this should edit the link.  There should also be a way to delete individual files.

**Comment by mgrauer** [comment]
@zachmullen 

Much of this exists now.  You can upload multiple files to an item through the web client and delete individual files of an item through the web client.

Is there currently a method to create Link Files?  When you said method did you mean API or web client?

**Comment by mgrauer** [comment]
@manthey wrote the original bug

**Comment by zachmullen** [comment]
We haven't done the link file stuff yet.

**Comment by manthey** [comment]
It's only link file support on the web client that is incomplete.  We could create a new, more specific issue and close this one, if you think that would be more obvious.

**Comment by mgrauer** [comment]
@manthey please do, thanks!  Seeing this issue as just a title hide what remains.

**Comment by manthey** [comment]
The undone part of this has been moved to issue #838.
