### ISSUE TITLE
Show folder size when possible

### ISSUE THREAD

**Issue by ronichoudhury** [girder/girder#454]
It would be cool to show how big a particular folder is, if it's possible to compute/store this information.

**Comment by brianhelba** [comment]
The folder info button now shows folder size, and I believe it includes the size of all subfolders. Is this issue now solved? @ronichoudhury @zachmullen

**Comment by zachmullen** [comment]
It does not include the contents of all subfolders, just the items directly underneath that folder.

**Comment by zachmullen** [comment]
I'm going to close this for now, if someone has concrete suggestions for this, let's reopen a ticket for them.
