### ISSUE TITLE
System consistency check

### ISSUE THREAD

**Issue by manthey** [girder/girder#496]
We should add a system consistency check.  This would perform a variety of tasks:

For each model, ensure documents within that model meet basic requirements.  For instance, items would have a folderId and that folderId exists in the system.  To be pedantic, we could check that each document can validate for that model.

For files, items, folders, and base parents, ensure that the size is correct.

For assetstores, ensure that all files (or chunks) are used.  Check for files and chunks that are not tracked.

I see having a progress context for this, as for any collection of significant size, it will be slow.  We should probably prevent two consistency checks from running concurrently.

Questions:

If a document fails to have the correct references or doesn't validate, what do we do with it?  Do we automatically delete it?  Move it to a lost+found area?

If an assetstore has files that aren't used, do we delete them or add them to a lost+found item?  Similarly, if there is a file that isn't in the database, do we add it to the database, ignore it, or delete it?

**Comment by danlamanna** [comment]
@manthey Did either of the referenced PRs resolve this?

**Comment by manthey** [comment]
@danlamanna I think this was still open as we never decided on the answer to the questions I posed.  I'll close.  We can open new issues if we ever care.
