### ISSUE TITLE
Notifications that are interrupted are never cleared

### ISSUE THREAD

**Issue by manthey** [girder/girder#502]
If you restart the girder server while a progress context is being updated (for instance, while deleting a large folder), the notification showing the progress at the time of the girder shutdown remains in the system and is never cleared.

We should either clear all notifications as we start or expire them after a while or clean them up in the consistency check.

**Comment by zachmullen** [comment]
Closing for now, we have a newer issue to address these notification messages, so we can move this discussion there.

**Comment by zachmullen** [comment]
See #1866
