### ISSUE TITLE
Girder docker container at girder/girder is broken

### ISSUE THREAD

**Issue by cpatrick** [girder/girder#522]
Building local works, but the autobuilder on dockerhub is unhappy with something.

**Comment by manthey** [comment]
@cpatrick Has this been taken care of?  In general, dockerhub seems happy with our Dockerfile.

**Comment by cpatrick** [comment]
@manthey yup, I think #662 fixes this.

**Comment by jeffbaumes** [comment]
@manthey I am also able to get this working fine - spun up Girder under Mesos/Singularity with Docker, yay!

**Comment by manthey** [comment]
Is there any reasonable way to add an automated test for the dockerhub file?  Perhaps as part of aiur nightly or something?
