### ISSUE TITLE
Ensure unicode support throughout

### ISSUE THREAD

**Issue by manthey** [girder/girder#526]
There are a few places where unicode data can cause problems.  For instance, some of the progress messages use python's `.format()`, which, when this includes a unicode string, can cause an error.  Test conditions should be added to test this, and any code that breaks should be fixed.

**Comment by zachmullen** [comment]
I'm going to close this ticket; we have live production instances with loads of multibyte characters that are running smoothly now, and we have a decent amount of testing in place that includes multibyte characters. If we find more specific unicode-related issues we should open new tickets for them.
