### ISSUE TITLE
update group model addUser docstring

### ISSUE THREAD

**Issue by mgrauer** [girder/girder#568]
Update the group model [addUser](https://github.com/girder/girder/blob/master/girder/models/group.py#L201-L221) method's docstring to warn that if the method is called when the user is already in the group, the call could have unintended consequences.

Calling this on a user already in a group with ADMIN or WRITE access, passing READ as param, will result in the user being removed from the group's user list.

**Comment by zachmullen** [comment]
If this is unresolved, please reopen.
