### ISSUE TITLE
Outstanding GirderClient capabilities

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#598]
From #582 

- [x] add callbacks for folder/item creation
- [x] implement upload folder as item
- [x] update docstrings on functions
- [x] Make sure we can upload into top level (collection or user)

**Comment by mgrauer** [comment]
- [ ] add scheme param to allow https

**Comment by zachmullen** [comment]
- [ ] resume upload and download (maybe on a separate topic)

**Comment by mgrauer** [comment]
I think we should push the resume onto a separate topic.  I'll write one up at some point soon with initial thoughts.

**Comment by mgrauer** [comment]
Now that this logic is somewhat substantial and stable, I want to test it.  For now I'm thinking about the upload functionality only with the following test cases:
- [ ] upload a tree to a folder parent, with metadata callbacks for items and folders
- [ ] upload a tree to a folder parent, with the leaf-folders-as-items option
- [ ] upload a tree to a user parent
- [ ] upload a tree to a collection parent
- [ ] upload an item to a user parent and fail
- [ ] upload an item to a collection parent and fail
- [ ] upload a leaf-folders-as-item to a user parent and fail
- [ ] upload a leaf-folders-as-item to a collection parent and fail
- [ ] upload a top level item to a folder parent
- [ ] use a partially existing tree, upload a tree with reuse-existing and ensure the tree is correct (should test partially reusing and existing tree and building on it)
