### ISSUE TITLE
Girder output doesn't use standard logging facilities

### ISSUE THREAD

**Issue by ronichoudhury** [girder/girder#602]
While figuring out just how to do logging for Tangelo, I discovered that, while CherryPy's "error" log (all log statements generated by calls to ``cherrypy.log()``) is by default written to stderr, but that some of Girder's output goes to stdout instead.  I came upon this when I saw that reports about Girder connecting to Mongo, etc., appear on stdout even as the rest of Tangelo's logs go to stderr.

The reason for this is that Girder, at least in that instance, uses ``print`` statements to make this report.  Should this be part of the logging output (either CherryPy's, or Python's) instead?

**Comment by zachmullen** [comment]
Probably. As long as our messages still appear in the console I am fine with changing this; having the colorful errors and warnings are kind of handy for development.

**Comment by ronichoudhury** [comment]
Colors are great.  In fact I poached the code to make rainbow logs into Tangelo :metal:

**Comment by manthey** [comment]
Added in PR #1505.
