### ISSUE TITLE
Size quota plugin: add user and collection-level defaults

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#605]
These will be two system settings that specify the quotas on collections and users where a specific quota has not yet been set. This is useful so that, e.g., new users registering in the system will automatically start out with a set size quota.

**Comment by manthey** [comment]
How do you think the quota dialog should expose allowing an unlimited quota versus setting a quota back to the default setting?  At the moment, a blank value goes to unlimited.

One option would be that if there is a system-wide, then no individual quota can be unlimited (it just has to be specified to be very large).

**Comment by zachmullen** [comment]
The way we did it before was:

![https://cloud.githubusercontent.com/assets/555959/5630770/bab7c522-958e-11e4-934d-ea519603b40f.png]()

**Comment by manthey** [comment]
Right-o.

**Comment by manthey** [comment]
Added in PR #603.
