### ISSUE TITLE
Uniform way to query for front-end URL

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#615]
Some of our instances will modify the path of the main girder web client to be something other than the webroot. When we send emails, for instance, we will need to know what that root is rather than assuming it's at /. I think this should be an app config property that a plugin will set whenever it moves the girder web app service path.

**Comment by manthey** [comment]
Do we need to expose this further than adding a value to the cfg file (and using it appropriately for email)?  Would server.client_root be an appropriate key?

I note that we don't have fall-back values for api_root and static_root.  I would think that the utility/server.py script should have default values in case the cfg file si missing them.

**Comment by zachmullen** [comment]
We need a way for plugins to dynamically update the property in cases where they relocate the core web app. The static specification of that root as a config parameter is somewhat orthogonal to that concern, though I could see it being useful. I need to think a bit more about how to do this right.

**Comment by manthey** [comment]
We should probably have a test that relocates the core web app.  I know there are external projects that do so, but perhaps we should have a test plugin that does so, too.

**Comment by zachmullen** [comment]
:+1:

**Comment by zachmullen** [comment]
@manthey I forgot about it, but we already have such a test. https://github.com/girder/girder/blob/master/tests/cases/custom_root_test.py

**Comment by manthey** [comment]
I had forgotten about that, too.  Interestingly, it is the one test that wasn't clearing its mongo database as it started.  I don't think this was causing any problems.

**Comment by manthey** [comment]
Should we be using the Referer header to try to glean this information instead of using a setting for it (or at least as a fallback if the setting hasn't been changed)?

**Comment by zachmullen** [comment]
That might be a good choice for the fallback.
