### ISSUE TITLE
Exceptions when loading plugins are not causing plugin to be disabled

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#618]
When loading a plugin that causes exceptions to be thown during module imports (before "load()" is actually called), the plugin may not always indicate its failure to load with a message in the plugin control panel. Additionally, these failed plugins remain enabled in the plugin control panel.

The exception causing this plugin failure may not be logged to the Girder log file, but rather sent to standard error.

**Comment by brianhelba** [comment]
More investigation is needed to reproduce this issue. I'll take a look when I can.

**Comment by zachmullen** [comment]
Some of these issues may remain, though at least we now log plugin load failures to the error log. If more changes are desired, let's reopen a new ticket for them.
