### ISSUE TITLE
girder-users mailing list

### ISSUE THREAD

**Issue by jeffbaumes** [girder/girder#628]
Is there one? Should we set one up?

**Comment by cpatrick** [comment]
We should.

**Comment by zachmullen** [comment]
I emailed sysadmin to create this. When it is created, we should change our contact info in the web app to include the new address.

**Comment by zachmullen** [comment]
http://public.kitware.com/mailman/listinfo/girder-users

**Comment by jeffbaumes** [comment]
Thx
