### ISSUE TITLE
Automatic parsing of JSON request bodies

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#632]
For HTTP requests with bodies (currently POST, PUT, PATCH), the body of any request with "Content-Type: application/x-www-form-urlencoded" (aka a POST form) is automatically parsed and passed to request handlers within the "params" argument. ( https://github.com/cherrypy/cherrypy/blob/3.3.0/cherrypy/_cpreqbody.py#L175 )

We should enable the same behavior for bodies of "Content-Type: application/json", but there are several decisions to be made:
- Do we enable this behavior for all routes in Girder, or only those under "/api/v1"? I'd suggest all routes, as it's consistant with the other request body processors, and it's likely a useful behavior for any other non-API endpoinds that plugins may create.
- Where do we store the parsed JSON data? There are several options:
  1) Put it in the magic "params" argument. This has several issues:
  - While a POST form is always nicely represented directly as a Python dict (with each key-value item equivalent to a name-value field), a JSON body could be an array. Where would we place this? Something like "params['json']" is even more magicical.
  - The "params" argument already stores both HTTP query string arguments and HTTP request bodies. In my opinion, this is a bit sloppy, as a request handler has no way to tell which source a "params" item came from. Additionally, if there are any repeated key names between the query string and the POST form, each corresponing "params" value becomes a list containing both values (something that Girder API handlers currently do not check for at all!). If anything, I think we should change this behavior for parsed POST forms too and provide the data via some other mechanism.
  
  2) Also solve ( https://github.com/girder/girder/issues/442 ) by making a new Resource method (say "getBody()") that returns the parsed JSON / parsed POST form / raw body, depending on the "Content-Type" of the request. However, this too has problems:
  - For request handlers that are not members of a class inheriting Resource, this method becomes inaccessable (unless we make it static, which is inconistant with how "Resource.getCurrentUser" et. al. are handled).
  - A request handler that expected "Resource.getBody()" to return some parsed Python datatype could instead get a raw string if the request wasn't of the proper "Content-Type". This misses a great oppertunity to move all of the JSON validation boilerplate (like https://github.com/girder/girder/blob/v1.2.0/girder/api/v1/item.py#L179 ) to a central place, as handlers still have to do an all-or-nothing check of whether the body was parsed at all and raise an exception if it wasn't.
  
  3) Put it in "cherrypy.request.json", which is CherryPy's default when you simply enable the "json_in" tool. This would be well-understood by native CherryPy users, but breaks the abstraction between Girder and CherryPy.
  
  4) Create a new optional magic named argument for request handlers, like "params".
  - If present, the argument (say "json") would indicate that the handler expects to recieve requests with a JSON body. If a request with an invalid JSON body or a different Content-Type were sent, a RestException with an appropriate message could automatically be raised before the handler is reached.
  - We could extend this to POST forms, (with, say, a "form" argument), solving the aforementioned issues with POST forms in "params".
  - For consistancy, we could make the "parms" argument be optional. If absent, any request with a query string argument could automatically cause a RestException. This simplifies most request handlers, which never expect query strings.
- Once better support for JSON bodies is in place, should Girder's HTTP API start accepting more parameters as JSON bodies rather than query strings. For example, requests to "PUT /api/v1/collections/access" must pass the "access" parameter as a query string, which can result in an excessively long HTTP resource and isn't very RESTful. It would be nice to optionally or even preferedly support these parameters as JSON bodies, like "PUT /api/v1/item/{id}/metadata" already does.

**Comment by zachmullen** [comment]
I like this idea.

> Do we enable this behavior for all routes in Girder, or only those under "/api/v1"? I'd suggest all routes, as it's consistant with the other request body processors, and it's likely a useful behavior for any other non-API endpoinds that plugins may create.

Since we want to encourage this sort of server interaction to go through the REST API, I'm OK with just implementing this within the `rest` module and having it only apply to the rest routes for now.

> Where do we store the parsed JSON data?

I'd say we don't store it, we lazily parse it when some abstraction method (probably in `rest.py`) gets called, and cache it on the request.

> For request handlers that are not members of a class inheriting Resource, this method becomes inaccessable (unless we make it static, which is inconistant with how "Resource.getCurrentUser" et. al. are handled).

We have static versions of `getCurrentUser` and `getCurrentToken`, and those are simply wrapped in the `Resource` class. We could do the same for this method.

> The "params" argument already stores both HTTP query string arguments and HTTP request bodies. In my opinion, this is a bit sloppy, as a request handler has no way to tell which source a "params" item came from. Additionally, if there are any repeated key names between the query string and the POST form, each corresponing "params" value becomes a list containing both values (something that Girder API handlers currently do not check for at all!). If anything, I think we should change this behavior for parsed POST forms too and provide the data via some other mechanism.

This is a convenience for us since the vast majority of the time, we don't care how the key value parameters were encoded in the HTTP request. More elegant support for the multi-key -> list transformation would certainly be good; we haven't used that feature yet, but even if we don't support it we should at least fail more gracefully or arbitrate that case.

For those rare cases when someone actually cares whether the param was a query parameter or form encoded, I think we should expose some utilities in the rest module for getting the query params and form params separately, and as you say further down, we should make the `params` kwarg optional on route handlers using `functools` introspection (or whatever the best way to do that is).

**Comment by zachmullen** [comment]
`autoDescribeRoute` gives us nice support for JSON parsing from both form/query params as well as the request body, including handling validation with jsonschema.
