### ISSUE TITLE
Support cookie-authenticated downloads

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#639]
We should make an exception to our normal authentication requirements for the download endpoints by allowing cookie-based auth so that it's easy for people to provide direct download links to private data that are consumable by web browsers. Since they're read-only operations, this won't be problematic wrt CSRF.

My use case is for COVALIC, where users who have access to a phase will be able to see user-created text containing download links to data that may be private.

**Comment by zachmullen** [comment]
I'll implement this by adding an optional kwarg called ``allowCookie=False`` to ``getCurrentUser`` and ``getCurrentToken`` in case we need to use this exception again.

**Comment by cpatrick** [comment]
:+1: This will also allow us to change many of the links to bitstream and item downloads with proper hrefs.
