### ISSUE TITLE
Uploading a new file to an existing item as a private user fails

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#657]
Here's an abbreviated stack trace:
* Upload.finalizeUpload https://github.com/girder/girder/blob/eaf0ff77afd0eb4fff78c7bcc214face128620c6/girder/models/upload.py#L112
* User.load(id=<private_user's_id>, level=AccessType.READ)
* AccessControlledModel.load(id=<private_user's_id>, level=AccessType.READ) https://github.com/girder/girder/blob/eaf0ff77afd0eb4fff78c7bcc214face128620c6/girder/models/model_base.py#L674
* AccessControlledModel.requireAccess(doc=<user_doc>, user=None, level=AccessType.READ) https://github.com/girder/girder/blob/eaf0ff77afd0eb4fff78c7bcc214face128620c6/girder/models/model_base.py#L632
* AccessControlledModel.requireAccess(doc=<user_doc>, user=None, level=AccessType.READ) https://github.com/girder/girder/blob/eaf0ff77afd0eb4fff78c7bcc214face128620c6/girder/models/model_base.py#L606
* returns False at this point, as "user" is None

**Comment by zachmullen** [comment]
Thanks @brianhelba , we haven't played around much with private users. Are you planning to fix this or should I?

**Comment by brianhelba** [comment]
I just pushed a fix in https://github.com/girder/girder/pull/658 .

However, a test for this behavior would be nice, and I'm not familar enough with the uploading test cases to quickly make one. If anyone else wants to add a commit with additional testing on top of my PR, it would be a welcome enhancement.

**Comment by brianhelba** [comment]
Assigned this to @zachmullen now.
