### ISSUE TITLE
Girder docker does not seem to be working

### ISSUE THREAD

**Issue by jeffbaumes** [girder/girder#661]
I get the following when attempting to use the Girder Docker container. This is running under Mesos and the mongo setup might not be correct, but it seems there is a more fundamental issue:

![screen shot 2015-01-28 at 3 09 28 pm](https://cloud.githubusercontent.com/assets/81305/5945992/653f6e28-a700-11e4-8658-d464379fc656.png)

**Comment by zachmullen** [comment]
Looks like grunt didn't get run.

**Comment by manthey** [comment]
Is this the same as issue #522?

Do we know how long this has been broken?

At some point, we removed an explicit call to `grunt init && grunt` since it was covered in the `npm install` step.  At the time, we wondered why we were doing it.  Could this have been the reason?
