### ISSUE TITLE
parseQueryString doesn't work as expected

### ISSUE THREAD

**Issue by manthey** [girder/girder#671]
I was expecting parseQueryString() to be the functional inverse of `jQuery's $.param()` function.  It is not, as it uses `decodeURI` on the *entire* string before splitting on `&` and subsplitting on `=`.  It should split on `&` before decoding, the split on `=` should use everything after the first `=` as the value, and the decode should be on the individual key and value using `decodeURIComponent`, not `decodeURI`.

Am I wrong about the intent of this function?  If so, it should be commented.  If not, it should be fixed.

**Comment by cpatrick** [comment]
@manthey I'm all for a fix as long as it doesn't break dialogs or routing. :smiley:

**Comment by manthey** [comment]
I'll submit a fix later today or tomorrow.  I have written a replacement function for another project I'm working on since the girder function didn't work.  I just have to consider how it should be tested.

**Comment by manthey** [comment]
Fixed in PR #676.
