### ISSUE TITLE
Group Moderators / Administrators are also listed as Group Members

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#673]
A user who is a Moderator or Administrator of a Group also shows up as a Member, which is confusing. The user should be listed only under the Moderator / Administraor section, and have the necessary promote / demote / remove icons as part of that single listing.

**Comment by manthey** [comment]
Should group moderators be able to ADD new members to a group, or only INVITE new members?

Also, why can moderators edit group properties?  It seems like that should be an admin power (to change, for instance, if a group is public or private).

**Comment by zachmullen** [comment]
Just invite. I think only site admins should be able to force a user into a group. I could be persuaded otherwise though if we have a good story.

I agree that only admin access should confer the ability to change properties like the public flag.

**Comment by manthey** [comment]
Also, a moderator can currently invite a new member to be a moderator, but doesn't have the power to raise (or demote) a member to moderator status.  It seems like either a moderator shouldn't be able to invite a user to be a moderator or should be able to promote (but then, would they be allowed to demote?).

**Comment by zachmullen** [comment]
We can change that policy to be more consistent, maybe just by restricting moderators to only inviting users as members.

**Comment by brianhelba** [comment]
@zachmullen @manthey This issue is a straightforward bug that should be fixed. However, group moderators being able to ADD members is something I have thoughts on as well. I'm going to create a seperate issue to discuss that.

**Comment by brianhelba** [comment]
See https://github.com/girder/girder/issues/690 for the ADD / INVITE issue.

**Comment by brianhelba** [comment]
@manthey @zachmullen While this issue is being fixed, it would be nice if some tooltips explaining what group "moderator" and "administrator" meant, outside of just the user invite dialog.

**Comment by zachmullen** [comment]
:+1:

**Comment by manthey** [comment]
Fixed in PR #701.
