### ISSUE TITLE
Group Moderators / Administrators should be able to add (not just invite) users

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#690]
Our use of Girder would benefit from allowing group moderators / administrators to directly add users to groups. If Girder can't / won't support this, I'll eventually want to add the functionality as part of our plugin. 
 
Our use case is that we have several "phases" in a data annotation pipeline. Each phase is administered and used by a separate group of people (some are clinicians, some are CV experts, etc.). There is also a clear hierarchy between phase administrators, who are trusted and appointed by us, and phase users, who have no site powers beyond group membership + read access. The phase administrators should be able to independently decide who needs to be a member of their group, without having to burden the ordinary users with all of the "invite+accept" stuff, which many of them have a hard time figuring out, due to their non-technical background.

**Comment by brianhelba** [comment]
I also totally see the use case where the group invite functionality is useful. In a more flat community, you wouldn't want a rogue group moderator to start adding random people from all over the site to the group.

However, maybe we could have a site configuration option to toggle this ability?

**Comment by brianhelba** [comment]
@zachmullen @manthey I'd be interested in your feedback here.

**Comment by zachmullen** [comment]
+1 for site config option or a small plugin that exposes this option. Would be nice to be able to set it on a per group basis as a site admin, but we could add that down the road.

**Comment by manthey** [comment]
I'm working on this code right now, so I can add this, too.

This is what I think the desired features and powers are:

Group admins can ADD or INVITE users to to be members, moderators, or admins.  Group admins can edit group properties and delete groups.

Group moderators can INVITE users to be members.  Group mods can NOT edit group properties.  Groups mods can NOT INVITE users to be moderators.

If a (new) group property of 'allow moderators to directly add members' is selected, then group moderators can ADD users to be members.

A (new) system config setting could determine the default of the group property for allowing mods to directly add members.

**Comment by brianhelba** [comment]
@manthey I really like this system. Not only is it a good compromise of the ADD / INVITE dilemma that doesn't involve a special config option, but it further delineates and clarifies the powers and roles of moderators and admins, which were a bit muddled before.

**Comment by zachmullen** [comment]
I still think the default should be that only site-level admins can add a user to a group directly (since technically that's changing a property of the user without their permission), and that the system-level setting can add that power to group admins and/or moderators. ping @girder/developers @girder/owners for consensus.

**Comment by jcfr** [comment]
+1

On Tue, Feb 10, 2015 at 10:58 AM, Zach Mullen <notifications@github.com>
wrote:

> I still think the default should be that only site-level admins can add a
> user to a group directly (since technically that's changing a property of
> the user without their permission), and that the system-level setting can
> add that power to group admins and/or moderators. ping @girder/developers
> <https://github.com/orgs/girder/teams/developers> @girder/owners
> <https://github.com/orgs/girder/teams/owners> for consensus.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/girder/girder/issues/690#issuecomment-73724828>.
>



-- 
+1 919 869 8849

**Comment by zachmullen** [comment]
To motivate my opinion: I am thinking about groups as more than just a mechanism for RBAC. I want them to be the go-to tool for any grouping of users imaginable, for example like facebook groups that are used for social networking organization and communication. Of course, that type of flexibility should be balanced as much as possible with making them easy for people to use for their normal RBAC. So the question should be framed as how can we achieve both of those goals as seamlessly as possible.

**Comment by manthey** [comment]
Okay, here's my next attempt to satisfy these desires:

Group admins can INVITE users to be members, moderators, or admins. Group admins can edit group properties and delete groups.

Group moderators can INVITE users to be members. Group mods can NOT edit group properties. Groups mods can NOT INVITE users to be moderators.

System admins act as group admins AND can ADD users as members, moderators, or admins.  System admins can edit group properties and delete groups.

A (new) system config setting determines IF admins and optionally mods can ADD members and the default on a per-group basis for this setting.  That is, the setting "Allow members to be directly added to groups" would default to "Never - members must be invited and accept invitations", and have the additional options "No, except by group admins when enabled per group", "No, except by group admins and mods when enabled per group", "Yes, by group admins unless disabled per group", "Yes, by group admins and mods unless disabled per group".

If the system setting isn't "never", a (new) group property of "Allow members to be directly added to groups" would exist with the options of "Never - members must be invited and accept invitions", "Allow group admins to directly add members", "Allow group admins and moderators to directly add members" [the last option only exists under the appropriate system-wide setting].

**Comment by zachmullen** [comment]
:+1: Sounds like an ideal solution to me.

**Comment by brianhelba** [comment]
@manthey +1 sounds great for my application's needs.

I question whether having 5 different values for the config option isn't too complex, but if you can make the programming work reasonably, I think site administrators could understand it. The upside is the amount of flexability it will give us, especially with @zachmullen 's vision of groups with broad semantic value.

**Comment by manthey** [comment]
Added in PR #707.
