### ISSUE TITLE
Prefer href rather than event binding where possible

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#709]
We have places in the web client where we have an element where we bind a click action that basically just calls navigate on the router to another page. We should instead just set the fragment as the href of those links where it makes sense to do so, which will allow users to see the URL appear in their browser when they hover, and do things like open link in new tab, copy link address, etc.

**Comment by brianhelba** [comment]
+1

**Comment by cpatrick** [comment]
+1000

-Patrick

**Comment by jcfr** [comment]
:+1:

**Comment by manthey** [comment]
This was largely done.  I'm closing the issue.
