### ISSUE TITLE
Enhance style tests to detect variable names which shadow Python builtins

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#717]
There are a number of places in the Python code that define variables "id", "hash", etc. These override Python builtin functions which are always in the namespace, which is a bad practice.

In addition to renaming the variables, we need the style tests to warn about this issue. Unfortunately, Flake8 does not appear to have a checker for this. Other style checking tools may need to be utilized.

**Comment by zachmullen** [comment]
Too many builtins ... took all the good names :tongue:

**Comment by zachmullen** [comment]
I think this only matters for publicly visible symbols, which we can't really change for compatibility reasons. We have these in a lot of places, the two that come to mind are `file` and `id`, both of which are fairly obscure builtins that people don't use very often.

For now, I'm going to close this -- in the rare cases where we might run into a shadowing issue when needing to use a builtin, there are workarounds.
