### ISSUE TITLE
add recursive permission setting to python cli

### ISSUE THREAD

**Issue by mgrauer** [girder/girder#751]
- [ ] add recursive permission setting as an additional cli command
- [ ] change the documentation to a cli invocation (currently programmatic, and only 4ish lines)
- [ ] add a test

**Comment by mgrauer** [comment]
This can be made much simpler once #811 gets merged.  Just calling an API endpoint.

**Comment by zachmullen** [comment]
Please re-open this if you think we should have more first-class support for this in the CLI.
