### ISSUE TITLE
Investigate gulp build system

### ISSUE THREAD

**Issue by jeffbaumes** [girder/girder#754]
Low priority. I've used it a bit and like it, but these slides

http://markdalgleish.github.io/presentation-build-wars-gulp-vs-grunt

both promote gulp as the future and yet also say it's not entirely ready for prime time. Not clear to me yet whether gulp will take over the world.

**Comment by brianhelba** [comment]
@jbeezley @zachmullen Do we know anything more now, 10 months later, that we can add to this issue?

**Comment by zachmullen** [comment]
We've talked about this as a possible 2.0 technology to investigate, but as of right now we are pretty entrenched in grunt. I'm going to close this for now to reduce noise on our issue tracker, but if someone feels strongly about this they can re-open.
