### ISSUE TITLE
Check if jscs and jshint supports settings "inheritance"

### ISSUE THREAD

**Issue by jcfr** [girder/girder#761]
See https://github.com/girder/girder/pull/756#issuecomment-85244512 and https://github.com/girder/girder/commit/df26dcab15f588a603419545dd5bf35aa8392df1#commitcomment-10270055 for more details

**Comment by brianhelba** [comment]
@jcfr @jbeezley Do we need to keep this, now that jshint is deprecated?

**Comment by jbeezley** [comment]
Yes, I think we can close it.

**Comment by brianhelba** [comment]
@jbeezley I'll let you to so.
