### ISSUE TITLE
Add tagged version to dockerhub as part of release process

### ISSUE THREAD

**Issue by jbeezley** [girder/girder#786]
This will make it possible to do:

```
docker run girder/girder:v1.2.1
```

etc.

Tagging _should_ be as easy as

```
docker build -t girder/girder:<version> .
docker push girder/girder
```

**Comment by zachmullen** [comment]
This seems like a good idea for sure, @jbeezley would you like to add this to the release docs?

**Comment by jbeezley** [comment]
@danlamanna was working this earlier.  Perhaps he could formalize the procedure.
