### ISSUE TITLE
Recent changes cause OAuth login error

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#796]
After upgrading from v1.2.4 to the latest master, then logging in for the first time with the Google OAuth plugin, I get a 500 error. Subsequent OAuth logins after this work fine.

Traceback (most recent call last):
  File "girder/api/rest.py", line 277, in endpointDecorator
    val = fun(self, args, kwargs)
  File "girder/api/rest.py", line 854, in GET
    return self.handleRoute('GET', path, params)
  File "girder/api/rest.py", line 635, in handleRoute
    val = handler(**kwargs)
  File "girder/api/access.py", line 62, in accessDecorator
    return fun(*args, **kwargs)
  File "/home/ubuntu/girder/plugins/oauth/server/rest.py", line 86, in googleCallback
    self._validateCsrfToken(redirect)
  File "/home/ubuntu/girder/plugins/oauth/server/rest.py", line 128, in _validateCsrfToken
    raise Exception('No CSRF cookie (state="{}").'.format(redirect))
Exception: No CSRF cookie (state="https://demo.uda2study.com/#group/54c5eb21765a3634b739794f/roles").
Additional info:
  Request URL: GET https://demo.uda2study.com/api/v1/oauth/google/callback
  Query string: state=https://demo.uda2study.com/%23group/54c5eb21765a3634b739794f/roles&code=...

**Comment by zachmullen** [comment]
I just enabled this plugin on latest master and logged in both as a new user and existing user w/ Google Oauth but could not reproduce this. The CSRF token does expire after 6 hours, did you have the google page open for several hours before accepting?

I think this is a bug either way -- we should show a more user-friendly error message and a 401 instead of a 500, something like "Your temporary login session has expired, please restart the login."

**Comment by brianhelba** [comment]
I was able to reproduce this twice, on two different deployments. Additionally, I recall that the login process actually succeeded, but threw up the 500 error page anyway.

I'll do some additional testing and get back with more information.

**Comment by zachmullen** [comment]
> Additionally, I recall that the login process actually succeeded, but threw up the 500 error page anyway.

If that's true, it would have to be hitting the callback twice -- once where it succeeds (and deletes the cookie) and once afterwards where it fails because the cookie was deleted. Can you describe your deployments? Are they behind a proxy?

**Comment by brianhelba** [comment]
Yes, it's behind Nginx.

@zachmullen , I'm going to be traveling / busy for the rest of the day, so please excuse if I'm slow on further responses.

**Comment by zachmullen** [comment]
If it's possible to reproduce this error condition again, can you capture your browser's network console list and see all the requests that it makes during the login process?

**Comment by brianhelba** [comment]
Upon further testing, I've been unable to reproduce this. For future reference, the error produced was:
[2015-04-15 11:49:22,209] ERROR: 500 Error
Traceback (most recent call last):
  File "girder/api/rest.py", line 277, in endpointDecorator
    val = fun(self, args, kwargs)
  File "girder/api/rest.py", line 854, in GET
    return self.handleRoute('GET', path, params)
  File "girder/api/rest.py", line 635, in handleRoute
    val = handler(**kwargs)
  File "girder/api/access.py", line 62, in accessDecorator
    return fun(*args, **kwargs)
  File "/home/ubuntu/girder/plugins/oauth/server/rest.py", line 86, in googleCallback
    self._validateCsrfToken(redirect)
  File "/home/ubuntu/girder/plugins/oauth/server/rest.py", line 128, in _validateCsrfToken
    raise Exception('No CSRF cookie (state="{}").'.format(redirect))
Exception: No CSRF cookie (state="https://demo.uda2study.com/#group/54c5eb21765a3634b739794f/roles").
Additional info:
  Request URL: GET https://demo.uda2study.com/api/v1/oauth/google/callback
  Query string: state=https://demo.uda2study.com/%23group/54c5eb21765a3634b739794f/roles&code=<redacted>
  Remote IP: <redacted>

Closing this issue.
