### ISSUE TITLE
document JSHINT_EXTRA_CONFIGS and JSSTYLE_EXTRA_CONFIGS 

### ISSUE THREAD

**Issue by mgrauer** [girder/girder#800]
Makes the most sense to document this in the plugin development section of the docs.  

Show how you would use this in a plugin.

**Comment by brianhelba** [comment]
@mgrauer @jbeezley Do we need to keep this, now that jshint is deprecated?

**Comment by jbeezley** [comment]
Maybe, but this issue is still relevant "in spirit".  I can add some docs to my PR to explain how to extend the config.
