### ISSUE TITLE
Girder is not mobile-friendly

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#801]
While uploading / downloading of files is less likely to occur with users on mobile devices (tablets / phones), there may be uses where mobile devices are used to browse folders / items or where plugins provide additional functionality that users on mobile devices may want to access.

Currently, Girder is failing [Google's Mobile-Friendly Test](https://www.google.com/webmasters/tools/mobile-friendly/?url=http%3A%2F%2Fgirder-test.herokuapp.com%2F). There also may be other mobile-friendliness metrics we should test against.

**Comment by zachmullen** [comment]
:+1: I noticed it did look rather ugly on my phone.
