### ISSUE TITLE
girder_client: Multi-page responses for list methods

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#802]
We should support a page-based streaming API for our listing methods. Right now you can't specify paging params to the more abstract list methods; we should change them so they return generators that will keep fetching pages dynamically as long as iteration continues.

**Comment by brianhelba** [comment]
@zachmullen I'm pretty sure this is now fixed by the fact that the model layer now returns iterators (with ``limit=0`` by default) wherever possible. Is this was you were referring to here?

**Comment by brianhelba** [comment]
Nevermind, I didn't see the tag for ``girder_client``.

**Comment by zachmullen** [comment]
This was implemented at some point in `GirderClient.listResource`.
