### ISSUE TITLE
girder_client: token kwarg for `authenticate()`

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#803]
You can sort of do this already by calling `client.token = ...`, but it would be better if we either expose a `token` kwarg on `authenticate()` that could be used instead of username and password, or simply create an alternative method called `authenticateWithToken()`.

**Comment by jcfr** [comment]
:+1:  Where can I get the token from the current girder UI ?

**Comment by zachmullen** [comment]
Closing this for now, `client.token = ...` is relatively pythonic and not so bad really.

**Comment by danlamanna** [comment]
This behavior took me off guard (only for a moment)... but talking with others I found out it confused them as well.

Not that `client.token` is difficult, but being totally undocumented and not part of the authentication function (which we have a level of compatibility for) is counter intuitive.

**Comment by zachmullen** [comment]
Setting the token directly is a bit of an edge case for usage of girder_client. Doing so means you've somehow used a different client to obtain a token. The prescribed ways of authentication for the client are to use a username/password or an API key. What is the use case for wanting to create the token yourself?

**Comment by danlamanna** [comment]
When I schedule jobs I create a token with the specific scope needed for the job, and pass that along. So the job uses the token when it uses Girder client.

**Comment by zachmullen** [comment]
Fair enough. I will reopen this, but it's quite an old issue -- does someone have time to actually add this in soon?
