### ISSUE TITLE
Modular javascript libs

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#805]
Rather than build everything into a single JS file (app.min.js), we should divide it up into more files so people can import useful subsets of javascript functionality. I would propose the following:
- `girder.core.min.js`: all the utilities (init, misc functions, etc. All others would depend on this)
- `girder.models.min.js`: models (in case someone wants to build their own widgets
- `girder.widgets.min.js`: stuff inside views/widgets, meant for embedding inside other custom apps
- `girder.app.min.js`: everything else (the main app, layout stuff, and other views). Most custom apps would not need to import this file at all.

**Comment by zachmullen** [comment]
And while we are breaking js import compatibility, I would rename `libs.min.js` to `girder.ext.min.js`.

**Comment by jeffbaumes** [comment]
+1: rename `libs.min.js` to `girder.ext.min.js`.

**Comment by ronichoudhury** [comment]
+7

**Comment by cjh1** [comment]
@zachmullen Would the files that depend on girder.core.min.js load it automatically or would the user have to include it manually?

**Comment by zachmullen** [comment]
@cjh1 It might make sense to investigate using require.js or something similar when we do this. We could also preserve backward compatibility by adding an additional grunt step that built stuff under the old names, though I would remove such a task from the default task graph.

**Comment by manthey** [comment]
I like the idea of using require.js or similar so that when I want both girder and another package that both include the same external library, I only get it once.

**Comment by cjh1** [comment]
I have looked a requires.js a couple of times and every time was scared off by the changes that would be required to use it in an existing application, but I may have missed something. I would be interesting in other peoples opinions ...

**Comment by jeffbaumes** [comment]
I assume we would use browserify with require. I saw it being used with good success in a BioJS tutorial.

**Comment by cpatrick** [comment]
+1 to something like require.js and +1 to changing the name. I'm a little nervous about how this affects our version... We need to make sure all users of JS things know of the change.

**Comment by jbeezley** [comment]
It will probably require a significant change to do right.  This is what scared me away when I last looked at it.  I think you need to wrap all of your js modules into functions that look like this

```javascript
require(['dep1', 'dep2'], function (dep1, dep2) {
});
```

It might be worth it to look into ES6 shims that perform the same function if you are going to do this.

**Comment by zachmullen** [comment]
Yeah, it's a sizeable undertaking; I'm not sure how it would play with our minification since we have a disconnect between modules and files.

**Comment by zachmullen** [comment]
Answered my own concern; they have their own require-aware minifier that we would have to use instead of uglify.

**Comment by brianhelba** [comment]
@girder/developers Before we merge https://github.com/girder/girder/pull/1161 , does anyone care if we call the plugins file ``girder.ext.min.js`` instead of ``ext.min.js``? If we want to, now's the perfect time to change it.

**Comment by mgrauer** [comment]
@brianhelba I think that would improve clarity, as long as it's an easy change, i.e. I'm in favor of `girder.ext.min.js`.

**Comment by mgrauer** [comment]
And it would make sense to do the same with the css if possible.

**Comment by zachmullen** [comment]
Fine by me, so long as we keep symlinks to the old names as well.

**Comment by brianhelba** [comment]
Want me to rename ``app.min.js`` and ``app.min.css`` too?

**Comment by zachmullen** [comment]
Yes, we should definitely keep the naming consistent.

**Comment by brianhelba** [comment]
What exactly do you want to call them? I have no opinions of my own on this.

**Comment by zachmullen** [comment]
Just add "girder." in front like you suggested for ext.min.js.

**Comment by brianhelba** [comment]
I've updated https://github.com/girder/girder/pull/1161/files to effectively rename:
``app.min.js`` -> ``girder.app.min.js``
``app.min.css`` -> ``girder.app.min.css``
``main.min.js`` -> ``girder.main.min.js``
``libs.min.js`` -> ``girder.ext.min.js``
``ext.min.css`` -> ``girder.ext.min.css``
