### ISSUE TITLE
Folder find api endpoint documentation for search by parent with text

### ISSUE THREAD

**Issue by mgrauer** [girder/girder#806]
Looking at the documentation for the [folder find api endpoint](https://github.com/girder/girder/blob/master/girder/api/v1/folder.py#L50-L64), it wasn't clear to me that you can perform a search under a parent including a fulltext field, whereas you clearly can given the code.  Update the documentation to clarify this point, and add the `text` param to the docstring.

**Comment by zachmullen** [comment]
This is mentioned in the docstring for that function, is that sufficient? If not, please re-open.
