### ISSUE TITLE
make it harder to delete all your data

### ISSUE THREAD

**Issue by mgrauer** [girder/girder#809]
This might be a UI issue, or an issue with confirm vs redo, or maybe we should have a dry-run of notifications on delete in the progress area, I'm open to ideas.

I was in a hierarchy view, and selected a folder, then instead of clicking delete directly above that checkbox for the folder I had selected, I clicked the delete action on the right and clicked to confirm without even reading the confirmation, and then this deleted the parent folder.

**Comment by ronichoudhury** [comment]
+7 for undo in general.

Also, maybe I misunderstood, but why does selecting a delete action for a particular folder delete its *parent* folder?

**Comment by manthey** [comment]
I have an idea to extend what we do with provenance that would give full
undo capability.  Perhaps there should be a light-weight version that just
provides a limited number of undo levels.


On Fri, Apr 24, 2015 at 4:32 PM, Roni Choudhury <notifications@github.com>
wrote:

> +7 for undo in general.
>
> Also, maybe I misunderstood, but why does selecting a delete action for a
> particular folder delete its *parent* folder?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/girder/girder/issues/809#issuecomment-96055981>.
>



-- 
David Manthey
R&D Engineer
Kitware Inc.
(518) 881-4439

**Comment by mgrauer** [comment]
I wanted to do this sort of delete, which would delete the folder.

![screen shot 2015-04-24 at 5 23 03 pm](https://cloud.githubusercontent.com/assets/595023/7328826/a4c4146a-eaa6-11e4-82c5-b1a8dc5ac207.png)

Instead (probably I was distracted) I did this sort delete by accident, which deletes the parent folder.


![screen shot 2015-04-24 at 5 22 47 pm](https://cloud.githubusercontent.com/assets/595023/7328828/aa5ff286-eaa6-11e4-83e3-6743dde5585c.png)

**Comment by ronichoudhury** [comment]
Oh wow, I see.  Is there a case to be made that the delete action in that right-side dropdown should really only be possible by explicitly going up one directory, then using the checkboxes and left-side dropdown?  The use of the word "this" in the right-side menu is technically unambiguous, but the sequence of actions you took here is really very natural, where your mind just matches up the word "this" to the singleton-set of checked items you just created on the left.

**Comment by ronichoudhury** [comment]
Oh and, regarding your being "probably distracted" - http://www.azarask.in/blog/post/not-the-users-fault-manifesto/ (more from Aza Raskin).

**Comment by manthey** [comment]
I think UNDO is highly desirable regardless of other UI changes.

One of the UI issues is that we are constantly being asked to confirm
actions, so it becomes automatic to confirm any action.  I once watched a
user go through four confirmation dialogs on her way to dropping a database
that she really didn't want to drop.

On Mon, Apr 27, 2015 at 11:37 AM, Roni Choudhury <notifications@github.com>
wrote:

> Oh and, regarding your being "probably distracted" -
> http://www.azarask.in/blog/post/not-the-users-fault-manifesto/ (more from
> Aza Raskin).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/girder/girder/issues/809#issuecomment-96714080>.
>



-- 
David Manthey
R&D Engineer
Kitware Inc.
(518) 881-4439

**Comment by ronichoudhury** [comment]
+43.  Google got this idea exactly right.

**Comment by brianhelba** [comment]
+1 also, to allow the user to "ask for forgiveness rather than permission". Robust undo is a much better user experience than confirmations on everything.

@ronichoudhury, Google, [Amazon](http://i.stack.imgur.com/6ceeN.gif), and [Microsoft in 2005](https://msdn.microsoft.com/en-us/magazine/cc163835.aspx) all agree.

**Comment by cpatrick** [comment]
To follow up a meatspace conversation we had yesterday. The options seem to be (ordered by implementation difficulty).

1) Small UI change to guard against accidental delete.
2) Some sort of locking concept (not a fan of this one)
3) Recycle-bin style undo
4) Full undo-redo.

It sounds like the best way forward from the discussion here is to do 1 and then do 3. By causing "delete" to move the resources into the user's "deleted" space, we can implement undo a la gmail.
