### ISSUE TITLE
Display public/private icon for collection

### ISSUE THREAD

**Issue by mgrauer** [girder/girder#815]
Currently the only way to tell from the web client UI whether a collection is public/private is to go into the access control on that collection.  It would be great to tell at a glance in the collection list and collection page, the same way as with folders in the hierarchy view.

Now that I look at the folders, it would be good to add this to the folder view.

I'd like to see the public/private icon in this view (collections list) for the collections

![screen shot 2015-04-29 at 4 37 17 pm](https://cloud.githubusercontent.com/assets/595023/7400960/8c06fa50-ee8e-11e4-9cb4-381d1434a7ad.png)

In this view (hierarchy view) for the collection

![screen shot 2015-04-29 at 4 41 23 pm](https://cloud.githubusercontent.com/assets/595023/7401021/c97f1890-ee8e-11e4-867e-8f1ce6f06a9a.png)

And in this view (hierarchy view) for the folder

![screen shot 2015-04-29 at 4 41 48 pm](https://cloud.githubusercontent.com/assets/595023/7401026/cfcd8c7c-ee8e-11e4-8324-12a4bfcb00a4.png)

**Comment by brianhelba** [comment]
+1

@girder/developers If anyone has time to work on this, I have funding.

**Comment by manthey** [comment]
This was added in PR #1376.

**Comment by jcfr** [comment]
Nice :+1:
