### ISSUE TITLE
Girder attempting to set read-only type property on Blob objects

### ISSUE THREAD

**Issue by jeffbaumes** [girder/girder#829]
According to

https://developer.mozilla.org/en-US/docs/Web/API/Blob

the `type` field is read only, but we are setting it here:

https://github.com/girder/girder/blame/3cd83a3/clients/web/src/models/FileModel.js#L55

I cannot reproduce the error being thrown on my browser/versions of Chrome, Firefox, and Safari but @curtislisle is hitting this in a client app Kitware/tangelohub#145. But even on all my browsers I can see that `type` is unaffected when trying to set it, so it is reproducible in that way everywhere. His browser seems to be using a getter for a read-only property:

http://javascriptplayground.com/blog/2013/12/es5-getters-setters/

I did not even know such things existed in JavaScript.

**Comment by ronichoudhury** [comment]
I think the way to fix this is to make ``type`` a parameter to the ``_wrapData()`` method, and pass it to the ``Blob`` constructor there [0].  The only downside to this is, if the data being wrapped is *already* a ``Blob``, then that ``type`` will have no effect, though the user may expect it to (although, of course, right now it has no effect whatsoever, so this is probably still an improvement :smirk_cat:).

@zachmullen, what do you think?

[0] https://github.com/girder/girder/blame/3cd83a3/clients/web/src/models/FileModel.js#L12

**Comment by zachmullen** [comment]
That sounds good to me.

**Comment by mgrauer** [comment]
I just ran into this too, creating a JSON object in the browser and saving it as a File in an Item, setting `application/json` as the MIME type, but the File shows `application/octet-stream`.

I also noticed that [this line](https://github.com/girder/girder/blob/master/clients/web/src/models/FileModel.js#L45) seems unused.  If so, can we remove it as part of fixing this issue?  Or if for a side effect, can it be explained?

**Comment by ronichoudhury** [comment]
Not sure why that line is there, @mgrauer.  I don't believe ``.toString()``
is supposed to have any sort of side effects.

**Comment by zachmullen** [comment]
Kind of disappointing that jshint didn't catch that unread variable, given how they are trying to sell themselves as a static analysis tool and not a style checker now :unamused:

**Comment by manthey** [comment]
We don't have "unused": true in our jshint.cfg file.

On Mon, May 11, 2015 at 3:17 PM, Zach Mullen <notifications@github.com>
wrote:

> Kind of disappointing that jshint didn't catch that unread variable, given
> how they are trying to sell themselves as a static analysis tool and not a
> style checker now [image: :unamused:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/girder/girder/issues/829#issuecomment-101021545>.
>



-- 
David Manthey
R&D Engineer
Kitware Inc.
(518) 881-4439

**Comment by zachmullen** [comment]
Good call, we should add that.

**Comment by manthey** [comment]
Will do, unless someone else is already doing so.

On Mon, May 11, 2015 at 3:24 PM, Zach Mullen <notifications@github.com>
wrote:

> Good call, we should add that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/girder/girder/issues/829#issuecomment-101024191>.
>



-- 
David Manthey
R&D Engineer
Kitware Inc.
(518) 881-4439
