### ISSUE TITLE
Internal server error when trying to authenticate with user/password

### ISSUE THREAD

**Issue by jbeezley** [girder/girder#835]
If you have an account created by OAuth and try to log in via username/password, you get an internal server error.  This should probably be handled more gracefully.  On a related note, is it possible to use the girder python client with an OAuth account?

```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
/static/built/app.min.js:4 500 Internal Server Error 

    "message": "KeyError: KeyError('hashAlg',)",
    "trace": [
        [
            "girder/api/rest.py",
            277,
            "endpointDecorator",
            "val = fun(self, args, kwargs)"
        ],
        [
            "girder/api/rest.py",
            855,
            "GET",
            "return self.handleRoute('GET', path, params)"
        ],
        [
            "girder/api/rest.py",
            636,
            "handleRoute",
            "val = handler(**kwargs)"
        ],
        [
            "girder/api/access.py",
            62,
            "accessDecorator",
            "return fun(*args, **kwargs)"
        ],
        [
            "girder/api/v1/user.py",
            139,
            "login",
            "if not self.model('password').authenticate(user, password):"
        ],
        [
            "girder/models/password.py",
            90,
            "authenticate",
            "hash = self._digest(salt=user['salt'], alg=user['hashAlg'],"
        ]
    ],
    "type": "internal"
}
```

**Comment by zachmullen** [comment]
dup of #820

**Comment by jbeezley** [comment]
Hmmm, so girder has evolved to the point that I need to search issues before submitting?  :)

**Comment by zachmullen** [comment]
@jbeezley to answer your question, no you cannot use oauth with the python client. OAuth 2.0 requires the user to use a browser to authenticate, so I'm not sure we'll be able to support that; Google's recommendation is to print out a URL and tell the user to go there with their browser :smile:

https://developers.google.com/identity/protocols/OAuth2ForDevices

**Comment by jbeezley** [comment]
Okay good to know.  Part of me wants to try to make it work with lynx.  :wink:

**Comment by zachmullen** [comment]
Ha! That could be fun.
