### ISSUE TITLE
Silently ignoring exceptions when reading requirements files

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#847]
The following logic is present for both of our setup.py scripts:

```
try:
    install_reqs = parse_requirements(open('requirements.txt').read())
except Exception:
    pass
```

@jbeezley what's the reason for silently ignoring the exceptions here? Is this something we should change?

**Comment by jbeezley** [comment]
I don't think there is a good reason for that.  I'm not sure why I put it there beyond being skeptical that `parse_requirements` would always work.  I would say get rid of the try block, and we can fix problems with specific versions of `setuptools` as they arise.

**Comment by brianhelba** [comment]
@jbeezley Is this still relevant, in light of your more recent changes?

**Comment by jbeezley** [comment]
No longer relevant.
