### ISSUE TITLE
Error during jshint config merge

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#854]
@aashish24 ran into the following error:

```
CMake Error at scripts/JsonConfigMerge.cmake:32 (message):
  Failed to merge config files:
  /home/chaudhary/tools/girder/src.git/tests/jshint.cfg;/home/chaudhary/tools/girder/src.git/scripts/.jshintrc
Call Stack (most recent call first):
  tests/JavascriptTests.cmake:32 (json_config_merge)
  scripts/tests/CMakeLists.txt:2 (add_javascript_style_test)
```

ping @jcfr

**Comment by aashish24** [comment]
Looks like it came from failed to meet certain dependencies. Although the error message was not very helpful as I had all the files related to style tests existed in my clone. After re-installing all of the dependencies in my virtualenv I didn't run into this problem again.
