### ISSUE TITLE
Enable Grunt option to use local font files

### ISSUE THREAD

**Issue by jeffbaumes** [girder/girder#856]
This would enable an entirely local deploy.

**Comment by brianhelba** [comment]
To clarify, the [sourcing of the `//fonts.googleapis.com/css?family=Droid+Sans:400,700` stylesheet](https://github.com/girder/girder/blob/b8b66fe2d5662fe93fe378b6c6fab1c8e4bdef8a/girder/utility/webroot.mako#L6) needs to be replaced with a local copy of the same or equivalent files.

**Comment by manthey** [comment]
There is an npm package called "google-fonts-offline" which I've used before which can do this.

**Comment by zachmullen** [comment]
This is now supported via an env var.
