### ISSUE TITLE
Ansible installer broken (and therefore vagrant is broken)

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#861]
```
NOTIFIED: [restart mongodb] *************************************************** 
<127.0.0.1> ESTABLISH CONNECTION FOR USER: vagrant
<127.0.0.1> REMOTE_MODULE service name=mongodb pattern=/etc/init.d/mongodb state=restarted enabled=yes
<127.0.0.1> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/zach/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=2222', '-o', 'IdentityFile="/Users/zach/.vagrant.d/insecure_private_key"', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=vagrant', '-o', 'ConnectTimeout=10', '127.0.0.1', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1434391288.79-128676736986602 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1434391288.79-128676736986602 && echo $HOME/.ansible/tmp/ansible-tmp-1434391288.79-128676736986602'"]
<127.0.0.1> PUT /var/folders/0s/12m4th657gd224y3ypp5vxk80000gn/T/tmpPCZOjs TO /home/vagrant/.ansible/tmp/ansible-tmp-1434391288.79-128676736986602/service
<127.0.0.1> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/Users/zach/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'StrictHostKeyChecking=no', '-o', 'Port=2222', '-o', 'IdentityFile="/Users/zach/.vagrant.d/insecure_private_key"', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=vagrant', '-o', 'ConnectTimeout=10', '127.0.0.1', u"/bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1434391288.79-128676736986602/service; rm -rf /home/vagrant/.ansible/tmp/ansible-tmp-1434391288.79-128676736986602/ >/dev/null 2>&1'"]
failed: [default] => {"failed": true}
msg: stop: Rejected send message, 1 matched rules; type="method_call", sender=":1.45" (uid=1000 pid=6756 comm="stop mongodb ") interface="com.ubuntu.Upstart0_6.Job" member="Stop" error name="(unset)" requested_reply="0" destination="com.ubuntu.Upstart" (uid=0 pid=1 comm="/sbin/init ")
start: Rejected send message, 1 matched rules; type="method_call", sender=":1.47" (uid=1000 pid=6765 comm="start mongodb ") interface="com.ubuntu.Upstart0_6.Job" member="Start" error name="(unset)" requested_reply="0" destination="com.ubuntu.Upstart" (uid=0 pid=1 comm="/sbin/init ")
```

**Comment by brianhelba** [comment]
@zachmullen I'll be happy to fix this by replacing large parts of it. I'm just finishing a new Vagrant + Ansible configuration for my plugin, and most of it can probably be contributed back upstream. Also, we should unify this with some of the Ansible scripts from the COVALIC repo.

However, in the slightly longer term, I'd like to have each part of the Ansible scripts live in only 1 place, then have plugins fetch other parts of the script via this upstream location, probably using a mechanism like http://docs.ansible.com/galaxy.html#advanced-control-over-role-requirements-files . I'm not sure if this will be possible using *pure* Ansible, without any helper scripts, but it should make things much more maintainable.

**Comment by zachmullen** [comment]
That sounds great. :+1:

**Comment by cpatrick** [comment]
@brianhelba Thanks for picking up this torch. :fire_engine: 

@mgrauer worked on the COVALIC stuff heavily, so y'all should probably talk.

**Comment by brianhelba** [comment]
@cpatrick @zachmullen  I see you have some nice role-based Ansible scripts in https://github.com/crad/infrastructure

I also have some role-based scripts in https://github.com/ImageMarkup/isic-archive (mine has support for multiple Python backends, including system-installed, virtualenvs, and Anaconda), and a setup for an Nginx and Superviser server to serve and run Girder (though this bit need a bit more work to be totally general).

I also know that https://github.com/girder/covalic has its own scripts which again do the same (thought maybe some was copy-pasted into crad?)

I'm hoping we can start to unify this stuff before people waste more resources duplicating this functionality in subtly different ways. I haven't had as much time to work on this issue as I was hoping, but let me know if you have any thoughts on the path forward.

**Comment by cpatrick** [comment]
The hope is to move to playbooks that are developed here: https://github.com/Kitware/gobig. It's currently focused on Big Data™ things, but it should eventually include solid examples of setting up girder, romanesco, ect.

cc: @opadron

**Comment by opadron** [comment]
Right, the gobig repo is meant to be the unified source for devops resources.  In fact, I am working on roles for girder as we speak, and I wasn't aware of some of these repos that @brianhelba mentioned.  I'll definitely be checking them out and trying to integrate the best of each version.
