### ISSUE TITLE
Enabling a plugin should ensure its requirements.txt dependencies are installed

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#873]
Before we actually load the plugin's module, we should install its requirements via pip.

**Comment by brianhelba** [comment]
This would be very helpful.

**Comment by zachmullen** [comment]
One challenge is that the user running the girder server may not have permission to simply `pip install ...`, so we'll need a switch or a fallback for those cases.

**Comment by manthey** [comment]
Could we use pip install --user reliably?

On Tue, Jun 23, 2015 at 4:24 PM, Zach Mullen <notifications@github.com>
wrote:

> One challenge is that the user running the girder server may not have
> permission to simply pip install ..., so we'll need a switch or a
> fallback for those cases.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/girder/girder/issues/873#issuecomment-114631725>.
>



-- 
David Manthey
R&D Engineer
Kitware Inc.
(518) 881-4439

**Comment by brianhelba** [comment]
I've opened #874 as a related issue.

**Comment by cpatrick** [comment]
We could set a virtual env as a config parameter.

**Comment by brianhelba** [comment]
I can't comment on whether its necessary to explicitly specify a virtualenv, or there's some way to make it work implicitly, but we should ensure that pip packages installed to both the global system and in a virtualenv are equally supported as deployment options for Girder.

Personally, all of my deployments of Girder have ran in either a Python virtualenv or a Conda instance.

**Comment by brianhelba** [comment]
@zachmullen @jbeezley Should we consider this fixed, now that plugin ``requirements.txt`` are checked when a plugin is installed?

**Comment by jbeezley** [comment]
If I understand correctly, this issue is about installing deps when the plugin is enabled, not when it is installed.  We don't currently do that.  I'm also inclined to say that allowing that to happen is probably a bad idea.  For security sake, I would want the process running the server to have read-only access to the installation.

**Comment by brianhelba** [comment]
@jbeezley I agree, run-time is the wrong time to be installing packages. I'll let you close the issue.

**Comment by jbeezley** [comment]
@zachmullen Are you okay with closing this?

**Comment by zachmullen** [comment]
Yep!
