### ISSUE TITLE
Plugins should be able to easily specify npm dependencies

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#874]
There should be a documented mechanism to have a plugin define third-party Javascript dependencies which get installed by npm and possibly served via the static path.

You can probably already just make a plugin custom Gruntfile to do most of this, but it would be nice to have a general-purpose mechanism for this use case available in Girder's build system and/or a way to specify simple npm "package.json" files in plugins.

**Comment by brianhelba** [comment]
@jbeezley Has this issue been fixed by your recent improvements?

**Comment by jbeezley** [comment]
Probably, yes.  See the description for how to specify new dependencies here: http://girder.readthedocs.org/en/latest/plugin-development.html#installing-custom-dependencies-from-npm

**Comment by brianhelba** [comment]
@jbeezley Great. I'll let you close this issue.
