### ISSUE TITLE
Editor for more complex JSON metadata

### ISSUE THREAD

**Issue by jeffbaumes** [girder/girder#875]
@danlamanna and I were discussing this issue today. I was sure there was already an issue for this but I could not find it. My proposed plan is twofold:

1. Pretty-print complex JSON metadata in a scrollable field to at least view it better.
2. Next to each property have an "Edit" button that will open up a full JSON editor in a dialog. I say next to each one because even for simple properties the user should be able to transform them into more complex JSON objects if desired.

The editor that @danlamanna is currently looking at is http://jsoneditoronline.org/

Another idea in place of or in addition to this is a single edit button that puts the entire metadata object into a JSON editor.

@danlamanna is currently looking into the first step. Any other thoughts? @brianhelba will this serve your use case?

**Comment by zachmullen** [comment]
:+1: , it's apache licensed, npm installable, and seems well documented. (https://github.com/josdejong/jsoneditor/ for anyone looking for the repo).

As for the UI, I think it might be best not to try to fit both sections into a dialog, it might be cleaner and easier to just open it in a full-width div right below the metadata field being changed.

**Comment by jeffbaumes** [comment]
By "two sections" do you mean the raw JSON and editor versions on the left and right? I was actually just thinking to use the right editor - the one that seems more user friendly - and not even allow the possibility of creating malformed JSON.

**Comment by zachmullen** [comment]
I see what you mean, though I would like to have the ability, at least optionally, to edit the text raw (simply because I'm more used to it). Maybe a single view that can switch between the two modes would be OK.

**Comment by jeffbaumes** [comment]
Yes I see that for some technical folks the raw JSON could be better. Please work with @danlamanna on how you envision the UI layout to work (inline vs. dialog). I just think the JSON editor has its own controls, styles, etc. and it could relieve user mental burden having to just focus on that UI while editing JSON instead of mixing in inline into the Girder UI. Sorta like how inserting/editing diagrams in a Google Doc works.
