### ISSUE TITLE
Call to python in Gruntfile.js should use env

### ISSUE THREAD

**Issue by chrismattmann** [girder/girder#896]
I've noticed while running girder on DARPA memex for our Image Space application that when I use my locally installed python, it won't get picked up and config_parse fails because the system python isn't compatible with the syntax used. I think this is b/c the system python is pre 2.6 but my local python is 2.7+. In order to get it to work with my local python I keep having to change the line where it calls python in the Gruntfile.js to use `env python`. I think this is actually more correct since normally npm is installed at the system level and so that's why it picks up the system python instead of the one from my local environment. If you all agree, I'll submit a quick PR for this.

**Comment by jeffbaumes** [comment]
@zachmullen what do you think?

**Comment by cpatrick** [comment]
@chrismattmann, @jeffbaumes, @zachmullen I think using `env python` makes sense here.

**Comment by zachmullen** [comment]
I am fine with that change :+1:

**Comment by chrismattmann** [comment]
Okey dokey see #924
