### ISSUE TITLE
enable girder-install command line client to install 3rd party plugins

### ISSUE THREAD

**Issue by mgrauer** [girder/girder#899]
allow girder-install to install 3rd party plugins, i.e. those not part of girder core.

This should allow for 

  * installing plugin's python server side code
  * pip installing plugin's requirements.txt specified dependencies

possibly doing these

  * installing plugin's npm dependencies
  * installing plugin's bower dependencies (?)
  * building and installing the plugin's web client code

but probably Grunt wouldn't be available in the case where a user is running girder-install, so instead girder-install should be able to install the web client code that the plugin should already have available in a built and packaged form.

**Comment by mgrauer** [comment]
Add to our grunt package step, so that a 3rd party plugin will get its web client packaged up correctly so that it could be added to a github release for that plugin, and then this will be installable by girder-install.

**Comment by jbeezley** [comment]
'girder-install` does (or should) install server side code and requirements for an arbitrary plugin packaged as a tarball.  One of my original intents with `girder-install` was to support installing from the plugin's git repository, but you are right about node possibly missing.

It would be awesome to have a searchable plugin repository somewhere containing packaged plugins.  The way homebrew does it's package installation from github is the best mechanism like this that I have seen.  Perhaps something hosted on data.kitware.com is another alternative.

**Comment by zachmullen** [comment]
Yeah, the more I think about it the more I like the idea of requiring plugins to do all their own building/packaging so that we can simply download a tarball and plop it down. If we can provide a nice package registry (as a girder plugin!?!) that would be awesome.

**Comment by mgrauer** [comment]
@jbeezley 

I think using girder-install you can install server side code for a 3rd party plugin, but there is a current limitation for installing the web client of the plugin.  I forget the exact details now.

**Comment by jbeezley** [comment]
Yeah, I the limitation is that it won't install the client side content.  I'm not sure the conventions for that were nailed down at the time that I wrote the installer, or at least I wasn't aware of it.

**Comment by jbeezley** [comment]
@zachmullen A girder plugin that hosts girder plugins... this sounds like a corollary to Russell's paradox.

**Comment by zachmullen** [comment]
I'll try not to tear any holes in the universe when we implement this

**Comment by brianhelba** [comment]
+1 for supporting Bower, either as a common tool that's installed available with Girder core, or with a clean procedure for a plugin requiring and using it.

+1 for allowing a plugin to specify its own NPM requirements, which are recursively installed (although if we wanted to only install them for enabled plugins, there are some issues with a circular workflow).

I'm thinking more about the development build process for both of these sub-issues, as I'm not personally needing to fully package my plugins yet. @zachmullen , if support for these doesn't get added to your improvements, I'd like to create separate issues for them.

**Comment by zachmullen** [comment]
Fixed in v1.4.0.
