### ISSUE TITLE
Travis keeps failing

### ISSUE THREAD

**Issue by cpatrick** [girder/girder#908]
What should we do?
- Move off of Travis? (go to buildbot)
- Bug Travis people?

**Comment by cpatrick** [comment]
@girder/developers @girder/owners

**Comment by zachmullen** [comment]
@jbeezley has experience with circle, maybe he could describe his experience with it in comparison to Travis?

**Comment by jbeezley** [comment]
I vote:
- move to [circleci](https://circleci.com/)

**Comment by cpatrick** [comment]
@zachmullen Go on vacation. :smile_cat:

**Comment by jbeezley** [comment]
I can't say whether it is more/less stable because I haven't used it extensively, but at least you can ssh/vnc into the test environment.  Also, you always get root without having to go into a different, less stable infrastructure.

**Comment by cjh1** [comment]
I vote for staying on managed infrastructure rather than buildbot. Despite any problems its likely to be a lot less trouble than administering a bunch of machines at kitware.  circleci does look interesting

**Comment by jbeezley** [comment]
Yes, managing it locally should be avoided if at all possible.
