### ISSUE TITLE
track down assets from an assetstore

### ISSUE THREAD

**Issue by mgrauer** [girder/girder#927]
I want to delete an S3 assetstore, but there are files stored in it and I can't delete it. I'd like some easier way of tracking down these files so that I can remove the assetstore.

**Comment by zachmullen** [comment]
:+1:

**Comment by manthey** [comment]
I think the simplest way is to add an endpoint for GET /assetstore/{id}/files .

**Comment by manthey** [comment]
Added in PR #1516.
