### ISSUE TITLE
Investigate v4 signature for S3 assetstore

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#928]
http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html

See `boto.s3.connection.Connection.generate_url_sigv4`. This new signature method looks like it supports signing all HTTP headers, including Content-Length, which could get around the longstanding issue we have with unverified content length uploads when going direct to S3 from the user agent.

**Comment by brianhelba** [comment]
I was just dealing with this very issue on another side project, and I actually had to implement a large part of the v4 signing protocol from scratch (don't ask), though I have also used Boto's interface.

@zachmullen Let me know if you need me to look at anything on this.

**Comment by zachmullen** [comment]
I got this working for normal uploads, but not for multipart ones. That will require [this change](https://github.com/boto/boto/pull/3322) in boto. Until that goes in, I will probably implement a little workaround function to properly generate the URL for multipart requests.
