### ISSUE TITLE
girder.api.docs.addModel functionality

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#958]
I'm still not understanding how girder.api.docs.addModel is supposed to work, given the way that it's implemented and the way that Swagger defines things. Some history of the variable and function is included in this commit message: https://github.com/girder/girder/commit/0b39ea6434e52a4bbf3ee2a97c726f8226df008a .

[Swagger defines the ``models`` field](https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md#52-api-declaration) as:
> A list of the models available to this resource. Note that these need to be exposed separately for each API Declaration.

See the [Petstore example](http://petstore.swagger.io/) for a demo implementation that uses models. Note that while a resource can expose multiple models, you don't get every possible model on every possible resource.

The way the code is now, there is a single "models" dict, which gets returned in its entirety for every resource description. At the very least, [the line here](https://github.com/girder/girder/blob/109662e3e9cd06bf4eecc29ac554c6c3ede15f32/girder/api/describe.py#L338) should be something like ``'models': docs.models[resource],`` so that you don't get the exact same model description for each separate resource type.

For a nice clean high-level API to set models, we should build the [model objects](https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md#527-model-object) up from individual parameters. However, even with just the low-level API to set models from raw objects, it looks like we need to have something to discriminate which resource type a model is being applied to. Since the existing API has no way to require that parameter, fixing this issue seems to necessarily require a breaking API change.

I have no problem with exposing this functionality at a low-level at first, but I'd like to get a more sane API figured out now. Some testing would be good too.

Of course, if I'm missing something, please let me know. Code examples from @cjh1 that show how this currently is being used would be helpful.

**Comment by brianhelba** [comment]
@cjh1 @zachmullen @cpatrick I'd welcome your feedback.

**Comment by cjh1** [comment]
```
    addModel('Params', {
        "id": "Params",
        "properties": {
            "aProperty": {"type": "string", "description": "The property."}
        }
    })

    create.description = (Description(
        'Create a bar bar'
    )
        .param(
            'body',
            'The params for this bar bar',
            dataType='Params',
            required=True, paramType='body'))

```

**Comment by zachmullen** [comment]
Another usage is to document the return type:

```
addModel('Folder', {
    ...
})

...
foo.description = (Description('foo')
    .responseClass('Folder')
    ...
```

**Comment by brianhelba** [comment]
Closing in favor of using https://github.com/girder/girder/issues/971 to continue this line of development.
