### ISSUE TITLE
Add support for using JSON schema to validate and document requests

### ISSUE THREAD

**Issue by cjh1** [girder/girder#964]
So I thought I had raise an issue about this before, but I could find it ...

I have been used JSON schema in to validate incoming requests, it vastly reduces the amount of code you have to right to validate requests. Swagger uses JSON schema ( well a subset ) for defining models. It would be nice if we could provide a mechanism to allow a user to define their requests or models using JSON schema once and this could be used for validation and documentation ...

**Comment by zachmullen** [comment]
This sounds like a great idea, do you have a link to an example where you are using this?

**Comment by cjh1** [comment]
Sure, [there is a schema definition](https://github.com/OpenChemistry/mongochemserver/blob/calculations/girder/molecules/server/models/calculation.py#L24-L65) and here is it [use in a validate method](https://github.com/OpenChemistry/mongochemserver/blob/calculations/girder/molecules/server/models/calculation.py#L88-L92) and my attempt to use it for the [doc] (https://github.com/OpenChemistry/mongochemserver/blob/calculations/girder/molecules/server/calculation.py#L103-L105) this doesn't work so well, you just get the first level of property haven't looked into why.

**Comment by cjh1** [comment]
Was planning on tackling the validation part of this first.

**Comment by mgrauer** [comment]
@cjh1 Your three links in the above comment are dead to me.  Are they still valid or is there a permissions issue?

**Comment by cjh1** [comment]
Here are some new links, an example of a [schema](https://github.com/Kitware/HPCCloud/blob/master/server/hpccloud/server/models/simulation.json) and here is the [validation](https://github.com/Kitware/HPCCloud/blob/master/server/hpccloud/server/models/simulation.py#L44-L50)

**Comment by cjh1** [comment]
@mgrauer  So my plan was to add an optional schema attribute on a model, if set then we will do the validation using jsonschema. We probably what to validate the schema itself when the model it loaded, in order to separate out schema issues from data validation issues.

**Comment by mgrauer** [comment]
That sounds reasonable, so will this work be validating the model or the API endpoints as well?

**Comment by cjh1** [comment]
That is a good point, to start with just the model I think.
