### ISSUE TITLE
server_upload test occasionally failing on travis

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#969]
```
24: ======================================================================
24: ERROR: setUpModule (tests.cases.upload_test)
24: ----------------------------------------------------------------------
24: Traceback (most recent call last):
24:   File "/home/travis/build/girder/girder/tests/mock_s3.py", line 102, in startMockS3Server
24:     test_socket.bind(('0.0.0.0', port))
24: OSError: [Errno 98] Address already in use
24: 
24: During handling of the above exception, another exception occurred:
24: 
24: Traceback (most recent call last):
24:   File "/home/travis/build/girder/girder/tests/cases/upload_test.py", line 34, in setUpModule
24:     base.startServer(mockS3=True)
24:   File "/home/travis/build/girder/girder/tests/base.py", line 76, in startServer
24:     mockS3Server = mock_s3.startMockS3Server()
24:   File "/home/travis/build/girder/girder/tests/mock_s3.py", line 106, in startMockS3Server
24:     if err[0] != errno.EADDRINUSE:
24: TypeError: 'OSError' object is not subscriptable
24: 
24: ----------------------------------------------------------------------
24: Ran 0 tests in 0.189s
```

@manthey Do you know what could be causing this?

**Comment by zachmullen** [comment]
That's actually pretty straightforward, looking at the code, we are attempting to ignore ports in use, but (at least in python 3) we can't use `err[0]`. I'll try to fix this.

**Comment by manthey** [comment]
Aside from what you just found, we try to pick a port that is unlikely to be in use, namely 31100 + (pid%100).  We could be more intelligent in how we pick that port to reduce the collision likelihood.  For instance, for the web client, we ask for a different port for each test in the CMake file, and we could do something similar.

**Comment by brianhelba** [comment]
@manthey I think this is a good approach. I've seen other library software tests attempt to pick a random high-numbered port, and repeatedly try different random ports if the the first one(s) are in use. Non-determinism in tests is generally a bad thing, but this seems harmless. A random port series also has the advantage of being more likely to succeed on developer machines, where high-numbered ports may be in use unpredictably.

**Comment by manthey** [comment]
We used to use high-numbered ports, but they are more likely to be in use,
as they are used for outgoing connections.  A while ago I migrated away
from high-numbered ports which greatly reduced the intermittent issues.
Because we can run tests in parallel, it is difficult to ensure that a port
is free; it is better if a test has an explicit port.  See PR #636 for more
commentary.

On Wed, Sep 9, 2015 at 4:42 PM, Brian Helba <notifications@github.com>
wrote:

> @manthey <https://github.com/manthey> I think this is a good approach.
> I've seen other library software tests attempt to pick a random
> high-numbered port, and repeatedly try different random ports if the the
> first one(s) are in use. Non-determinism in tests is generally a bad thing,
> but this seems harmless. A random port series also has the advantage of
> being more likely to succeed on developer machines, where high-numbered
> ports may be in use unpredictably.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/girder/girder/issues/969#issuecomment-139039759>.
>



-- 
David Manthey
R&D Engineer
Kitware Inc.
(518) 881-4439
