### ISSUE TITLE
girder-client: Upload "latest" version to pypi

### ISSUE THREAD

**Issue by jcfr** [girder/girder#974]
As of Sept 12th 2015,  the [latest girder-client documentation](http://girder.readthedocs.org/en/latest/python-client.html)  mentions that it could be installed using

```
pip install girder-client
```

This is not completely true, running this command will install version `1.0.2`.

```
$ pip install girder_client
Collecting girder-client
[...]
Installing collected packages: girder-client
  Running setup.py install for girder-client
Successfully installed girder-client-1.0.2
```

This is a problem. 

For example, the documentation mentions that the method `listItem` has the `name` parameter, but this has been added on Sept 4th in 66471e17 but version  `1.0.2` has been [uploaded on July 27th](https://pypi.python.org/pypi/girder-client/1.0.2).

I would suggest that:
- the `latest` version is uploaded an pypi automatically each time a new commit is pushed on `master`. In that case, the documentation would specify `pip install girder-client --pre`. See [here](https://pip.pypa.io/en/latest/reference/pip_install.html#pre-release-versions) for the `--pre` option documentation.
- the `vx.y.z` documentation specifies `pip install girder-client==vx.y.z`

Cc: @girder/developers

**Comment by jcfr** [comment]
Cc: @mgrauer  @cpatrick

**Comment by cpatrick** [comment]
@jcfr This is a good catch.

I think using the `--pre` option for both the client and server would be good. This would force us to automate our packaging and documentation changes which I think would generally be a good thing.

**Comment by cryos** [comment]
I was just hit by a similar issue with listFolder in the client with the optional name parameter, it would be great to ensure new releases also update the client. I am getting 1.1.0 at this time, and will use listResource for now building up my own parameter object.

**Comment by danlamanna** [comment]
@jbeezley This can be closed now right? https://pypi.org/project/girder-client/#history

**Comment by jbeezley** [comment]
Yes

**Comment by jcfr** [comment]
What is the process to release a pre-release ? It would be great to avoid "spamming" each time there is a merge to master.

Instead, I suggest to push the latest dev release as a GitHub release that could be install using:

```
pip install itk --upgrade --no-index \
  -f https://github.com/girder/girder/releases/tag/latest-girder-client
```

**Comment by jbeezley** [comment]
A PyPI prerelease is generated on merge to master (and anytime a semver tag is pushed).  You can install the latest with `pip install --pre girder-client`.

**Comment by jcfr** [comment]
I guess that will work. 

The "issue" is that pypi will be littered with a lot of .dev packages. Looking back at the PEP, pre-release are usually:

```
X.YaN   # Alpha release
X.YbN   # Beta release
X.YrcN  # Release Candidate
```

See https://www.python.org/dev/peps/pep-0440/#pre-releases

**Comment by jbeezley** [comment]
Development releases are described in the same PEP.  To be more precise, we push development releases on every push to master.  Pre-releases and releases are created when pushing a tag.

**Comment by jcfr** [comment]
My proposal would be to publish to pypi only pre-release like this one:

![image](https://user-images.githubusercontent.com/219043/56231046-7d268180-604b-11e9-80a2-a1ddf59fc759.png)

And only publish development packages on GitHub release:

![image](https://user-images.githubusercontent.com/219043/56231072-8e6f8e00-604b-11e9-83a6-b776ec44224c.png)

Doing so would avoid uploading pypi with a lot of development packages while being a "good open-source citizen" (i think). Only "true" pre-release (marked as such with a tag) would be available on PyPi.

Only the latest development package would be pushed as GitHub release assets.

**Comment by jcfr** [comment]
All of that said, this is a nitpick. It is great to see latest releases available :+1:
