### ISSUE TITLE
doc: Incorrect versions reported on readthedocs

### ISSUE THREAD

**Issue by jcfr** [girder/girder#975]
As of September 12th 2015, incorrect versions seem to be reported. Looking at the screenshot below we can see there are version like `969` and `948`.

![girder-readthedocs-incorrect-version](https://cloud.githubusercontent.com/assets/219043/9833630/c9e94aec-596b-11e5-9b04-6382619dbccd.png)

Related to #974

Cc: @zachmullen

**Comment by jcfr** [comment]
Cc: @girder/developers 

I checked again and the incorrect version are still listed. Who has the credential to clean readthedocs.org ?

**Comment by zachmullen** [comment]
Thanks JC, just fixed it. I guess RTD assumes if your branch name is purely numeric, that it is a version tag.
