### ISSUE TITLE
item view: Lazily retrieve item metadata

### ISSUE THREAD

**Issue by jcfr** [girder/girder#976]
Considering the case where DICOM files are uploaded into a folder as item with metadata being all the DICOM tags (in my example, around ~80 tags)  expect the one associated with binary data, showing the content of the folder take ~8s.

![girder-item-in-folder-with-metadata](https://cloud.githubusercontent.com/assets/219043/9833954/b565e066-5976-11e5-8db5-8a40a92bd54f.png)

By removing the field `meta` from  the `exposeFields` in the `item` model, the time is cut down to `350ms`. This quick test confirms metadata should be retrieved lazily.

A possible approach could be to:
- add a new parameter named `includeMetadata` to the route `GET /item`. By default it would be `True` to maintain backward compatibility. 
- add a new route `GET /item/{id}/metadata`
- update `ItemCollections.js` setting `self.params["includeMetadata"] = False`
- update `ItemModel.js` adding a method `getMetadata()`
- update `render` function in `ItemView.js` to call  `getMetadata()` and update `item` model with the lazily retrieved metadata. 

Cc: @girder/developers

**Comment by zachmullen** [comment]
This sounds reasonable to me, and since we already have a widget specifically for metadata display, updating the view asynchronously shouldn't be a problem.

**Comment by zachmullen** [comment]
@jcfr I just looked more closely at this screenshot, and noticed it was only transferring a total of 457KB of data, which certainly shouldn't take 8 seconds... where is this deployed? I think we should try and profile this and see why it's taking that much time.

**Comment by jcfr** [comment]
This was my local instance. If you give me access to a deployed instance, I could upload the data in a collection/folder of your choice.

**Comment by zachmullen** [comment]
You should be able to upload here: https://data.kitware.com/#user/5419fefa8d777f0fcc59b6bd/folder/56005a768d777f6ddc3da1fb

**Comment by jcfr** [comment]
Trying to login with username/pwd returns `KeyError: KeyError('hashAlg',)` error. I will try with the google auth.

**Comment by jcfr** [comment]
Using google auth worked ..

**Comment by zachmullen** [comment]
That bug was just fixed on #984 but has not yet been deployed to data.kitware.com yet.

**Comment by jcfr** [comment]
Could we consider upgrading data.kitware.com ? My upload script depends on 6c0566947893f
In the mean time, I will disable the check for existing item for similar name.

**Comment by jcfr** [comment]
All set. See https://data.kitware.com/#user/5419fefa8d777f0fcc59b6bd/folder/56005a768d777f6ddc3da1fb

Performance are better .. it takes 1secs.

That said, I still think it should be possible to retrieve item list independently of the associated metadata.

**Comment by zachmullen** [comment]
Thanks for uploading, I'm seeing ~600ms to load it after several refreshes.

> That said, I still think it should be possible to retrieve item list independently of the associated metadata.

:+1:

**Comment by manthey** [comment]
Closing this as it behaves well with the current system.
