### ISSUE TITLE
Zip files >= 2 Gb and < 4Gb can be invalid

### ISSUE THREAD

**Issue by manthey** [girder/girder#977]
When a zip file is generated that is greater than 2Gb in size and less than 4 Gb, it is sometimes generated without the Zip64 footer, resulting in an invalid zip file.

**Comment by zachmullen** [comment]
@manthey thanks for the report. Are you investigating this further? If not, could you provide some details about the size of file you saw this with, and how many records it contained?

**Comment by manthey** [comment]
@brianhelba actually found the problem.  He has a directory with ~1500 items, each of which contains 8 or so files.  Those files range from 2.5 kb to 2 Mb.  I'm not sure what is triggering the problem yet, as the code superficially looks like it should do the right thing.

I'll probably have a fix for this today or tomorrow.

**Comment by zachmullen** [comment]
Awesome :smile:

**Comment by manthey** [comment]
It turns out that this is a bug that occurs when any file is located in the zip file at a position >= 2Gb.  The existing large-file tests used a single massive file.  Adding a small file at the end of the archive showed off the problem.  We should have noticed that we weren't covering a few lines and tested them.

**Comment by zachmullen** [comment]
Good find, is the fix straightforward?

**Comment by manthey** [comment]
Yes; trivial.  I'm working on the test, then I'll submit.

**Comment by manthey** [comment]
Resolved in PR #987.
