### ISSUE TITLE
Error logging in to data.kitware.com

### ISSUE THREAD

**Issue by jeffbaumes** [girder/girder#982]
This error appears in the login window:

KeyError: KeyError('hashAlg',)

When attempting to login to data.kitware.com using normal (non-google) authentication.

@zachmullen suggested this is likely an issue when you create a user by logging in with google oauth and then later attempting to login via password.

**Comment by brianhelba** [comment]
Some error checking with an error message is probably sufficient to resolve this issue, but please keep https://github.com/girder/girder/issues/983 in mind as a desirable future goal.

**Comment by brianhelba** [comment]
Look what I dug up from the pile in the basement: https://github.com/girder/girder/issues/675

**Comment by brianhelba** [comment]
And https://github.com/girder/girder/issues/820 too.

**Comment by zachmullen** [comment]
Nice, get to close 3 issues at once :)
