### ISSUE TITLE
Support users with login credentials from multiple sources

### ISSUE THREAD

**Issue by brianhelba** [girder/girder#983]
Users should be able to have both a password and an OAuth credential associated with their account, and use either to log in.

If the user account was first created with OAuth, then an option to add a new password needs to be exposed.

If the user account was first created with a password, a mechanism to associate an OAuth credential with the account needs to be added. Additionally, since creating new accounts with OAuth is so easy, it's possible that a user may already (possibility accidentally) have a 2nd OAuth account, which they want to merge / absorb into their primary password-created account.

**Comment by zachmullen** [comment]
> If the user account was first created with a password, a mechanism to associate an OAuth credential with the account needs to be added. Additionally, since creating new accounts with OAuth is so easy, it's possible that a user may already (possibility accidentally) have a 2nd OAuth account, which they want to merge / absorb into their primary password-created account.

This part is already possible. It's only broken going from the other direction, and that should be fixed with the fix for #982

**Comment by brianhelba** [comment]
@zachmullen You're right: https://github.com/girder/girder/blob/master/plugins/oauth/server/providers.py#L123

Closing this as already implemented.
