### ISSUE TITLE
Consider user-facing explicit token management

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#995]
@jcfr just brought up this issue -- it may be nice to allow users of programmatic clients to be able to create (auth) tokens explicitly, even controlling the duration, via a REST endpoint. This would ideally be able to be done *without* needing to provide your password, via either a new REST endpoint or via modification of the existing `GET user/authentication` route.

This could be achieved by allowing users to create an API key that could be a proxy for their password, much like we had in Midas. This could be exposed with a new kwarg in the python client, e.g.

```
client = GirderClient(...)
client.authenticate(apiKey='foo')
```

**Comment by jcfr** [comment]
:+1: 

Leveraging SSH keys _a la GitHub_ would also be nice too.

**Comment by zachmullen** [comment]
SSH is a great, robust solution, but I propose we go with something like the AWS shared secret key instead. It has a couple of advantages:

1) Simpler than SSH for non-developers to understand and use.
2) Much simpler for us to implement and maintain.

Just like with AWS, I think the value should only be shown to the user at the time it is created. If the user requests a new one, it takes the place and therefore invalidates the old key.

**Comment by jcfr** [comment]
> something like the AWS shared secret key instead.

Makes sense.

**Comment by opadron** [comment]
+1

**Comment by kotfic** [comment]
+1

**Comment by jeffbaumes** [comment]
How does this relate to Girder becoming an OAuth provider? Is this a custom auth/token scheme? Should we just implement OAuth instead?

**Comment by zachmullen** [comment]
This is orthogonal to being an OAuth provider. Correct me if I'm wrong, but I think all @jcfr wants to do is be able to programmatically authenticate with something other than his password. In the simplest form of this, we can simply have an API key that acts as a proxy for the user's password, and whose only advantage is that it's a randomly generated string rather than their actual password.

A more robust solution would look like what AWS does, where the key isn't sent directly, but is rather used to sign (via HMAC) all the relevant parameters of a request. (That would be a lot of effort to implement and support, though, since it involves things like clock skew, managing encodings, etc.). This is nice because the shared secret isn't sent over the wire, and because it allows users to authorize requests to girder on behalf of other user agents. However, for @jcfr's purposes, this is no better than the first solution, since his concern was about writing his password in plaintext in a file on his system.

**Comment by jeffbaumes** [comment]
Thanks for the explanation. Carry on :)

**Comment by jcfr** [comment]
> be able to programmatically authenticate with something other than his password

+1

> can simply have an API key

As @zachmullen mentioned to me, we would have the API key acting as the password, it means that script would simply specify username/apikey instead of username/password.


> since his concern was about writing his password in plaintext in a file on his system

I could also have setup an env variable. Either way, for scripting purpose having the apikey is definitively more reasonable.

**Comment by brianhelba** [comment]
+1 I'd have a use for this now too.

**Comment by jcfr** [comment]
Similarly to what is done for [github personal access token](https://help.github.com/articles/creating-an-access-token-for-command-line-use/), girder token could be regenerated, deleted, etc ... 

Features:
* Regeneration
* Last time of use
* Deleting a token
* Setting scopes on creation, editing scopes for existing token.  Scope would allow to grant only read access to a given token.

**Comment by jbeezley** [comment]
+1 Scoped tokens would be great automated components that only need limited permissions.

**Comment by ronichoudhury** [comment]
+1
